### ISSUE TITLE
Xray Core

### ISSUE THREAD

**Issue by THMaST3R** [Mahdi-zarei/nekoray#10]
Can you add a Xray core please?

**Comment by Mahdi-zarei** [comment]
what functionalities will Xray add to the Project? As far as I am concerned sing-box provides all legitimate features that Xray has.

**Comment by misagh72** [comment]
no fragment support in sing-box

**Comment by Mahdi-zarei** [comment]
> no fragment support in sing-box

Fragment is practically a pitiful trick that can be easily blocked, I have been using ws over cloudflare for a very long time and neither my domain was blocked nor my configuration has been slowed down ( besides the times when internet traffic is disrupted as a whole ), so I suggest you use a proper configuration and don't rely on temporary solutions. In case you really want to use fragment I can suggest hiddify desktop client, it does support fragment. But I need a better reason than fragment to bring back Xray, as it has poor code quality (various bugs, memory leaks), is much harder to configure and introduces numerous complications to the code base of the GUI.

**Comment by midncircus** [comment]
I agree.

The sole advantage of Xray that justifies itself is that it supports the Whitelist mode by process name for Tun.

Only the Blacklist mode works as intended for sing-box. It just ignores the Whitelist settings.

![2024-06-06_001946](https://github.com/Mahdi-zarei/nekoray/assets/171871443/f2c3e99e-273a-4cd5-866a-263ec01fd27b)

**Comment by M-Sadegh-M** [comment]
> what functionalities will Xray add to the Project? As far as I am concerned sing-box provides all legitimate features that Xray has.

https://github.com/XTLS/Xray-core/pull/3534#issuecomment-2227584482
