### ISSUE TITLE
请求添加TLS分片功能

### ISSUE THREAD

**Issue by lleeopen** [Mahdi-zarei/nekoray#101]
## 描述建议

**请求添加TLS分片功能**

## 建议的必要性

**重要**

**Comment by M-Sadegh-M** [comment]
https://github.com/Mahdi-zarei/nekoray/issues/10#issuecomment-2123316310

**Comment by Mahdi-zarei** [comment]
Given that Nekoray is a wrapper for sing-box and sing-box has not added these features yet, for the time being there is no plan to add these features. Also I have not heard much about the success of warp with noise and fragment compared to normal methods like properly configured SS or trojan.
