### ISSUE TITLE
BUG: مشکلات نسخه 4.1.0

### ISSUE THREAD

**Issue by M-Sadegh-M** [Mahdi-zarei/nekoray#102]
هیچ کدوم از کانفیگ هام در این نسخه کار نمیکنه در حالی که در نسخه قبل همگی سالم هستند
همچنین clone کردن کار نمیکنه
ویندوز 11

https://github.com/user-attachments/assets/6fee3984-c6bd-47b4-94d4-504c6a8b8acf

**Comment by Mahdi-zarei** [comment]
مشکل کلون و کلا ایمپورت توی گروه هایی که سابکریبشن دارن هست و به زودی رفع میشه
برای مشکل وصل نشدن پیشنهاد میدم کانفیگ های جنریت شده هر دو ورژن رو بررسی کنید و تفاوتش رو من بگید، اینکه ارور 403 میدن احتمالا به این خاطر هست که یه پارامتر عوض شده.

**Comment by M-Sadegh-M** [comment]
من برای اینکه تفاوت را نشون بدم یک نسخه خام دانلود کردم و فقط لینک ساب بهش اضافه کردم
نسخه قبلی تنظیمات روتینگ شخصی خودم را داره ولی همونم اگه به اخرین نسخه اپدیت کنم کانفیگ ها همگی غیرفعال میشن.
ورژن قبلی
'
{"dns":{"independent_cache":true,"rules":[{"domain":[],"domain_keyword":[],"domain_regex":[],"domain_suffix":[],"rule_set":["category-ir_SITE","ir_SITE"],"server":"dns-direct"}],"servers":[{"address":"https://8.8.8.8/dns-query","address_resolver":"dns-local","detour":"proxy","strategy":"ipv4_only","tag":"dns-remote"},{"address":"local","address_resolver":"dns-local","detour":"direct","strategy":"ipv4_only","tag":"dns-direct"},{"address":"rcode://success","tag":"dns-block"},{"address":"local","detour":"direct","tag":"dns-local"}]},"inbounds":[{"domain_strategy":"ipv4_only","listen":"::","listen_port":2080,"sniff":true,"sniff_override_destination":false,"tag":"mixed-in","type":"mixed"}],"log":{"level":"info"},"outbounds":[{"domain_strategy":"ipv4_only","flow":"","packet_encoding":"","server":"172.66.44.109","server_port":443,"tag":"proxy","tls":{"alpn":["http/1.1"],"enabled":true,"server_name":"bPb-WORkEr-pANel-1Mi.PaGES.Dev","utls":{"enabled":true,"fingerprint":"randomized"}},"transport":{"headers":{"Host":"bPB-WOrkeR-pAnel-1mI.PAgeS.dev"},"path":"/bHgNt50EISQXjE2M/MTQxLjE0NS4xOTkuMTg4","type":"ws"},"type":"vless","uuid":"c2c8a201-09b9-47a7-b336-fcf1657f54a8"},{"tag":"direct","type":"direct"},{"tag":"block","type":"block"},{"tag":"dns-out","type":"dns"}],"route":{"final":"proxy","rule_set":[{"format":"binary","path":"rule_sets/ir_IP.srs","tag":"ir_IP","type":"local"},{"format":"binary","path":"rule_sets/category-ir_SITE.srs","tag":"category-ir_SITE","type":"local"},{"format":"binary","path":"rule_sets/ir_SITE.srs","tag":"ir_SITE","type":"local"},{"format":"binary","path":"rule_sets/category-ads-ir_SITE.srs","tag":"category-ads-ir_SITE","type":"local"}],"rules":[{"outbound":"dns-out","protocol":"dns"},{"ip_is_private":true,"outbound":"direct"},{"outbound":"direct","rule_set":["ir_IP","category-ir_SITE","ir_SITE"]},{"outbound":"block","rule_set":["category-ads-ir_SITE"]},{"ip_cidr":["91.107.164.204"],"outbound":"direct"}]}}
'
نسخه اخر
'
{"dns":{"rules":[],"servers":[{"address":"8.8.8.8","address_resolver":"dns-local","detour":"proxy","strategy":"","tag":"dns-remote"},{"address":"local","address_resolver":"dns-local","detour":"direct","strategy":"","tag":"dns-direct"},{"address":"rcode://success","tag":"dns-block"},{"address":"local","detour":"direct","tag":"dns-local"}]},"inbounds":[{"domain_strategy":"","listen":"127.0.0.1","listen_port":2080,"sniff":true,"sniff_override_destination":false,"tag":"mixed-in","type":"mixed"}],"log":{"level":"info"},"outbounds":[{"domain_strategy":"","flow":"","packet_encoding":"","server":"172.66.47.147","server_port":443,"tag":"proxy","tls":{"alpn":["http/1.1"],"enabled":true,"server_name":"BpB-WOrKER-PaneL-1mi.Pages.dEv","utls":{"enabled":true,"fingerprint":"randomized"}},"transport":{"headers":{},"path":"/ayB04GFurIIL388e/MTQxLjE0NS4xOTkuMTg4","type":"ws"},"type":"vless","uuid":"c2c8a201-09b9-47a7-b336-fcf1657f54a8"},{"tag":"direct","type":"direct"},{"tag":"block","type":"block"},{"tag":"dns-out","type":"dns"}],"route":{"final":"proxy","rule_set":[],"rules":[{"outbound":"dns-out","protocol":"dns"}]}}
'

**Comment by M-Sadegh-M** [comment]
برام جالبه چرا فقط کانفیگ اول کار میکنه ولی اون 3 تا کار نمی کنن مگه میشه از یک لینک ساب 2 چند مدل کانفیگ جنریت بشه
یکم تو روتینگ هم تغییرات دادم ولی بازم فرقی نداشت، فقط همون کانفیگ کار میکنه

این کانفیگ اول ویدئو که فقط همون کار میکنه، 

`
{"dns":{"rules":[{"domain":["bpb-worker-panel-1mi.pages.dev"],"domain_keyword":[],"domain_regex":[],"domain_suffix":[],"rule_set":["category-ir_SITE"],"server":"dns-direct"}],"servers":[{"address":"https://8.8.8.8/dns-query","address_resolver":"dns-local","detour":"proxy","strategy":"ipv4_only","tag":"dns-remote"},{"address":"local","address_resolver":"dns-local","detour":"direct","strategy":"ipv4_only","tag":"dns-direct"},{"address":"rcode://success","tag":"dns-block"},{"address":"local","detour":"direct","tag":"dns-local"}]},"inbounds":[{"domain_strategy":"ipv4_only","listen":"127.0.0.1","listen_port":2080,"sniff":true,"sniff_override_destination":false,"tag":"mixed-in","type":"mixed"}],"log":{"level":"info"},"outbounds":[{"domain_strategy":"ipv4_only","flow":"","packet_encoding":"","server":"bpb-worker-panel-1mi.pages.dev","server_port":443,"tag":"proxy","tls":{"alpn":["http/1.1"],"enabled":true,"server_name":"BPB-wORKer-PanEl-1mI.PaGEs.deV","utls":{"enabled":true,"fingerprint":"randomized"}},"transport":{"headers":{},"path":"/I49dvp8Pd1aO7QLv/MTQxLjE0NS4xOTkuMTg4","type":"ws"},"type":"vless","uuid":"حذف کردم"},{"tag":"direct","type":"direct"},{"tag":"block","type":"block"},{"tag":"dns-out","type":"dns"}],"route":{"final":"proxy","rule_set":[{"format":"binary","path":"rule_sets/ir_IP.srs","tag":"ir_IP","type":"local"},{"format":"binary","path":"rule_sets/category-ir_SITE.srs","tag":"category-ir_SITE","type":"local"}],"rules":[{"outbound":"dns-out","protocol":"dns"},{"outbound":"direct","rule_set":["ir_IP","category-ir_SITE"]},{"ip_is_private":true,"outbound":"direct"}]}}
`

**Comment by Mahdi-zarei** [comment]
مشکل توی هدر host هست که توی وب سوکت داره override میشه.
پیشنهاد میدم بعد از رفع مشکل کانفیگ ها رو عوض کنید که پخش نشن.

**Comment by M-Sadegh-M** [comment]
> پیشنهاد میدم بعد از رفع مشکل کانفیگ ها رو عوض کنید که پخش نشن.
از داخل کانفیگ ها uuid را حذف کردم، پخش هم بشه رایگان هست و مشکلی نیست. (^_^)

چندتا پیشنهاد هم داشتم:

 - اگه ممکنه کلیدهای میانبر مثل قبل باشه.
 - گزینه resolve دامنه به ایپی کارایی داشت
 - گزینه استاپ تست هم کارایی داشت به خصوص وقتی لیست های بلند را تست میگرفتم.

**Comment by Mahdi-zarei** [comment]
> > پیشنهاد میدم بعد از رفع مشکل کانفیگ ها رو عوض کنید که پخش نشن.
> 
> از داخل کانفیگ ها uuid را حذف کردم، پخش هم بشه رایگان هست و مشکلی نیست. (^_^)
> 
> چندتا پیشنهاد هم داشتم:
> 
>     * اگه ممکنه کلیدهای میانبر مثل قبل باشه.
> 
>     * گزینه resolve دامنه به ایپی کارایی داشت
> 
>     * گزینه استاپ تست هم کارایی داشت به خصوص وقتی لیست های بلند را تست میگرفتم.

2 مورد اول رو در صورتی که درخواست های بیشتری بیاد برمیگردونم به قبل، در لحظه حقیقتش صرفه نداره
مورد سوم حذف نشده، فقط وقتی اسپید تست در حال انجام باشه نشون داده میشه و بی مورد نشون داده نمیشه که شلوغ نشه منو.

**Comment by Mahdi-zarei** [comment]
نسخه جدید رو تست کنید.

**Comment by M-Sadegh-M** [comment]
> 2 مورد اول رو در صورتی که درخواست های بیشتری بیاد برمیگردونم به قبل، در لحظه حقیقتش صرفه نداره 

میانبرها به نظرم مهم تر هستند، دیگه به قبلیا 2 ساله عادت کردیم برای تست همیشه ctrl+shift+u میزدم 
هرچند که جدیدا هم زمان بگذره عادت میشه. ولی فعلا مغز هی باگی میشه. خخخخخخ

**Comment by Mahdi-zarei** [comment]
> > 2 مورد اول رو در صورتی که درخواست های بیشتری بیاد برمیگردونم به قبل، در لحظه حقیقتش صرفه نداره
> 
> میانبرها به نظرم مهم تر هستند، دیگه به قبلیا 2 ساله عادت کردیم برای تست همیشه ctrl+shift+u میزدم هرچند که جدیدا هم زمان بگذره عادت میشه. ولی فعلا مغز هی باگی میشه. خخخخخخ

نسخرو دادم قبل از کامنت
اگر تا نسخه بعدی عادت نکردین یادآوری کنید برمیگردونم 😄

**Comment by M-Sadegh-M** [comment]
> نسخه جدید رو تست کنید.

بله مشکل برطرف شد

**Comment by M-Sadegh-M** [comment]
مورد زیر هم به چشم خورد، گویا با 2 روش متفاوت تست گرفته میشه

https://github.com/user-attachments/assets/e0c1fe6e-0730-4b0b-90d2-5a786e2505f3

**Comment by Mahdi-zarei** [comment]
> مورد زیر هم به چشم خورد، گویا با 2 روش متفاوت تست گرفته میشه که تفاوتش در پینگ زیاده
> bandicam.2024-08-14.19-15-47-494.mp4

روش تست یکی هست
در کل https به علت داشتن هندشیک مخصوص به خودش زمان بیشتری طول میشه تا جواب بگیره و برای همین از http استفاده میشه که زمان درست رو بده، https به خاطر هندشیکش 3 بار رفت و برگشت داره و منطقا حدود 3 برابر لیتنسی بین سرور ها طول میکشه تا جواب بگیره

**Comment by M-Sadegh-M** [comment]
> > مورد زیر هم به چشم خورد، گویا با 2 روش متفاوت تست گرفته میشه که تفاوتش در پینگ زیاده
> > bandicam.2024-08-14.19-15-47-494.mp4
> 
> روش تست یکی هست در کل https به علت داشتن هندشیک مخصوص به خودش زمان بیشتری طول میشه تا جواب بگیره و برای همین از http استفاده میشه که زمان درست رو بده، https به خاطر هندشیکش 3 بار رفت و برگشت داره و منطقا حدود 3 برابر لیتنسی بین سرور ها طول میکشه تا جواب بگیره

بله تا حدودی اشنایی دارم ولی اگه دقت کنید وقتی https میشه پینگ میاد پایین

**Comment by Mahdi-zarei** [comment]
> > > مورد زیر هم به چشم خورد، گویا با 2 روش متفاوت تست گرفته میشه که تفاوتش در پینگ زیاده
> > > bandicam.2024-08-14.19-15-47-494.mp4
> > 
> > 
> > روش تست یکی هست در کل https به علت داشتن هندشیک مخصوص به خودش زمان بیشتری طول میشه تا جواب بگیره و برای همین از http استفاده میشه که زمان درست رو بده، https به خاطر هندشیکش 3 بار رفت و برگشت داره و منطقا حدود 3 برابر لیتنسی بین سرور ها طول میکشه تا جواب بگیره
> 
> بله تا حدودی اشنایی دارم ولی اگه دقت کنید وقتی https میشه پینگ میاد پایین

این عجیبه
