### ISSUE TITLE
BUG: 设置GeoSite URL 后，Download and Replace 失败，但GeoIp URL没有问题

### ISSUE THREAD

**Issue by shamikon** [Mahdi-zarei/nekoray#106]
![image](https://github.com/user-attachments/assets/ae81899c-fd24-45af-ab6c-8e8d176d1b9e)

**Comment by Turbine8845** [comment]
GitHub experienced a significant outage recently, which might be the reason you encountered this error. I haven’t experienced this issue myself. Please try testing again, and if the problem persists, provide more information so the maintainer can better identify and address the root cause.
