### ISSUE TITLE
BUG: url test group error

### ISSUE THREAD

**Issue by ig-man** [Mahdi-zarei/nekoray#107]
## Win7 x64 releases 4.1.0 & 4.1.1
Can't run the url test group. The test stops immediately.
Get log:
"grpc-status error code: 2 , error msg: outbounds[4].transport: unknown transport type: kcp
[Error] gRPC: QNetworkReply::NetworkError code: 301"

**Comment by Mahdi-zarei** [comment]
Try 4.1.2

**Comment by papan2084** [comment]
Hello, I can't find, the correct configurations, without a download test

**Comment by ig-man** [comment]
Good, thank you!

**Comment by papan2084** [comment]
thank you for being

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
