### ISSUE TITLE
BUG: error windows 7

### ISSUE THREAD

**Issue by ruboard** [Mahdi-zarei/nekoray#109]
[4.1.2](https://github.com/Mahdi-zarei/nekoray/releases/tag/4.1.2)
nekoray-4.1.2-2024-08-16-windows7.Zip 

I was very happy when I found it nekoray for win7, but the joy did not last long.
When starting, a window pops up
"the procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll"

exactly the same as here: https://github.com/MatsuriDayo/nekoray/issues/848

**Comment by Mahdi-zarei** [comment]
Please read the readme of the project, you need to utilize a third party tool to be able to run nekoray on windows 7

**Comment by parhelia512** [comment]
Try fork https://github.com/parhelia512/nekoray-win7/releases

**Comment by Mahdi-zarei** [comment]
> Try fork https://github.com/parhelia512/nekoray-win7/releases

If you are interested, you can open a PR and contribute your changes so that nekoray can support windows 7 out of the box as well.
