### ISSUE TITLE
BUG: Fake Dns not working properly

### ISSUE THREAD

**Issue by fx505** [Mahdi-zarei/nekoray#110]
اول از همه خسته‌نباشی عزیز، امیدوارم راه رو همیشه ادامه بدی
فیک dns در نسخه‌های اولی که توسعه داده بودی و از کانفیگ
`dns.rules`
``` 
{
   "inbound": "tun-in",
  "server": "dns-fake"
}
```
استفاده میکردی، کاملا درست کار میکرد. ولی متاسفانه در نسخه‌های اخیر مشکل دارن!
**عملکرد نسخه‌ی فعلی:**
![image](https://github.com/user-attachments/assets/f2bb5ad7-cfdb-4ff9-bca8-e4a896f485cb)

**عملکرد صحیح:**
![image](https://github.com/user-attachments/assets/3eb07ec9-89df-42d1-a7d5-252521c9d127)

کانفیگ پیشنهادی:
```
{
 "inbound": "tun-in",
 "query_type": [
      "A",
      "AAAA"
  ],
  "server": "dns-fake"
}
```

**Comment by Mahdi-zarei** [comment]
متوجه نمیشم چرا مورد اول مشکل داره و دومی صحیح هست
و اینکه کانفیگ فعلی و پیشنهادی عملا یکی هست و هر دو بر اساس داکیومنت خود سینگ باکس هست، پیشنهاد میدم یک دور کانفیگ رو اکسپورت کنید و دلیل اشتباه بودنش رو ذکر کنید.

**Comment by Mahdi-zarei** [comment]
> تنها دلیل استفاده کردنم از Fakedns اینه که بخوام از dnsی که تو سرور ست کردم استفاده کنم. (من تو سرور dns گوگلی ست نکردم و نمیخوام هم استفاده کنم) dns گوگلی که در تست نشون میده از Remote Dns توی تنظیمات نکوری میاد.

وقتی از fakedns استفاده میکنید هنوز هم dns remote برای ریزالو استفاده میشه، فقط ip آی که به اپلیکیشن ها در جواب ریکوئستشون داده میشه یه آی پی پرایوت هست که سینگ باکس اون رو به آی پی اصلی مپ میکنه
در صورتی که نیاز به استفاده از از dns سرور دارین sniff رو باید توی سرور اعمال کنید و درخواست های dns رو به dns out بدید، فیک dns سمت کلاینت تغییری توی نحوه عملکرد سرور ایجاد نمیکنه.
