### ISSUE TITLE
BUG: Hotkeys do not work

### ISSUE THREAD

**Issue by EzSync** [Mahdi-zarei/nekoray#111]
Version: 4.1.2

I pressed Control+U, but nothing happened and the subscription was not updated.
Also, the Control+Shift+G group test doesn't work any more.

**Comment by M-Sadegh-M** [comment]
I don't know why,
but both of these features were removed in version 4.1.2.

**Comment by Mahdi-zarei** [comment]
They are not removed, they are relocated to the Group's context menu.
![Screenshot 2024-08-17 121817](https://github.com/user-attachments/assets/e5402d1d-bd55-4526-a55a-fce218390aa6)

**Comment by M-Sadegh-M** [comment]
> They are not removed, they are relocated to the Group's context menu.

It doesn't show up in Windows.

![image](https://github.com/user-attachments/assets/c5da230e-de7f-43de-b2f5-95113185dab4)

**Comment by Mahdi-zarei** [comment]
You need to right click the tabs, I also noted this in the release notes.

**Comment by M-Sadegh-M** [comment]
oooh, ok I find them.

I look for them in wrong place. Sorry

Thanks a lot

**Comment by M-Sadegh-M** [comment]
I'm using shortcuts key, but they're not working

**Comment by Mahdi-zarei** [comment]
I also noticed this. Will try to fix them.

**Comment by M-Sadegh-M** [comment]
> I also noticed this. Will try to fix them.

thanks bro

**Comment by Mahdi-zarei** [comment]
try 4.1.3

**Comment by M-Sadegh-M** [comment]
> try 4.1.3

It's worked. thanks
