### ISSUE TITLE
[FR] Please add SSH as a config type

### ISSUE THREAD

**Issue by Turbine8845** [Mahdi-zarei/nekoray#113]
## Description suggestions
If it is possible, please kindly consider adding SSH as a config type in `Server` > `New Profile` section of Nekoray.

![SSH as a config](https://github.com/user-attachments/assets/209a9d21-3027-470e-a1e0-a1201d12b08a)

## Necessity of recommendations
Clients like Husi and NekoBox for Android have long had the ability to connect to VPS servers using SSH. Since Sing-box supports SSH, I guess having the ability to utilize it in the desktop version of Nekoray can be a useful feature for users.

https://sing-box.sagernet.org/configuration/outbound/ssh/

![husi_ssh(1)](https://github.com/user-attachments/assets/49aaaaeb-cf94-43ce-b0d5-ff63774879e9)
![husi_ssh](https://github.com/user-attachments/assets/5e26c6a2-7b3a-4a21-aee3-05ab0497c5ce)

**Comment by SagePtr** [comment]
I checked SSH, it works in Nekoray if added as "Custom sing-box outbound", example:
```
{
    "type": "ssh",
    "server": "192.168.0.15",
    "server_port": 22,
    "user": "johndoe",
    "private_key": "-----BEGIN OPENSSH PRIVATE KEY-----\nKEY_HERE\n-----END OPENSSH PRIVATE KEY-----"
}
```
Would be nice to have in GUI as well.

**Comment by Mahdi-zarei** [comment]
Added in 4.1.4
