### ISSUE TITLE
اجرا نشدن در لینوکس

### ISSUE THREAD

**Issue by persian85** [Mahdi-zarei/nekoray#114]
اپ رو با تمام dependency های لازم روی لینوکس ابونتو ۲۲.۰.۴ نصب کردم ولی اجرا نمیشه! نه خطایی میده و نه اپی باز میشه! ولی با دانلود نسخه جنرال لینوکس و اجرای لانچر اپ باز میشه و بخوبی کار میکنه. چرا نمیتونم از نسخه deb استفاده کنم؟

**Comment by Mahdi-zarei** [comment]
یک دور باید از توی /opt/nekoray لانچر رو با sudo اجرا کنید.
بعد از اون میتونید بصورت نرمال ازش استفاده کنید.

**Comment by persian85** [comment]
> یک دور باید از توی /opt/nekoray لانچر رو با sudo اجرا کنید. بعد از اون میتونید بصورت نرمال ازش استفاده کنید.

ممنون از پاسختون. با استفاده از sudo اپ اجرا شد و بخوبی کار میکنه. ولی باز وقتی میخوام بصورت عادی اجراش کنم هیچ اتفاقی نمی افته (حالت gui  که سرچ میکنم اسم و آیکون برنامه رو میاره ولی وقتی روش کلیک مکینم هیچ اتفاقی نمی افته(. البته اگه از محیط ترمینال اجراش کنم بدون سودو باز میشه ولی وقتی پروفایل مورد نظرم رو میخوام استارت کنم خطای permission denied میده. ضمن اینکه در محیط ترمینال حتما باید مسیر اجرای لانچر رو هم بدم بهتر نبود در path هم تعریف میشد تا مثل بقیه اپها راحت اجرا بشه؟

**Comment by Mahdi-zarei** [comment]
یک سری تغییرات جدید داده شد، ممنون میشم تست کنید پکیج جدید رو

**Comment by persian85** [comment]
هنگام نصب نسخه جدید با این خطا روبرو میشه
Selecting previously unselected package nekoray.
(Reading database ... 302650 files and directories currently installed.)
Preparing to unpack Downloads/413.deb ...
Unpacking nekoray (4.1.3) ...
Setting up nekoray (4.1.3) ...
Failed to set capabilities on file `/use/local/nekoray/nekobox_core' (No such file or directory)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file

**Comment by Mahdi-zarei** [comment]
نسخه 4.1.4 رو امتحان کنید.

**Comment by persian85** [comment]
بدون خطا نصب شد ولی همچنان از قسمت لانچر که اپ رو سرچ میکنم وقتی روش کلیلک میکنم اجرا نمیشه و باید از طریق ترمینال از مسیر /opt/nekoray/launcher اجراش کنم. مورد دومی که داره برای دانلود asset ها شروع به دانلود میکنه حتی فایل هم دریافت میکنه ولی آخرش خطا میده چنین فایلی برای دانلود وجود نداره! 

یه سوال؟ تو تب core گزینه ntp تنظیم سرور زمان به چه کاری میاد برای این برنامه؟

**Comment by Mahdi-zarei** [comment]
برای اجراش بهتره اکانتتون رو sudoer کنید که بتونید بدون نیاز به auth از sudo استفاده کنید.
مورد دوم رو نمیدونم
یک سری سیستم ها که تایمشون دقیق نباشه میتونن از ntp استفاده کنن که مستقل از زمان برنامه بتونن به پروتکل هایی که به زمان حساس هستن وصل بشن.

**Comment by MHDLNX** [comment]
در اوبونتو ۲۴ . نه به صورت عادی باز میشه . نه از طریق لانچر

**Comment by Mahdi-zarei** [comment]
در حال حاضر پکیج deb خراب هست و پیشنهاد میدم از فایل آرشیو استفاده کنید.

**Comment by Mahdi-zarei** [comment]
try 4.2.2
