### ISSUE TITLE
BUG: دلیل وصل نشدن برخی از کانفیگ ها

### ISSUE THREAD

**Issue by nightday1243** [Mahdi-zarei/nekoray#115]
درود وقت بخیر
مشکلی از نرم افزار داره اینه بنده بعد از اپدیت 4.0.8 برام کانفیگ ها وصل نمی شن و مشکلشم اینه ستینگ هدر tcp بعد از نسخه 4.0.8 برداشته شده
ممنون میشم این بخش رو مجدد در نسخه های جدید برگردونید اینطوری مشکلات بقیه دوستان هم حل میشه
![2024-08-18 17_55_54-Edit](https://github.com/user-attachments/assets/8ca06ea6-ab54-4b70-9424-c8cf3f0f2ad6)

**Comment by Mahdi-zarei** [comment]
ورژن 4.1.3 رو تست کنید

**Comment by nightday1243** [comment]
درود وقت بخیر
بله حل شد خیلی ممنون
