### ISSUE TITLE
BUG: 路由设置代理规则会导致URL test失败

### ISSUE THREAD

**Issue by shamikon** [Mahdi-zarei/nekoray#116]
## 描述问题

预期行为：正常测试

实际行为：路由规则存在porxy时测试失败，删除这条规则只留下block和direct规则后URL test恢复正常

## 如何复现

![image](https://github.com/user-attachments/assets/d11c2d81-01c7-453f-a5f2-97e2c8c3bdde)
![image](https://github.com/user-attachments/assets/057dc547-f64f-4fbf-b310-bc16048e4c7e)

**Comment by zhegeshijiehuiyouai** [comment]
我也遇到了，我的版本是 4.1.2
