### ISSUE TITLE
Please add support for modern SSL versions.

### ISSUE THREAD

**Issue by To-Azamat** [Mahdi-zarei/nekoray#117]
Running Lubuntu 24 with OpenSSL 3.0.13
The program does not start as unable to find ssl 1.1

**Comment by Mahdi-zarei** [comment]
The said library is included within the package, you need to run the launcher and not the nekoray binray itself

**Comment by To-Azamat** [comment]
Sorry, my bad, used to run the binary. Launcher works just fine.

Can you help me troubleshoot a weird routing issue? I am trying to run a nekoray node as a VPN gateway for local network. Locally all is fine, but when I route traffic from the main router to the VPN gateway - it does not work. The most strange behavior is when I route DNS through VPN - traceroute shows it just loops from main router to VPN gateway and back.

I have the same config with nekoray running on Mac and it works flawlessly. What can I be missing with Ubuntu?

**Comment by Mahdi-zarei** [comment]
I have not dealt with such configurations much but, I guess the problem is caused by different settings on iptables in the sing-box's end, try strict route and see if it makes any changes. Besides, I wouldn't suggest using nekoray's Tun mode for making a VPN gateway, tproxy has much better performance for your case.

**Comment by To-Azamat** [comment]
Will try it and report here. 
As for tproxy performance is not an issue here. I am building kind of split tunnel, warping just a part of the traffic into vpn. As I have xui already deployed makes sense to use it.

**Comment by To-Azamat** [comment]
Did a fresh install on Lubuntu 24.
With Strict route enabled everything runs as expected. Thank you for the help!
