### ISSUE TITLE
BUG: Significant difference between the URL Test results in versions 4.1.2 and 4.0.10

### ISSUE THREAD

**Issue by Turbine8845** [Mahdi-zarei/nekoray#118]
## Describe the problem
As shown in the following screenshots, in version 4.1.2 the URL test gives a lower and more inaccurate ping for various configs compared to version 4.0.10. In fact the URL test in version 4.1.2 gives ping values that are too good to be true for my internet! In other words the URL test in version 4.1.2 shows a low ping for various configs that doesn't work at all!
### URL test in version 4.1.2:
![4 1 2 Ping](https://github.com/user-attachments/assets/829a75e0-8df5-4866-aa35-e986a2644271)
### Version 4.1.2 log:
```log
INFO[0000] router: updated default interface Wi-Fi, index 12
INFO[0000] sing-box started (0.11s)
INFO[0000] outbound/shadowsocks[g-415578-0]: outbound connection to www.google.com:80
Speedtest finished!
```
### URL test in version 4.0.10:
![4 0 10 Ping](https://github.com/user-attachments/assets/c8a275fe-fa2a-4742-8943-3feb2e9589d9)
### Version 4.0.10 log:
```log
INFO[0000] router: updated default interface Wi-Fi, index 12
INFO[0000] sing-box started (0.00s)
INFO[0000] outbound/shadowsocks[proxy]: outbound connection to www.google.com:80
INFO[0000] outbound/direct[direct]: outbound packet connection to 1.1.1.1:53
INFO[0000] dns: exchanged series-a2-me.varzesh360.co CNAME series-a2-me.varzesh360.co. 6 IN CNAME account-me.emofid.co.
INFO[0000] dns: exchanged series-a2-me.varzesh360.co CNAME account-me.emofid.co. 6 IN CNAME admin.c3.webramz.co.
INFO[0000] dns: exchanged series-a2-me.varzesh360.co CNAME admin.c3.webramz.co. 6 IN CNAME admin.c3.havij.co.
INFO[0000] dns: exchanged series-a2-me.varzesh360.co CNAME admin.c3.havij.co. 6 IN CNAME me-xz-nlb-1311-44dd36fde0c142ca.elb.me-south-1.amazonaws.com.
INFO[0000] dns: exchanged series-a2-me.varzesh360.co SOA elb.me-south-1.amazonaws.com. 6 IN SOA ns-687.awsdns-21.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 60
INFO[0000] dns: exchanged series-a2-me.varzesh360.co CNAME series-a2-me.varzesh360.co. 37 IN CNAME account-me.emofid.co.
INFO[0000] dns: exchanged series-a2-me.varzesh360.co CNAME account-me.emofid.co. 37 IN CNAME admin.c3.webramz.co.
INFO[0000] dns: exchanged series-a2-me.varzesh360.co CNAME admin.c3.webramz.co. 37 IN CNAME admin.c3.havij.co.
INFO[0000] dns: exchanged series-a2-me.varzesh360.co CNAME admin.c3.havij.co. 37 IN CNAME me-xz-nlb-1311-44dd36fde0c142ca.elb.me-south-1.amazonaws.com.
INFO[0000] dns: exchanged series-a2-me.varzesh360.co A me-xz-nlb-1311-44dd36fde0c142ca.elb.me-south-1.amazonaws.com. 37 IN A 16.24.57.2
Speedtest finished!
```

URL tests were preformed for the following config using http://www.google.com/generate_204:

`
{"dns":{"independent_cache":true,"rules":[{"domain":["series-a2-me.varzesh360.co"],"domain_keyword":[],"domain_regex":[],"domain_suffix":[],"rule_set":[],"server":"dns-direct"}],"servers":[{"address":"https://8.8.8.8/dns-query","address_resolver":"dns-local","detour":"proxy","strategy":"","tag":"dns-remote"},{"address":"local","address_resolver":"dns-local","detour":"direct","strategy":"","tag":"dns-direct"},{"address":"rcode://success","tag":"dns-block"},{"address":"local","detour":"direct","tag":"dns-local"}]},"inbounds":[{"domain_strategy":"","listen":"127.0.0.1","listen_port":2080,"sniff":true,"sniff_override_destination":false,"tag":"mixed-in","type":"mixed"}],"log":{"level":"info"},"outbounds":[{"domain_strategy":"","method":"chacha20-ietf-poly1305","password":"Bog0ELmMM9DSxDdQ","server":"series-a2-me.varzesh360.co","server_port":443,"tag":"proxy","type":"shadowsocks","udp_over_tcp":false},{"tag":"direct","type":"direct"},{"tag":"block","type":"block"},{"tag":"dns-out","type":"dns"}],"route":{"final":"proxy","rule_set":[],"rules":[{"outbound":"dns-out","protocol":"dns"}]}}
`
## Expected behavior:
The URL test in version 4.1.2 must show the accurate ping of the config.

## Actual behavior:
The URL test in version 4.1.2 gives lower and more inaccurate ping values for various configs compared to the URL test in version 4.0.10.

## How to reproduce
Preform a URL test for an arbitrary config in Nekoray version 4.1.2 and compare it the URL test results in version 4.0.10

**Comment by Mahdi-zarei** [comment]
The only difference in the methods between the 2 versions is that the newer version runs URLTest 2 times and reports the second one, so that it won't account for the initial connection setup times that is only done once when mux is enabled.
