### ISSUE TITLE
BUG: Weird "security": "reality" in GUI

### ISSUE THREAD

**Issue by SagePtr** [Mahdi-zarei/nekoray#119]
Version 4.1.3

## How to reproduce

1. Import proxy configured like:
```
vless://myUUID@MyServerIP:443?security=reality&sni=www.microsoft.com&alpn=h2&fp=chrome&pbk=MyPBK&sid=MySID&type=tcp&flow=xtls-rprx-vision&encryption=none
```
It has "security": "tls" in GUI configuration, and both "Reality Pbk" and "Reality SID" hidden from GUI (but working).
2. Check this proxy. It works without problems. Despite  "Reality Pbk" and "Reality SID" fields hidden.
3. Change "security" to "reality". Now "Reality Pbk" and "Reality SID" appear back with their filled in values.
4. If we click OK and start this proxy, it doesn't connect with this message:
```
INFO[0000] outbound/vless[g-1-0]: outbound connection to cp.cloudflare.com:80
[[VLESS]] ошибка теста: Get "http://cp.cloudflare.com/": initialize vision: vision: not a valid supported TLS connection: *net.TCPConn
Speedtest finished!
```
5. If we copy our non-working proxy and paste it back, it works again. And if we just switch "security" from "reality" to "tls" it works too.

**Comment by Mahdi-zarei** [comment]
Try 4.1.4

**Comment by SagePtr** [comment]
Looks fixed
