### ISSUE TITLE
Help Needed: fingerprint: chrome_pq (with reality)

### ISSUE THREAD

**Issue by SagePtr** [Mahdi-zarei/nekoray#120]
I want "chrome_pq" fingerprint to make uTLS mimic Kyber (on by default in few recent Chrome versions).
But if I set "fingerprint" to "chrome_pq", it doesn't work with error message:
```
[[VLESS] Test2] ошибка теста: Get "http://cp.cloudflare.com/": nil ecdhe_key
Speedtest finished!
```
Not sure how to get this ecdhe_key and pass it to uTLS. Tried to specify it in "Outbound custom config", but not sure where to put it, sing-box documentation has no info about ecdhe_key.
Any ideas?
The protocol I use is VLESS + Reality with flow = xtls-rprx-vision, works good with chrome/firefox/edge fingerprints at least (stops working when i switch to "chrome_pq" fingerprint).

**Comment by Mahdi-zarei** [comment]
I do not know if this problem is related to sing-box, from the code I could say that reality does not support these TLS methods, as the newer uTLS fingerprints differ from the old ones that only mimicked browser client hellos, the new ones mimic a more complicated TLS process related to Post Quantom encryption.

**Comment by SagePtr** [comment]
After some brainstorming, I figured out chrome_pq actually works with normal TLS (either normal or xtls-rprx-vision), but not working with Reality. I will investigate further and write if I figure out more useful info.

**Comment by SagePtr** [comment]
Tested this with original CLI Sing-box (both latest release and beta), and it seems to be Sing-box bug, not Nekoray.
https://github.com/SagerNet/sing-box/issues/2084
