### ISSUE TITLE
BUG: Win7 - failed to start profile

### ISSUE THREAD

**Issue by ig-man** [Mahdi-zarei/nekoray#121]
The new release v.4.1.3 does not start the url test and failed to start profile on Win7.
![nek](https://github.com/user-attachments/assets/9b42d0a5-3cd1-4ddd-a0b1-f234d1a8df1e)

**Comment by Mahdi-zarei** [comment]
It is caused by the change mades to the sing-box's win management methods. perhaps we need to disable power listener on windows 7 build...

**Comment by Mahdi-zarei** [comment]
Try 4.1.4

**Comment by ig-man** [comment]
Win7, it works fine. Thank you!
