### ISSUE TITLE
BUG: WIN 10/version 4.1.3 - application crashed when trying to URL Test Group

### ISSUE THREAD

**Issue by ironlag85** [Mahdi-zarei/nekoray#122]
![report](https://github.com/user-attachments/assets/48af16b7-6c40-4cbc-963e-e1af463e2810)

**Comment by Mahdi-zarei** [comment]
I cannot trace the root cause by the given information, please provide a way to reproduce this crash so that i can investigate it.

**Comment by ironlag85** [comment]
When trying to hold Url Lest group (https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/speed.txt) occurs application crashed
![report2](https://github.com/user-attachments/assets/fbde14be-e4c8-4a7f-bdd9-7217170f0f37)

**Comment by Mahdi-zarei** [comment]
Will be fixed in the next release

**Comment by M450ud** [comment]
I had this problem with Hy1 configs.

**Comment by ndsphonemy** [comment]
> I had this problem with Hy1 configs.

Same error when in subscription hysteria1 config, when hysteria2 error not occured.

**Comment by Mahdi-zarei** [comment]
Fixed in 4.1.4
