### ISSUE TITLE
BUG: Tun auto redirect option 

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#124]
No idea what does it do... 
Tried to test but it keeps getting disabled after restarting tun or restarting nekoray or sometimes nekoray crash.

**Comment by Mahdi-zarei** [comment]
Fixed in 4.1.4
Also auto redirect is the one from sing-box new Tun capabilities, it configures your iptables to redirect connections to sing-box, I believe this can yield a better performance than using Tun only.

**Comment by papampi** [comment]
Since I bugged you a lot today ... 
Is it normal that when enable this option local adguard will be bypassed and seems like nekoray will do the resolve.

When disabled and use dig, 2nd request query time will be 0 (cache hit):
```
~$ dig @192.168.1.10 github.io

; <<>> DiG 9.18.28-0ubuntu0.24.04.1-Ubuntu <<>> @192.168.1.10 github.io
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25336
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;github.io.                     IN      A

;; ANSWER SECTION:
github.io.              3600    IN      A       185.199.111.153
github.io.              3600    IN      A       185.199.108.153
github.io.              3600    IN      A       185.199.110.153
github.io.              3600    IN      A       185.199.109.153

;; Query time: 371 msec
;; SERVER: 192.168.1.10#53(192.168.1.10) (UDP)
;; WHEN: Tue Sep 24 16:18:13 +0330 2024
;; MSG SIZE  rcvd: 102

:~$ dig @192.168.1.10 github.io

; <<>> DiG 9.18.28-0ubuntu0.24.04.1-Ubuntu <<>> @192.168.1.10 github.io
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29577
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;github.io.                     IN      A

;; ANSWER SECTION:
github.io.              3599    IN      A       185.199.111.153
github.io.              3599    IN      A       185.199.108.153
github.io.              3599    IN      A       185.199.110.153
github.io.              3599    IN      A       185.199.109.153

;; Query time: 0 msec
;; SERVER: 192.168.1.10#53(192.168.1.10) (UDP)
;; WHEN: Tue Sep 24 16:18:14 +0330 2024
;; MSG SIZE  rcvd: 102

```

But when enabled adguard won't show any requests and resolves not using the adguard cache and repeating dig will not showing  query times of 0 like above

**Comment by Mahdi-zarei** [comment]
I do not exactly know, but auto redirect configures the routing tables so that tcp connections will be redirected to you, so I believe it should not intercept UDP dns requests, also, many DNS clients do cache responses based on the TTL of the response, so it is not a good gauge to check the latency to check who is resolving the query.

**Comment by papampi** [comment]
Thank you so much
Will try to look it up and dig more 
If found out how it works will post the update here.
