### ISSUE TITLE
BUG: The URL Test Group functionality does not work when a Front/Landing proxy is set

### ISSUE THREAD

**Issue by Turbine8845** [Mahdi-zarei/nekoray#126]
## Describe the problem
The URL Test Group functionality fails when a Front/Landing proxy is set for a group.
## Expected behavior:
The bulk URL test should not fail or generate an error message when a Front/Landing proxy is used.
## Actual behavior:
Preforming a Group URL test leads to an error in the log section and fails when a Front/Landing proxy is set in the `Edit Selected Group` Window. Surprisingly, the URL test can still be successfully preformed manually and one by one for each config in the Group that is using a Front/Landing proxy!
## How to reproduce
Create a subscription group containing several configs. Then select a Front/Landing proxy for the created group. Click on the URL Test Group. The URL test fails and an error message appears in the log section.

## log
```log
INFO[0000] router: updated default interface Wi-Fi, index 12
grpc-status error code: 2 , error msg: start service: outbound tag g-0-1 duplicated
[Error] gRPC: QNetworkReply::NetworkError code: 301
Speedtest finished!
```

**Comment by Mahdi-zarei** [comment]
Fixed in 4.1.4
