### ISSUE TITLE
BUG: minor GUI Bug

### ISSUE THREAD

**Issue by M-Sadegh-M** [Mahdi-zarei/nekoray#128]
Hello and thank you for your efforts.

![image](https://github.com/user-attachments/assets/0b739fef-c7ff-4dc5-a1a7-d4374ab6efc1)
![image](https://github.com/user-attachments/assets/9aa4576b-b785-4e57-8fc6-805805f29505)

**Comment by Mahdi-zarei** [comment]
Fixed in 4.1.4

**Comment by M-Sadegh-M** [comment]
> Fixed in 4.1.4


thanks a lot.
