### ISSUE TITLE
BUG: 中文翻译问题

### ISSUE THREAD

**Issue by cnm4399** [Mahdi-zarei/nekoray#129]
## 描述问题
这几个地方，没有翻译成中文？我已经标注，请修复。

![001](https://github.com/user-attachments/assets/ff7e3389-c255-4d01-ab5f-0c70b6703ed2)

![002](https://github.com/user-attachments/assets/bd8793c9-ba81-4ed0-ae8b-1c0cdd96c60b)
![003](https://github.com/user-attachments/assets/4c9f839f-2a64-4b56-82f3-1432453ebbc6)
![004](https://github.com/user-attachments/assets/8e9df03d-3d8e-4882-b168-e807f3c915b7)
![005](https://github.com/user-attachments/assets/cea2b762-184a-44a4-a4bb-f27cd9d7d95f)
![006](https://github.com/user-attachments/assets/d37aa018-4478-4f82-8ea4-8017c0ade0bd)
![007](https://github.com/user-attachments/assets/7fa6135b-dea5-4472-aad8-12876fd5341e)

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by cnm4399** [comment]
![116](https://github.com/user-attachments/assets/be9a5042-5125-4b53-9fa7-0b6eafd9a7ff)

**Comment by Mahdi-zarei** [comment]
This is an open source project and everyone help in developing it. I can't single handedly update the translations, if you are interested, please open a PR and improve the Chinese translations.
