### ISSUE TITLE
BUG: App crash if use old tun mode syntaxt

### ISSUE THREAD

**Issue by AkramiPro** [Mahdi-zarei/nekoray#132]
**you must change this:**
```
"inet4_address": "172.18.0.1/30",
"inet6_address": "fdfe:dcba:9876::1/126",
```
**to this:**
```
"address": [
    "172.18.0.1/30",
    "fdfe:dcba:9876::1/126"
]
```
**otherwise app crash**
see: https://sing-box.sagernet.org/configuration/inbound/tun/#address

**Comment by Mahdi-zarei** [comment]
What version are you using?

**Comment by AkramiPro** [comment]
sorry i forget to mention that: 4.1.3-20204-08-28

also i tested with this and get the same result as your client. the crash is for core upgrade

```./sing-box run -c sonfig.json```

**Comment by AkramiPro** [comment]
you can reproduce the problem with this:

`"inet4_address": "172.19.0.1/30",`

the default is `172.18.0.1/30` in `address` section and i think they get conflict if use `inet4_address` in different subnet like above

**Comment by Mahdi-zarei** [comment]
I don't understand, where am i supposed to enter the field you have mentioned?

**Comment by AkramiPro** [comment]
create new custom sing-box config:

```
"inbounds": [
        {
            "inet4_address": "172.19.0.1/30",
            "inet6_address": "fdfe:dcba:9876::1/126",
            "auto_route": true,
            "domain_strategy": "ipv4_only",
            "interface_name": "sing-box",
            "mtu": 9000,
            "sniff": true,
            "sniff_override_destination": false,
            "stack": "mixed",
            "strict_route": true,
            "tag": "tun-in",
            "type": "tun"
        },
}
```

**Comment by Mahdi-zarei** [comment]
Do you mean that I should look inside custom configs and update them according to the new sing-box TUN configuration syntax?

**Comment by AkramiPro** [comment]
no. my point is your are using old syntaxt in the client in some where beacuse i can use tun mode in custom config but i can not use default client tun mode
i show the problem in this video:

https://github.com/user-attachments/assets/487d17fe-7f71-4dfa-9124-21e9ddce6b02

**Comment by Mahdi-zarei** [comment]
I don't know about the crash, but your environment has serious problems, as setting up a profile should never take this long. Also the format of the addresses is correct, instead of testing nekoray like a blackbox you could simply turn on the TUN mode and use the `export sing-box config` option to see what configuration is being generated. I also use the exact same version of the app and have used Tun mode on both windows and linux, and I have not encountered the problem you are facing.
