### ISSUE TITLE
BUG: Logical Routes are not importing

### ISSUE THREAD

**Issue by EbadiDev** [Mahdi-zarei/nekoray#135]
VERSION : 4.1.4
There is a problem when trying to import a route with logical fields in the routes configuration: [Logical Fields in Routes](https://sing-box.sagernet.org/configuration/route/rule/#logical-fields).

The original configuration:
```json
[
    {
        "type": "logical",
        "mode": "and",
        "rules": [
            {
                "process_name": [
                    "cs2.exe",
                    "dota2.exe",
                    "stremio.exe"
                ]
            },
            {
                "network": [
                    "udp"
                ]
            }
        ],
        "outbound": "direct",
        "invert": false
    }
]
```
![{444B849D-69CD-494A-AFB5-60C3569E90D2}](https://github.com/user-attachments/assets/3f3d89d3-fa88-456e-afab-b3c17c527d7c)

Is imported as:
```json
{
    "outbound": "direct"
}
```
![{B221B7E1-2EAB-4B8D-A5D8-3153D3B1C7A4}](https://github.com/user-attachments/assets/6be13ead-2f49-41c3-9e62-cf6fe8178492)

**Comment by Mahdi-zarei** [comment]
Logical rules are not supported, either use the normal rules or use custom configs.
