### ISSUE TITLE
Incorrect parsing

### ISSUE THREAD

**Issue by Sue1133** [Mahdi-zarei/nekoray#136]
I have a subscription that has a trojan protocol, which I update constantly. Starting with version 4.1.3, nekoray began to parse the config incorrectly, namely the "Security" field. It leaves it empty, although I use ws + tls. After each subscription update, I have to manually change everything to tls. This bug is also on version 4.1.4, but on 4.1.2 everything is fine.

**Comment by Sue1133** [comment]
I looked at the raw text that the subscription link sends and realized that most likely this is because the "Security" type is not specified there and apparently in the old version (4.1.2) it was automatically specified as tls.

**Comment by Mahdi-zarei** [comment]
This can be improved

**Comment by Sue1133** [comment]
Thank you
