### ISSUE TITLE
[Feature Request] Automatically removes duplicates when updating subscriptions

### ISSUE THREAD

**Issue by tglsf** [Mahdi-zarei/nekoray#137]
If your subscription contains a large number of duplicate configurations, then you will need to manually remove them after each subscription update.
Therefore I suggest adding the following feature: Automatically removes duplicates when updating subscriptions.
Thanks.

**Comment by Mahdi-zarei** [comment]
Optimizing Nekoray for large number of configs is not the main goal of this project, there have been improvements made for this, but the mainstream usage for Nekoray should be too manage your subscriptions and system settings, not managing thousands of them.
