### ISSUE TITLE
[Feature Request] Adjusting the UI layout to make repetitive operations more convenient

### ISSUE THREAD

**Issue by tglsf** [Mahdi-zarei/nekoray#138]
Currently, there are a lot of operations that need to be performed via context menus, such as updating subscriptions, deleting duplicate items, etc. This can cause some inconvenience and confuse newcomers.
Therefore, I would suggest to add functions that are very frequently used in general to the buttons above. For example, start, stop, update subscription, etc.

**Comment by Mahdi-zarei** [comment]
This will make the top bar of the app very crowded and this is not how it should be, the top bar should be as simple and concise as possible.
