### ISSUE TITLE
Microsoft Windows Defender Trojan Detection for updater.exe

### ISSUE THREAD

**Issue by AkramiPro** [Mahdi-zarei/nekoray#139]
current version: `4.1.3`
current WD version: `Microsoft Defender Antivirus - KB2267602 (Version 1.417.548.0) - Current Channel (Broad)`

I tried to update to `4.1.4`, but after clicking `Yes` in `Restart to install` dialog, I got a WD alarm for the `updater.exe` file.

![image](https://github.com/user-attachments/assets/ce1a72d3-0f7f-484e-b370-b0b3038f847e)

is this false positive?

**Comment by Mahdi-zarei** [comment]
Decide by yourself, that is one of the points of open source code
https://github.com/Mahdi-zarei/nekoray/tree/main/go/cmd/updater
