### ISSUE TITLE
support sing-box new routing system

### ISSUE THREAD

**Issue by AkramiPro** [Mahdi-zarei/nekoray#14]
I just want to be sure that your fork is support new sing-box routing rules? 
for example, the `GeoIP` and `Geosite` are deprecated and we need to use new `rule_set` option.

you can see sing-box doc migration section for full description about these changes.
https://sing-box.sagernet.org/migration/#migrate-cache-file-from-clash-api-to-independent-options

## Old Routing
```
{
  "route": {
    "rules": [
      {
        "geoip": "private",
        "outbound": "direct"
      },
      {
        "geoip": "cn",
        "outbound": "direct"
      },
      {
        "source_geoip": "cn",
        "outbound": "block"
      }
    ],
    "geoip": {
      "download_detour": "proxy"
    }
  }
}
```

## New Rotuing (v1.8+)
```
{
  "route": {
    "rules": [
      {
        "ip_is_private": true,
        "outbound": "direct"
      },
      {
        "rule_set": "geoip-cn",
        "outbound": "direct"
      },
      {
        "rule_set": "geoip-us",
        "rule_set_ipcidr_match_source": true,
        "outbound": "block"
      }
    ],
    "rule_set": [
      {
        "tag": "geoip-cn",
        "type": "remote",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs",
        "download_detour": "proxy"
      },
      {
        "tag": "geoip-us",
        "type": "remote",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-us.srs",
        "download_detour": "proxy"
      }
    ]
  },
  "experimental": {
    "cache_file": {
      "enabled": true // required to save Rule Set cache
    }
  }
}

```

**Comment by AkramiPro** [comment]
just for clarification i use `Custom Config Settings` for set routing settings and in my tests it is not support new sing-box routing syntax. 

![image](https://github.com/Mahdi-zarei/nekoray/assets/54323929/ec3c7219-83f5-42e1-83f3-6b6db003b2fa)

![image](https://github.com/Mahdi-zarei/nekoray/assets/54323929/422ad823-fdeb-4851-9e31-0ae3414de088)

**Comment by AkramiPro** [comment]
you test rules with tamin.ir domain, by default you shoud get 403 error so you can set rule to bypass IR sites but in new syntax it is not applied. 
for to be sure that my rules are correct i tested with sing-box cli version and its working.

**Comment by Mahdi-zarei** [comment]
The sections related to routing need to be fully rewritten, this might take some time.
