### ISSUE TITLE
BUG:  پاک شدن سرور منتخب- نتایج تست و ترافیک استفاده شده 

### ISSUE THREAD

**Issue by persian85** [Mahdi-zarei/nekoray#142]
در نسخه ویندوز و لینوکس بعد از زمان کوتاهی حدودا ۱ ساعت کمتر یا بیشتر مقادیری که در ستون test result - Traffic و همچنین سروری که برای اتصال انتخاب شده پاک میشن البته ارتباط همچنان برقرار هست. حتی توی قسمت program->active serverهم نشون نمیده با کدوم پروفایل متصل هست و باید از نو url test group اجرا بشه. 

مورد بعد اینکه اگر امکان داره در هنگام پروسه url test group بصورت لحظه ای نتایج رو نشون بده چون اگه تعداد زیادی پروفایل در یک گروه  وجود داشته باشه باید کلی صبر کرد تا نتایج بررسی رو دید و مناسب ترینش رو انتخاب کرد. ولی اگه لحظه ای نتایج رو نشون بده شاید قبل از نیاز به اتمام پروسه بررسی کاربر بخواد یه پروفایل رو برای اتصال انتخاب کنه

![Screenshot 2024-09-07 124836](https://github.com/user-attachments/assets/0a819a5a-fcec-46c6-b4e9-d3cd328dfeee)

**Comment by Mahdi-zarei** [comment]
مورد اول احتمال زیاد بخاطر automatic update هست و باگ محسوب نمیشه در این صورت.

در لحظه امکان پیاده سازی مورد دوم نیست، پیشنهادم اینه در صورتی که پهنای باندتون کشش داره concurrency رو ببرید بالا.
