### ISSUE TITLE
امکان اضافه کردن سایت و ای پی جدید برای بای پس کردن سایت های ایرانی

### ISSUE THREAD

**Issue by KingShah1998** [Mahdi-zarei/nekoray#144]
## Description suggestions
باسلام و احترام
اگه امکانش هست یه تغییراتی ایجاد کنید که بتونیم سایت و ای پی مورد نظرمون رو برای بای پس کردن اضافه کنیم. 
و همینطور اگه قابلیتی اینجاد کنید که برای پروکسی یا تون مد بتونیم یه سری برنامه ها رو اضافه کنیم به برنامه که بای پس بشن عالی میشه.
باتشکر

**Comment by Mahdi-zarei** [comment]
بخش routing settings دقیقا همین کارو انجام میده، هم میتونید rule های خودتون رو داشته باشید، هم پروفایل آماده هست که باهاش آی پی و دامنه های ایران رو میشه مستقیم زد.

**Comment by KingShah1998** [comment]
متاسفانه طوری طراحی شده که فقط میشه یه روت پروفایل انتخاب کرد و نمیشه اون پروفایلی که آماده هست برای ایران رو ادیت کرد و سایت و یا ای پی جدیدی بهش اضافه کرد. اگه خودمون هم روت پروفایل اضافه کنیم باید همه سایت ها و ای پی هایی که داخل روت پروفایل ایران هست رو دستی دوباره وارد کنیم و سایت خودمون رو هم بهش اضافه کنیم. اگه جز این راهی داره ممنون میشم راهنمایی کنید

**Comment by KingShah1998** [comment]
فایل های 
category-ir_SITE , ir_IP
رو نمیشه ادیت کرد و سایت و ای پی جدیدی که میخوایم بای پس بشه رو بهش اضافه کرد. 
با اضافه کردن روت جدید هم فقط یه پروفایل جدید ایجاد میشه با همون روتی که بهش اضافه کردیم و مشکلمون رو حل نمیکنه.

**Comment by Mahdi-zarei** [comment]
اگر نیاز به rule set های کاستوم دارید باید geoip و geosite کاستوم رو از بخش asset دانلود کنید و کتگوری هایی که داخلشون هستن رو میتونید اون موقع توی ساخت روت پروفایل استفاده کنید، در مورد یه روت پروفایل هم منظورتون رو متوجه نمیشم، توی هر پروفایل میشه تعداد دلخواه rule داشت و عملا میشه همه حالات رو پوشش داد، چرا چند تا روت پروفایل نیاز هست؟

**Comment by KingShah1998** [comment]
وقتی نمیشه روت پروفایل ایران رو ویرایش کرد و بهش سایت و ای پی جدید اضافه کرد مجبوریم روت پروفایل جدید بسازیم برای اضافه کردن سایت و ای پی جدیدمون، اما فقط یه روت پروفایل رو میشه هنگام کانکت شدن انتخاب کرد چند تا نمیشه. اونی هم که دستی میسازیم فقط یه سایت یا ای پی رو بهش اضافه کردیم مابقی سایت ها و ای پی هایی که روی روت پروفایل ایران بای پس میشدن رو باید دستی دونه دونه اضافه کرد. 
توی هر پروفایل میشه تعداد زیادی رول ساخت درسته ولی همه رو باید دونه دونه ساخت میخواستم ببینم راهی هست که بشه به همین روت پروفایل ایران که موجود هست سایت و ای پی جدید اضافه کنیم ؟
نمیدونم درست تونستم توضیح بدم یا نه ...
متاسفانه اونقدر سر در نمیارم که با  geoip و geosite کاستوم بتونم روت پروفایل جدید بزنمو

**Comment by Mahdi-zarei** [comment]
پروفایل ایران کلا 3 تا rule داره که خیلی راحت میتونید خودتون هم داخل پروفایل جدید بزاریدشون و بعد rule های مدنظر رو اضافه کنید. در لحظه امکان ادیت پروفایل ایران نیست و این 3 تا پروفایل پیش فرض هستن و قرار نیست ادیت بشن. امکان اضافه کردن دامین و آی پی به فایل های srs نیست و در صورتی که به srs های کاستوم نیاز دارید باید خودتون دانلود کنید و توی بخش config/rule_set بزاریدشون.
در آینده امکان کلون کردن روت پروفایل رو اضافه میکنم که یه سری کار ها راحت تر بشن.

**Comment by KingShah1998** [comment]
میخواستم همینکار رو انجام بدم دقیقا کپی شون کنم ولی موقع ساخت رول جدید تو پروفایل جدید برا سه تا رول ایران هر کدوم یه چیزی کم و کسری داشت و مثل اونی که داخل رول ایران بود نمیشد واسه همین بیخیال شدم.
