### ISSUE TITLE
wireguard Noise 

### ISSUE THREAD

**Issue by misagh72** [Mahdi-zarei/nekoray#147]
please add Noise to wireguard

**Comment by misagh72** [comment]
you can use this core for wireguard Noise 
https://github.com/kyochikuto/sing-box-plus/commit/14990223b8b604e35aed848cc2e036292cfdcc01

**Comment by Mahdi-zarei** [comment]
This is a big change, and there needs to be a strong reason for it to be made, I have tested oblivion a couple times and on different ISPs and I was not able to connect. If the Noise feature only works on few ISPs then it is not a reliable method to use. There are many methods both old and new that if are used properly can easily bypass the Wall, so temporary and weak methods like noise are of no value here I believe.
