### ISSUE TITLE
BUG: Tun Mode seriously broken

### ISSUE THREAD

**Issue by midncircus** [Mahdi-zarei/nekoray#149]
Tun Mode is broken both in 4.1.4 and 4.1.5. Sites either don't connect at all or takes 20+ seconds to open.

I also noticed If specific site would open then it seems to navigate fine (looks like some initial connect problem, don't know much about that).

The last working version 4.1.3

Windows 10

**Comment by Mahdi-zarei** [comment]
I believe this is a problem from sing-box's end, as Tun interface is entirely managed by it and the configuration passed is not faulty. I suggest you try to set your remote dns to tls://8.8.8.8 and see if this solves the problem, and please report if this helps. Sing-box has solved some problems related to sniff which will most likely most of these problems.

**Comment by midncircus** [comment]
Nope, setting tls://8.8.8.8 or any other DNS won't change a thing.

sing-box means nekobox_core.exe, right? I tried running 4.1.5 with sing-box nekobox_core.exe from 4.1.3 and it didn't work. Then I tried 4.1.3 with nekobox_core.exe from 4.1.5 and it did work. Does it mean the problem is not with sing-box?

**Comment by Mahdi-zarei** [comment]
By it worked do you mean that the problem with Tun got resolved, or it simply started working?

**Comment by midncircus** [comment]
It works only with 4.1.3 (or lower). Even it does even with nekobox_core.exe copied from newer versions.

Actually I just noticed something interesting. When I first clicked Tun Mode in 4.1.5, Windows asked me to add a firewall rule for nekobox_core (not just nekoray which it did long time ago). I believe it also silently added sing-tun firewall rule. 4.1.3 never did this. So it looked like this:

![Screenshot (81)](https://github.com/user-attachments/assets/cad4b708-b47c-4e26-8f1d-b677902d2058)

So I enabled it only for Private profile which always worked for every other program. Now I tried to enable it also for Public profile. Nothing changed. Then I set DNS to tls://8.8.8.8 and it worked! Hope it makes sence.

Being short: 4.1.5 asks for new Firewall rule nekobox_core. You have to enable it for both Private and Public. Then set tls://8.8.8.8. And only then it works.

**Comment by Mahdi-zarei** [comment]
could you please give me the following information?
1: enable tun mode on 4.1.3 then export sing-box config and send the inbound, dns and route sections.
2: do the same for 4.1.5 and send it here so I can see if there is any changes that might have caused it.
Also try something else, set direct dns to `underlying://0.0.0.0` and see if this fixes the problem.

**Comment by midncircus** [comment]
If I set underlying://0.0.0.0 and set default DNS server as direct, then yes, works perfectly!

"export sing-box config and send the inbound, dns and route sections"

Not sure where would I find this?

**Comment by Mahdi-zarei** [comment]
I really don't suggest to set the default dns server as direct, it will try to resolve domains using your own dns and without passing it through the tunnel.


> Not sure where would I find this?

right click on a config and choose share -> export sing-box config
it will give you a JSON that is used to bootstrap the sing-box.

**Comment by midncircus** [comment]
OK I did it and there is one discrepancy.

4.1.3 reads "stack":"gvisor"
4.1.5 reads "stack":""

Just in case, I never changed the stack manually. Out of curiosity I opened Tun Settings and noticed the order and casing are different between 4.1.3 and 4.1.5. Aesthetically I don't care but may be this info will help.

![1](https://github.com/user-attachments/assets/3a65d187-e22d-46aa-90ef-036d93262ae1)
![2](https://github.com/user-attachments/assets/449d87ab-a43c-4934-b30a-6db3a604d2b0)

By the way, not only underlying://0.0.0.0 works but also 223.5.5.5 and 119.29.29.29. localhost sucks.

**Comment by Mahdi-zarei** [comment]
I see
I also presume `local` may work too. I will fix the direct dns issue. Also the problem of stack being empty will be fixed too.

**Comment by Mahdi-zarei** [comment]
Try changing the Tun stack to gVisor and see if it helps.

**Comment by midncircus** [comment]
No change.

**Comment by Mahdi-zarei** [comment]
try [4.2.0-beta.1](https://github.com/Mahdi-zarei/nekoray/releases/tag/4.2.0-beta.1) with a clean install
