### ISSUE TITLE
Add support to access other configs as outbound for use in routing rules

### ISSUE THREAD

**Issue by AkramiPro** [Mahdi-zarei/nekoray#15]
## Description suggestions
i have 2 config `vmess-de` and `trojan-us`
in short i want to access `trojan-us` as outbound in `vmess-de` to use in routing rules.
for example i want to route all traffic to `vmess-de` and only route `us-domain.com` to `trojan-us`.

in  `vmess-de`  i added this rule to `Custom Config Settings`:
```
 "route": {
        "auto_detect_interface": true,
        "rules": [
            {
                "domain_suffix": [
                    "us-domain.com"
                ],
                "outbound": "trojan-us"
            }
        ]
    }
```
but it is not working because `trojan-us` is not included in  `vmess-de` as outbound.
i think you can check all rules before run sing-box and include necessary outbounds that user use in rules.

**Comment by Mahdi-zarei** [comment]
You can do this manually using custom config, in the ( most likely distant) future I will try to add functionalities to allow creating advanced routing using the GUI, but for now it's better that you use the custom config feature.
