### ISSUE TITLE
BUG: قطع وصل شدن کانکشن tun mode 

### ISSUE THREAD

**Issue by nightday1243** [Mahdi-zarei/nekoray#150]
درود وقت بخیر
ببخشید داخل نسخه 4.1.4 و 4.1.5 تون مود مشکل داره ممنون میشم یه بررسی بکنید کانکشن برقرار نمیشه یا بشه هم قطع وصلی داره

**Comment by Mahdi-zarei** [comment]
درود
دی ان اس ریموت رو tls://8.8.8.8 ست کنید و ببینید مشکل برطرف میشه یا نه. مشکل از سمت سینگ باکس هست و منتظر ریلیز هستم تا آپدیت کنم هسته رو.

**Comment by nightday1243** [comment]
متاسفانه خیر حل نشد
بازم ممنون بابت زحماتی که میکشید خسته نباشید
صبر میکنیم پس هسته اپدیت بشه

**Comment by nightday1243** [comment]
سلام وقت بخیر 
متاسفانه با اپدیت هسته هم اوکی نشد

**Comment by Mahdi-zarei** [comment]
چند مورد رو تست کنید
یکی اینکه dns ریموت رو به tls://8.8.8.8 تغییر بدید و همچنین dns دایرکت رو به localhost تغییر بدید.
همچنین اگر از tun mode استفاده میکنید استک های مختلف رو تست کنید.

**Comment by nightday1243** [comment]
سلام وقت بخیر متاسفانه همچنان مشکل هست با ست کردن ریموت tls://8.8.8.8 روی ورژن 4.1.4 اوکی میشه تون مود چون روی اونم اشکال داشت ولی نسخه 4.1.5 و 4.1.6 نه متاسفانه

**Comment by Mahdi-zarei** [comment]
استک های مختلف رو هم تست کردید؟

**Comment by nightday1243** [comment]
بله روی 4 تا ورژن از 4.1.3 تا 4.1.6 تست کردم با ریموت و عوض کردن استک مشکل تون مود 4.1.4 حل میشه ولی روی 4.1.5 و 4.1.6 نه متاسفانه البته شاید ویندوز من پک درایوری رو باید داشته باشه که نداره

**Comment by Mahdi-zarei** [comment]
منطقی نیست که روی 4.1.5 حل نشه و روی 4.1.4 بشه، توی ورژن 4.1.5 تنها چیزی که عوض شده مربوط به tun اسم استک ها توی gui هست، منطقا باید بتونید با امتحان استک های مختلف 4.1.5 رو هم اوکی کنید اگر 4.1.4 اوکی شده.

**Comment by Mahdi-zarei** [comment]
استک gVisor رو بنظرم تست کنید، این استک دیفالت بوده که عوض شده و حدس میزنم با استفاده ازش مشکلتون رفع بشه.

**Comment by nightday1243** [comment]
رو این گذاشتم اولیش جواب نداد بعد الان mtu رو گذاشتم 1500 فیکس شد خیلی ممنون
اگه باز از دوستان مشکلی داشت اینو میخواید به عنوان نوت پین کنید

**Comment by Mahdi-zarei** [comment]
جالبه. نوت نیاز نیست، دیفالت رو از 9000 میکنم 1500.

**Comment by nightday1243** [comment]
جسارتا یه سوال 10.10.34.35:443 این dns برای خود نکوری چون کانفیگ روی پیسی مدام روی همچین ایپی که انگار dns تایم اوت میخوره و زمانی هم که روی resolve select domain میزنم این عدد به جای ایپی میاد در صورتی که کانفیگ روی گوشی موردی نداره ممنون میشم اینو یه چک بکنید اگه از سمت نرم افزار

**Comment by Mahdi-zarei** [comment]
این آی پی هست که اینترنت ایران در صورتی که دامنه فیلتر باشه پس میده و به جایی هم وصل نمیشه کلا و از سمت اپ نیست این مورد
