### ISSUE TITLE
مخفی کردن بخش ادرس

### ISSUE THREAD

**Issue by nightday1243** [Mahdi-zarei/nekoray#151]
درود خسته نباشید
ببخشید میخواستم اگه میشه داخل گزینه ها یه بخشی اضافه کنید که با فعال کردنش چیزایی که داخلی بخش ادرس هست دامنه و پورت پنهان یا شطرنجی بشه

**Comment by Mahdi-zarei** [comment]
درود
متاسفانه امکان نیست در حال حاضر.
