### ISSUE TITLE
TUN模式错误

### ISSUE THREAD

**Issue by sjjiqtkgg** [Mahdi-zarei/nekoray#152]
![image](https://github.com/user-attachments/assets/61f0940f-8859-4fbe-bf66-3052d8b9b563)
![image](https://github.com/user-attachments/assets/1c62747f-f2d6-4f12-9612-e2c0b3f1aab5)
4.15开启TUN模式如图
给作者一点建议，您更新的版本我一直在用，但是从4.0.1后多多少少都 有点小问题，可能就是还有使用习惯的问题（一些功能），我还是用回原来的4.0.1版本。个人觉得4.0.1版本是最稳定的。我相信大多数使用这种软件就是直要能上网，支持协议多，最重要是稳定就行。除非有新的技术。没有必要过多的更新。当然以上只是个人建议。

**Comment by Mahdi-zarei** [comment]
I agree with your concerns, but there are usually some tweaks needed in the new versions, like for my own use case, I changed local dns to `local` and used a non udp remote dns and it is working well so far, whether i use Tun mode or proxy mode. I will try to fix these minor issues.

**Comment by sjjiqtkgg** [comment]
4.16一样问题。没有网络。虚拟网卡无网

**Comment by Mahdi-zarei** [comment]
Can you share more of your configuration? I use the same app and I have not had this much problem with it.

**Comment by midncircus** [comment]
Isn't it related to recently discussed problem with DNS address without a protocol? 8.8.8.8 is the default.

**Comment by Mahdi-zarei** [comment]
I'm not sure but there seems to be some problems with sing-box's udp dns seems to fail a lot compared to the older versions. But the problem mentioned here does not seems to be from the dns, but from a wrong configuration somewhere.

**Comment by sjjiqtkgg** [comment]
> 您能分享更多配置吗？我使用相同的应用程序，没有遇到这么多问题。
 要那方面的配置？日志记录吗？还是设置？我是小白我是不太懂。谷歌翻译可能也有差译

**Comment by Mahdi-zarei** [comment]
Tun settings
From routing settings the first page and the second one (DNS)
and also the Core settings from basic settings
and if you are using an old OS like windows 7 please note that as well

**Comment by sjjiqtkgg** [comment]
> Tun 设置 从路由设置中的第一页和第二页（DNS） 以及基本设置中的核心设置 ，如果你使用的是 Windows 7 等旧操作系统，请注意
![image](https://github.com/user-attachments/assets/c3819794-a65e-44d9-943c-4b3bf3ff9051)
![image](https://github.com/user-attachments/assets/2e47f2a0-c5d9-4c0c-b668-ccb3133ecad7)
![image](https://github.com/user-attachments/assets/7c3b6eb3-fa7e-4717-bf28-603814304e2a)
![image](https://github.com/user-attachments/assets/238f28ca-1866-437f-9d8c-633b550d06f0)
![image](https://github.com/user-attachments/assets/024693cb-a5b5-4b29-81b9-c01cee4101ea)
很多东西都没有动，除TUN两个打勾，路由选择中国其它都是默认。代理设置能正常上网

**Comment by Mahdi-zarei** [comment]
sorry for the delay, please try using gvisor in Tun settings, I believe it should solve your problem. Also i suggest you use tls://8.8.8.8 for remote dns and smux for mux.
