### ISSUE TITLE
BUG: آپدیترش ویروس شناسایی میشه

### ISSUE THREAD

**Issue by itmehr** [Mahdi-zarei/nekoray#153]
## Describe the problem

the updater has been detected as (Trojan:Win32/Wacatac.B!ml) Trojan By the latest version of Microsoft Defender Antivirus.

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by misagh72** [comment]
> "updater.exe"
false alarm

**Comment by Mahdi-zarei** [comment]
Ask microsoft why, and if you are concerned you can check the Code for Updater, it is open source and available.

**Comment by Mahdi-zarei** [comment]
> > Ask microsoft why, and if you are concerned you can check the Code for Updater, it is open source and available.
> 
> I prefer to don't continue using this fork of Nekoray if you strongly continue to providing reasons against this Trojan Detection.

I never provided reasons against this detection, I said you can read the code yourself, it is open source. And for the sake of common knowledge, the updater downloads the new zip, renames the old updater, extracts the zip to a new Dir and then copies its contents to override the current files, this pattern can be somewhat similar to some ransomwares and trojans so SOME anti virus apps detect this as a trojan. Anyways, do as you please.
