### ISSUE TITLE
BUG: Issues with Mixed TUN on some Windows installations with last updates. Please, revert to default gVisor stack, it works on all systems.

### ISSUE THREAD

**Issue by somebodywashere** [Mahdi-zarei/nekoray#154]
## Describe the problem

Expected behavior: Works perfectly without modifiying anything (default TUN mode)

Actual behavior: for some reason default (Mixed) TUN realisation stopped working on some windows installations. I can't be more datailed because it's not my own devices and I detected it via RDP helping people. System stack wasn't tested tho. Gvisor works without any noticed problem.

## How to reproduce

Just try to use on default settings on some systems with Win 10/11.

## log

None because of mentioning above (not my devices).

**Comment by Mahdi-zarei** [comment]
I did revert it, however gVisor stack also has problems on Linux, it is best for the user to find the most suitable stack by testing them out.

**Comment by somebodywashere** [comment]
Thanks! I understand that. Maybe it's possible to set defaults per OS, but probably it's too much work for nothing.

But judging that overall windows users have less technical skills I think it's better to set defaults for windows rather than linux :)
