### ISSUE TITLE
有计划增加路由逻辑规则吗

### ISSUE THREAD

**Issue by heibailiangxiangwang20** [Mahdi-zarei/nekoray#155]
## 描述建议
"type": "logical",
"mode": "and",
"rules": [],
"invert": false,
"outbound": "direct"
## 建议的必要性
sing-box的逻辑规则是一个很特色的功能，平时用到的场景也非常多，请问作者有计划增加此功能吗

**Comment by Mahdi-zarei** [comment]
for the time being there are no plans for this. Try using custom configs for now.
