### ISSUE TITLE
BUG:  v.4.1.6 Win10 url test error

### ISSUE THREAD

**Issue by ig-man** [Mahdi-zarei/nekoray#158]
Any group cannot pass "Url Test Group". Although "Test Result" shows Unavailable however the proxy server works (Traffic  is changing).
The "Url Test Group" was going good in the release 4.1.2 before updating.
![nk](https://github.com/user-attachments/assets/a3b2c156-f159-4148-8d2a-0f3db20bbeda)

**Comment by Mahdi-zarei** [comment]
I can't determine anything with the information you have provided.

**Comment by ig-man** [comment]
Url test is also a failure in the v.4.1.5
![nk1](https://github.com/user-attachments/assets/9cb246a0-4bfd-4624-82b7-f9bbbc756055)

**Comment by Mahdi-zarei** [comment]
I cannot determine the problem with your configuration, but try [4.2.0-beta.1](https://github.com/Mahdi-zarei/nekoray/releases/tag/4.2.0-beta.1), it has some of its default settings updated which may help you.

**Comment by ig-man** [comment]
My apologies, that was my antivirus Dr.Web. Nikoray was added to the exceptions and the test started working. Thanks!
