### ISSUE TITLE
BUG: ubuntu 使用dpkg安装deb文件后打不开

### ISSUE THREAD

**Issue by kirito201711** [Mahdi-zarei/nekoray#159]
## Describe the problem

Expected behavior:

Actual behavior:

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by Mahdi-zarei** [comment]
It needs to be run with admin, try removing sudo password requirement for your user.

**Comment by Mahdi-zarei** [comment]
try 4.2.2
