### ISSUE TITLE
Is setting gVisor as default a good idea performance wise?

### ISSUE THREAD

**Issue by midncircus** [Mahdi-zarei/nekoray#161]
I don't know what's under the hood of different stacks but judging simply by the CPU utilization Mixed gives me much better reults than gVisor.

If I open a bunch of sites simulteniously with gVisor the CPU utilization of nekobox_core.exe peaks usually between 1.6% - 1.9%
If I do the same with Mixed the result is somewhere between 0.6% - 1.0%

**Comment by Mahdi-zarei** [comment]
As a default yes it is a good idea since it is the most compatible stack for the time being, the ability to change the stack is also available if anyone wants to use them.
