### ISSUE TITLE
[Feature Request] TUN for process (like in original nekoray)

### ISSUE THREAD

**Issue by Keduber** [Mahdi-zarei/nekoray#164]
It will be great if your will leave TUN settings so users could set their software to use or not to use TUN

**Comment by Mahdi-zarei** [comment]
you can use a routing rule to only allow certain processes to use the Tun.

**Comment by Keduber** [comment]
> you can use a routing rule to only allow certain processes to use the Tun.

can you help me how it will look like? I need to set some processes to direct. with gui it was easy...

**Comment by Keduber** [comment]
Will this work and sent Photoshop to direct if I add this into Route-Default-New (after dns route) and use this ruleset?
```
      {
        "outboundTag": "direct",
        "processes": [
          "Photoshop.exe"
        ]
      }
```

**Comment by Mahdi-zarei** [comment]
yes it might work, you need to be sure that the name of process is precise, also you can provide the path to the executable.
