### ISSUE TITLE
BUG: Core exited when trying to enable TUN

### ISSUE THREAD

**Issue by stone-w4tch3r** [Mahdi-zarei/nekoray#165]
## Describe the problem

I am on Fedora 40 KDE 6, using nekoray-4.2.0-2024-09-22-linux64.zip 

1. Extract into `~/Downloads/nekoray`
2. Run `nekoray` binary without sudo
3. In interface check "Tun Mode"
4. Dialog "Please run nekoray as admin" appears
5. Yes
6. Type password in prompt
7. App restarts
8. Errors in log, tun not enabled, cant import connection

Restarting does not help

## log
```
[Error] Core exited, restarting.
[Error] Core exits too frequently, stop automatic restart this profile.
```

**Comment by Mahdi-zarei** [comment]
could you also try this with running the `launcher` instead of nekoray?

**Comment by Mahdi-zarei** [comment]
The reason is that even though nekobox core has CAP_SYS_ADMIN, nekoray  cannot run it with sudo. Do you know if the behavior differs in different Linux distributions? I know that this approach works in ubuntu.

**Comment by stone-w4tch3r** [comment]
AFAIK ubuntu uses AppArmour, and Fedora/RHEL uses SELinux. This may be the issue.

I can try to debug it, point out related source files please.

**Comment by Mahdi-zarei** [comment]
well the process is done in two parts, one in the `ui/mainwindow.cpp` line 728, where we set the `cap_sys_admin` for nekobox core. And after (an unnecessary) restart, if we detect that the core has the `cap_sys_admin` permission, we try to run it with sudo on `sys/ExternalProcess.cpp` line 57. It will really help out if you could tell me how we can run the core as root, while keeping nekoray itself as the calling user, as setting system proxy runs into problem if it is run as the root user, and `su` did not help here.

**Comment by miadabdi** [comment]
@stone-w4tch3r 
Did you find the problem?
I have the exact same issue on fedora 40.
Enabled tun mode then it started with admin

I restarted my computer
then running `sudo ./launcher` won't start the  app with admin, Or I should say it does but the core exists
The workaround seems to be running `sudo ./nekoray` which would run nekoray with admin and normal behaviour.
The if you run `sudo ./launcher` or even `./launcher` you would see the app has admin privilage and the core is starting without issues

@Mahdi-zarei 
nevertheless, I don't need tun mode, I want to revert it back to non-admin mode, so I can run it with my own user in a .desktop file. but I start it in any way, it is still in admin mode
Any ideas?

**Comment by Mahdi-zarei** [comment]
> nevertheless, I don't need tun mode, I want to revert it back to non-admin mode, so I can run it with my own user in a .desktop file. but I start it in any way, it is still in admin mode
> Any ideas?

You need to revoke CAP_SYS_ADMIN from nekobox core file.

**Comment by Mahdi-zarei** [comment]
The problem has nothing to do with fedora, I will try to fix it for the next release.

**Comment by Mahdi-zarei** [comment]
try 4.2.2

**Comment by stone-w4tch3r** [comment]
Tried, core starts fine! Unfortunately, now I have no active servers to test with, but main issue is resolved so everything should work.

Thanks a lot!

**Comment by Mahdi-zarei** [comment]
> Tried, core starts fine! Unfortunately, now I have no active servers to test with, but main issue is resolved so everything should work.
> 
> Thanks a lot!

Make sure to update to 4.2.3, as there was a minor problem regarding this issue.
