### ISSUE TITLE
clash api panel webview inside nekoray

### ISSUE THREAD

**Issue by AkramiPro** [Mahdi-zarei/nekoray#17]
is it possible to add new button that open clash api panel inside nekoray ?
i think you can check if the clash api is enabled then add new tab for that when config start.
many users do not have experience with clash api panel and this is good to have this inside nekoray so users do not have to use browser to access clash api panel.

**Comment by Mahdi-zarei** [comment]
Clash API is practically a web page, so I will need to see if QT offers a widget to serve it inside the app GUI.

**Comment by AkramiPro** [comment]
maybe this could help:

https://doc.qt.io/qt-6.5/qml-qtwebview-webview.html

**Comment by Mahdi-zarei** [comment]
After some searching, it appears that it can be a bit cumbersome to embed clash UI in nekoray, I don't think this feature is worth the effort it requires, so I will be closing this issue.
