### ISSUE TITLE
BUG: Using additional outbound in Route Rules causes group test errors

### ISSUE THREAD

**Issue by major-118** [Mahdi-zarei/nekoray#171]
In the routing rules, I created a rule that uses a separate outbond for the domain. 
_{
    "domain_suffix": [
        "qobuz.com"
    ],
    "outbound": "USA"
}_
And after that, a group url-test or a url-test of multiple dedicated configurations ends with an error.
**INFO[0000] router: updated default interface Ethernet, index 13
grpc-status error code: 2 , error msg: start service: outbound tag rout-0 duplicated
[Error] gRPC: QNetworkReply::NetworkError code: 301
Speedtest finished!**

Single configuration url-test continues to run

**Comment by Mahdi-zarei** [comment]
try 4.2.2

**Comment by major-118** [comment]
4.2.3 with VC++ update work fine
