### ISSUE TITLE
BUG: 4.2.1 when copy or ctrl+c vless reality config some parametrs lost! (Solved in 4.2.3)

### ISSUE THREAD

**Issue by ndsphonemy** [Mahdi-zarei/nekoray#174]
When copy or ctrl+c vless reality configs some parametrs lost!
The ones I noticed:
allowInsecure=
sni=
fp=
This causes some reality configs to become inoperable.

upd: in 4.2.0 everything was fine, it copied correctly.

**Comment by ndiruhniu** [comment]
I confirm, I have the same

**Comment by Mahdi-zarei** [comment]
try 4.2.2

**Comment by ndsphonemy** [comment]
> try 4.2.2

4.2.2 and 4.2.3 crash when start.

https://github.com/Mahdi-zarei/nekoray/issues/176#issuecomment-2406573067
