### ISSUE TITLE
BUG: 4.2.1 VLESS grpc is not working

### ISSUE THREAD

**Issue by ndiruhniu** [Mahdi-zarei/nekoray#175]
## Describe the problem

Expected behavior:

The connection should be established. I checked in husi(v0.9.0-rc.3) and NekoBox(4.0-beta4), there is a connection there.

Actual behavior:

There is no connection.

## How to reproduce

![nudrnurhnr](https://github.com/user-attachments/assets/58065684-8202-4369-8832-0f2e13f05e4b)
(Private information is blurred out.)

## log

ERROR[0021] [1805142617 10.0s] dns: lookup failed for duckduckgo.com: exchange6: context deadline exceeded | exchange4: context deadline exceeded

**Comment by Mahdi-zarei** [comment]
I suggest you use share->export sing-box config to see if there are any errors in the generated config, and report it to me.

**Comment by ndiruhniu** [comment]
It's weird, but I think I found the problem.
I use Remote DNS tls://dot.libredns.gr, and I also have prefer_ipv4 in Inbound Domain Strategy and Outbound Domain Strategy. With these settings, all protocols work fine, except grpc reality. So when I set nothing in Inbound Domain Strategy and Outbound Domain Strategy, the connection via this protocol worked. It's very weird.

**Comment by Mahdi-zarei** [comment]
This can be an issue with reality, the config you say seems fine to me and has no loopbacks or things like this.
