### ISSUE TITLE
BUG: nekoray-4.2.2 does not start

### ISSUE THREAD

**Issue by ironlag85** [Mahdi-zarei/nekoray#176]
## Describe the problem

Expected behavior: Launch of the program

Actual behavior: program does not start on win 10

**Comment by Mahdi-zarei** [comment]
I will wait for any *helpful* information to be provided, and from now on I will just close these kind of issues.

**Comment by sjjiqtkgg** [comment]
这兄弟问题应该跟我的一样

**Comment by ndsphonemy** [comment]
win11 23h2  22635.4300
nekoray 4.2.2 and latest 4.2.3 crash when start.
Even nekoray window does not open, the process appears in task manager and disappears after a few seconds.

windows event log entry:

**1**:

Контейнер ошибки 1160079544948270505, тип 4
Имя события: APPCRASH
Отклик: Нет данных
Идентификатор CAB: 0

Сигнатура проблемы:
P1: nekoray.exe
P2: 1.0.0.0
P3: 67082de4
P4: MSVCP140.dll
P5: 14.36.32532.0
P6: 04a30cf0
P7: c0000005
P8: 0000000000012f58
P9: 
P10: 

Вложенные файлы:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c7512642-fc53-421b-8956-e7cd5775bdb4.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.705d41fb-ef10-46c1-9273-d9a98ca00675.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8a99888c-8f5c-4889-9f41-e1b46d64d29a.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.796ebc64-412d-4bac-b133-727c28f9a199.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4f1ff453-f035-44ab-a8cd-0721d3f631a7.tmp.xml

Эти файлы можно найти здесь:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_nekoray.exe_e18e7c234d49f19c5cb92f23b54b66b9d9a1b47_ffb6b231_d1a27971-5916-4996-b742-878fd25c541f

Символ анализа: 
Повторный поиск решения: 0
Идентификатор отчета: b49e7e52-f05c-4708-8237-f7cd998c817b
Состояние отчета: 268435456
Хэшированный контейнер: 6216e56b045eb93460196e3323d6a5a9
Идентификатор GUID CAB: 0

**2**:

Имя сбойного приложения: nekoray.exe, версия: 1.0.0.0, метка времени: 0x67082de4
Имя сбойного модуля: MSVCP140.dll, версия: 14.36.32532.0, метка времени: 0x04a30cf0
Код исключения: 0xc0000005
Смещение ошибки: 0x0000000000012f58
Идентификатор сбойного процесса: 0x0x3AEC
Время запуска сбойного приложения: 0x0x1DB1B9B7A46924F
Путь сбойного приложения: C:\Portable\nekoray-fork\nekoray.exe
Путь сбойного модуля: C:\Windows\SYSTEM32\MSVCP140.dll
Идентификатор отчета: b49e7e52-f05c-4708-8237-f7cd998c817b
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

**report file contents
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_nekoray.exe_e18e7c234d49f19c5cb92f23b54b66b9d9a1b47_ffb6b231_d1a27971-5916-4996-b742-878fd25c541f** :

Version=1
EventType=APPCRASH
EventTime=133730968528592375
ReportType=2
Consent=1
UploadTime=133730968536877267
ReportStatus=268435456
ReportIdentifier=d1a27971-5916-4996-b742-878fd25c541f
IntegratorReportIdentifier=b49e7e52-f05c-4708-8237-f7cd998c817b
Wow64Host=34404
NsAppName=nekoray.exe
OriginalFilename=nekoray
AppSessionGuid=00003aec-0001-0128-4f92-467a9b1bdb01
TargetAppId=W:0006e033dce272465e1a035a8cc420bfba3a00000900!0000731892ac266db6b1c881bcd29bf2e71f308e2af6!nekoray.exe
TargetAppVer=2024//10//10:19:41:24!0!nekoray.exe
BootId=4294967295
TargetAsId=1015
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=6216e56b045eb93460196e3323d6a5a9
Response.BucketTable=4
Response.LegacyBucketId=1160079544948270505
Response.type=4
Sig[0].Name=Имя приложения
Sig[0].Value=nekoray.exe
Sig[1].Name=Версия приложения
Sig[1].Value=1.0.0.0
Sig[2].Name=Отметка времени приложения
Sig[2].Value=67082de4
Sig[3].Name=Имя модуля с ошибкой
Sig[3].Value=MSVCP140.dll
Sig[4].Name=Версия модуля с ошибкой
Sig[4].Value=14.36.32532.0
Sig[5].Name=Отметка времени модуля с ошибкой
Sig[5].Value=04a30cf0
Sig[6].Name=Код исключения
Sig[6].Value=c0000005
Sig[7].Name=Смещение исключения
Sig[7].Value=0000000000012f58
DynamicSig[1].Name=Версия ОС
DynamicSig[1].Value=10.0.22635.2.0.0.256.48
DynamicSig[2].Name=Код языка
DynamicSig[2].Value=1049
DynamicSig[22].Name=Дополнительные сведения 1
DynamicSig[22].Value=195b
DynamicSig[23].Name=Дополнительные сведения 2
DynamicSig[23].Value=195b719aec57d7bc9de247689ec8920a
DynamicSig[24].Name=Дополнительные сведения 3
DynamicSig[24].Value=ca25
DynamicSig[25].Name=Дополнительные сведения 4
DynamicSig[25].Value=ca25d9e8003daed8027c19f685a51b5a
UI[2]=C:\Portable\nekoray-fork\nekoray.exe
LoadedModule[0]=C:\Portable\nekoray-fork\nekoray.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\SYSTEM32\apphelp.dll
LoadedModule[5]=C:\Windows\System32\USER32.dll
LoadedModule[6]=C:\Windows\System32\win32u.dll
LoadedModule[7]=C:\Windows\System32\GDI32.dll
LoadedModule[8]=C:\Windows\System32\gdi32full.dll
LoadedModule[9]=C:\Windows\System32\msvcp_win.dll
LoadedModule[10]=C:\Portable\nekoray-fork\Qt6Network.dll
LoadedModule[11]=C:\Windows\System32\ucrtbase.dll
LoadedModule[12]=C:\Windows\System32\bcrypt.dll
LoadedModule[13]=C:\Portable\nekoray-fork\Qt6Widgets.dll
LoadedModule[14]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[15]=C:\Windows\System32\msvcrt.dll
LoadedModule[16]=C:\Windows\System32\WS2_32.dll
LoadedModule[17]=C:\Windows\System32\sechost.dll
LoadedModule[18]=C:\Windows\System32\RPCRT4.dll
LoadedModule[19]=C:\Windows\System32\ole32.dll
LoadedModule[20]=C:\Windows\System32\CRYPT32.dll
LoadedModule[21]=C:\Windows\System32\combase.dll
LoadedModule[22]=C:\Windows\System32\SHELL32.dll
LoadedModule[23]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[24]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[25]=C:\Windows\SYSTEM32\WINHTTP.dll
LoadedModule[26]=C:\Portable\nekoray-fork\Qt6Core.dll
LoadedModule[27]=C:\Windows\SYSTEM32\Secur32.dll
LoadedModule[28]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[29]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[30]=C:\Windows\SYSTEM32\UxTheme.dll
LoadedModule[31]=C:\Windows\SYSTEM32\MSVCP140.dll
LoadedModule[32]=C:\Windows\SYSTEM32\VCRUNTIME140.dll
LoadedModule[33]=C:\Windows\SYSTEM32\VCRUNTIME140_1.dll
LoadedModule[34]=C:\Windows\SYSTEM32\MSVCP140_1.dll
LoadedModule[35]=C:\Windows\SYSTEM32\WSOCK32.dll
LoadedModule[36]=C:\Portable\nekoray-fork\Qt6Gui.dll
LoadedModule[37]=C:\Windows\SYSTEM32\AUTHZ.dll
LoadedModule[38]=C:\Windows\SYSTEM32\MPR.dll
LoadedModule[39]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[40]=C:\Windows\SYSTEM32\NETAPI32.dll
LoadedModule[41]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[42]=C:\Windows\SYSTEM32\d3d11.dll
LoadedModule[43]=C:\Windows\SYSTEM32\dxgi.dll
LoadedModule[44]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[45]=C:\Windows\SYSTEM32\d3d12.dll
LoadedModule[46]=C:\Windows\SYSTEM32\DWrite.dll
LoadedModule[47]=C:\Windows\SYSTEM32\MSVCP140_2.dll
LoadedModule[48]=C:\Windows\SYSTEM32\SSPICLI.DLL
LoadedModule[49]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[50]=C:\Windows\SYSTEM32\NETUTILS.DLL
LoadedModule[51]=C:\Windows\SYSTEM32\SRVCLI.DLL
LoadedModule[52]=C:\Windows\System32\IMM32.DLL
LoadedModule[53]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[54]=C:\Windows\System32\NSI.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=22635
OsInfo[3].Key=ubr
OsInfo[3].Value=4300
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1049
OsInfo[7].Key=geoid
OsInfo[7].Value=203
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222882066
OsInfo[15].Key=osinsty
OsInfo[15].Value=2
OsInfo[16].Key=iever
OsInfo[16].Value=11.1.22621.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=3974
OsInfo[19].Key=svolsz
OsInfo[19].Value=395
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=220506
OsInfo[22].Key=bldtm
OsInfo[22].Value=1250
OsInfo[23].Key=bldbrch
OsInfo[23].Value=ni_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.22621.4300.amd64fre.ni_release.220506-1250
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=External
OsInfo[33].Key=expid
OsInfo[33].Value=NG:1CA0F4,FX:114145DF,FX:124117A5,FX:12BACA0D,FX:12C89713,FX:12DF21A9,FX:12ED781A,FX:12ED783A,FX:12ED7851,FX:12ED7864,FX:12F5D093,FX:12F5D41E,FX:12FE0F1E,FX:1300FA43,FX:13083122,FX:13093448,FX:130934A8,FX:130934DE,FX:13093503,FX:13093524,FX:1309354C,FX:130A5BF8,FX:130A631C,FX:130CC03C,FX:13143384,FX:13159315,FX:13164976,FX:131649D2,FX:1316F56B,FX:13170803,FX:13176AD4,FX:131795A2,FX:1317A2D6,FX:1317BE14,FX:1318CA30,FX:1318CAEE,FX:1318CAEF,FX:1318CAF4,FX:1318CBED,FX:1318CBF1,FX:13195EB7,FX:131A2317,FX:131A5892,FX:131A69B6,FX:131AB264,FX:131AB265,FX:131AB267,FX:131AB268,FX:131AB26A,FX:131AB26B,FX:131AB26C,FX:131AB26D,FX:131AB26E,FX:131AB270,FX:131AB271,FX:131AB272,FX:131AB274,FX:131AB276,FX:131AC9DE,FX:131B3F0F,FX:131BA20B,FX:131D7184,FX:131D8EFC,FX:131E3CD1,FX:131E5712,FX:131E5C5A,FX:13200D37,FX:1320305C,FX:1321AA0B,FX:13220E6B,FX:132213A1,FX:13244232,FX:13248B14,FX:13248CF4,FX:1324FB27,FX:1325AE7A,FX:1325AEFB,FX:132658C8,FX:13265B6E,FX:13265F56,FX:1326CEA5,FX:1326F8AB,FX:1326FBE7,FX:132795B0,FX:13286DBE,FX:1328C317,FX:1328FAFF,FX:1329B3E1,FX:1329E597,FX:1329E599,FX:1329E59A,FX:1329E59B,FX:1329E59E,FX:132A011E,FX:132A266B,FX:132A4157,FX:132A5547,FX:132AB493,FX:132AB495,FX:132AB496,FX:132AFF61,FX:132B3629,FX:132BA891,FX:132BA91D,FX:132BAAF4,FX:132C938A,FX:132CD384,FX:132D0FE7,FX:132D2691,FX:132DF42C,FX:132EB35F,FX:132EFFEC,FX:132F26B8,FX:132F39A8,FX:132F3ECF,FX:132FAB70,FX:132FF904,FX:13300DB4,FX:13304ADA,FX:1330EDC9,FX:13312DE4,FX:1332752E,FX:13329313,FX:13329314,FX:1332BE4A,FX:1332F24B,FX:13332621,FX:133332BE,FX:13334186,FX:13335705,FX:1334B55F,FX:13359839,FX:133598DE,FX:1335E4E0,FX:13363D3E,FX:13373D1D,FX:13375014,FX:13375025,FX:13377BFA,FX:1337F88A,FX:133836C0,FX:13386F05,FX:13386F06,FX:13388957,FX:1338E427,FX:1338EC29,FX:1338F080,FX:13394EA1,FX:133955AC,FX:13395A50,FX:1339867B,FX:1339E39F,FX:1339EC38,FX:1339F345,FX:133A39D7,FX:133A5166,FX:133A51C3,FX:133A5D7E,FX:133ADB8E,FX:133AEC3C,FX:133B5EA1,FX:133BD369,FX:133BF5BA,FX:133BFFED,FX:133C0679,FX:133C07C0,FX:133CC2A8,FX:133CFA78,FX:133D06FA,FX:133D06FB,FX:133D06FE,FX:133D06FF,FX:133D1368,FX:2E4AAE9,FX:30C465B,FX:3129C62,FX:315CF9E,FX:3163E31,FX:3170313,FX:3178161,FX:317A16B,FX:317D9D4,FX:3189469,FX:31899B8,FX:318BB6E,FX:31E66DD,FX:31E6967,FX:31FE455,FX:32094A3,FX:32094A5,FX:32117F7,FX:32117FA,FX:3224E50,FX:3286F25,FX:329E5B0,FX:329E5B2,FX:32A2778,FX:32BA508,FX:32E0D2E,FX:32F20A3,FX:32F3D90,FX:333870E0,FX:3354866,FX:33952A3,FX:339F2F4,FX:33A06C9,FX:33AA3AD,FX:33AF31C,FX:33B3DB6,FX:33B931C,FX:33BFCC1,FX:33C0AA0,FX:33CC906,FX:33CCAD8,FX:33D0699,FX:33D28BD,MD:283BAEF,ME:3036FD6,ME:3037091,ME:3038C64,ME:3038CEC,ME:3039059,ME:30390AF,ME:2E30A37
OsInfo[34].Key=fconid
OsInfo[34].Value=19194309,0,2,0;21031911,0,2,1;25385272,0,2,0;29532725,0,2,1;31043135,0,2,0;32222762,0,0,0;35681102,0,1,0;36351947,0,2,1;38873155,0,2,1;39145991,0,2,0;39281392,0,2,0;39382631,0,2,0;39695979,0,2,1;40330551,0,2,1;41118774,0,0,1;41267076,0,2,0;41655236,0,2,0;42105254,0,2,0;43133808,1,2,0;43203978,0,2,1;43231896,0,2,1;43283184,0,1,0;43729363,0,2,1;43866633,0,2,1;43968083,0,2,1;43998308,0,0,1;44030954,0,2,1;44063183,0,2,0;44361984,0,2,0;44470355,0,2,0;44533041,0,2,1;44776738,0,2,1;45046602,0,2,1;45130483,0,2,1;45286369,0,2,1;45286384,0,2,0;45286411,0,2,1;45374966,0,2,0;45380551,0,2,0;45515998,0,2,1;45796396,0,2,0;45825686,0,1,1;46013904,0,2,1;46027791,0,0,1;46045587,0,0,1;46077465,0,2,0;46084210,0,0,0;46094352,0,0,1;46107637,0,2,0;46221769,0,2,1;46237304,0,2,1;46448114,0,2,1;46624394,0,2,1;46650478,0,2,0;46700501,0,2,1;46700599,0,2,0;46700719,0,2,1;46700936,0,2,1;46715659,0,2,1;46874415,0,2,1;46963605,0,2,0;47035056,0,2,1;47106292,0,2,0;47205210,0,2,0;47268464,2,2,0;47287403,0,2,1;47410248,0,1,1;47557358,0,2,1;47718842,0,2,1;48053648,0,2,1;48084555,0,2,0;48142662,0,0,0;48142675,0,2,0;48281163,0,0,0;48362945,0,0,0;48433541,0,2,0;48433698,0,2,0;48433706,0,2,0;48433719,0,2,1;48446354,0,1,0;48449532,3,2,1;48468527,0,2,0;48468541,0,2,0;48540091,0,2,0;48636059,0,2,1;48637472,0,2,0;48697323,0,0,1;48719061,0,2,1;48780814,0,2,0;48789334,0,0,1;48799383,0,0,0;48818825,0,2,1;48872129,0,0,0;48885365,0,2,0;48896670,0,2,1;48914786,0,2,0;48915761,0,2,1;48917127,0,0,0;48980211,0,0,1;49006888,0,1,1;49054871,0,2,0;49084341,0,1,0;49107262,0,2,0;49204282,0,2,0;49204591,0,1,1;49239926,0,1,1;49268249,0,2,1;49309588,0,1,1;49385087,0,0,0;49402909,0,2,0;49542070,0,2,0;49577493,0,1,1;49585390,0,0,0;49615603,0,1,1;49646204,0,2,1;49646220,0,2,1;49666228,0,0,1;49673274,0,0,0;49676912,0,2,1;49683902,0,2,1;49689210,0,1,0;49718509,0,2,1;49804107,0,2,1;49820095,0,0,1;49992839,0,1,0;50050957,0,2,0;50054602,0,0,1;50104492,0,2,1;50174294,0,2,0;50198379,0,2,1;50201809,0,2,0;50228026,0,2,0;50288426,0,1,1;50288680,0,0,0;50297098,0,2,1;50309446,0,2,1;50383852,0,2,0;50389189,0,2,0;50390676,0,2,1;50552411,0,2,1;50556886,0,2,1;50557073,0,2,1;50564196,0,2,1;50564332,0,2,1;50565209,0,2,1;50565295,0,2,1;50619762,0,2,0;50619826,0,2,0;50628891,0,2,1;50638759,0,0,0;50657384,0,0,0;50659888,0,2,1;50662425,0,2,0;50692135,0,2,1;50733819,0,2,1;50762615,0,1,1;50878630,0,2,1;50897220,0,0,0;50968699,0,2,0;51018233,0,0,0;51087964,0,2,0;51095435,0,0,1;51099995,0,2,1;51119082,0,0,0;51254353,0,0,0;51344959,0,0,0;51345063,0,0,0;51360396,0,2,1;51461459,1,2,1;51482192,0,2,0;51511873,0,2,0;51532159,0,2,0;51535398,0,2,1;51578581,0,1,1;51629559,0,2,1;51732807,0,0,0;51759272,0,2,1;51782553,0,2,0;51790848,0,2,1;51834208,0,0,0;51849637,0,2,0;51877603,0,2,0;51878426,0,2,1;51889563,0,2,0;51891254,0,2,0;51900073,0,2,1;51914276,0,2,1;51942247,0,2,1;51944598,0,1,0;51978387,0,2,1;52059738,0,2,0;52087985,0,1,0;52282767,0,0,1;52303419,0,2,0;52330548,0,0,0;52404941,0,2,0;52412549,0,2,0;52433724,0,2,1;52443941,0,1,0;52538889,0,2,1;52558470,0,2,0;52718464,0,2,1;52800817,0,2,0;52846520,0,2,1;52873407,0,2,1;52876528,0,0,0;52876758,0,2,0;52888896,0,2,0;52934740,0,2,0;53086435,0,2,0;53117045,0,0,0;53151015,0,0,1;53272922,0,2,0;53308193,0,2,0;53330962,0,2,0;53416979,0,2,0;53508960,0,2,0;53523260,0,2,0;53615505,0,0,0;53615593,0,0,0
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
OsInfo[38].Key=servicinginprogress
OsInfo[38].Value=0
OsInfo[39].Key=featureupdatependingreboot
OsInfo[39].Value=0
FriendlyEventName=Остановка работы
ConsentKey=APPCRASH
AppName=nekoray
AppPath=C:\Portable\nekoray-fork\nekoray.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=6615C7F168C1308968D3A51357B5E494
MetadataHash=-939071388

**Comment by Mahdi-zarei** [comment]
Refer to #180
