### ISSUE TITLE
how to update nekobox_core on my own

### ISSUE THREAD

**Issue by johnayman0** [Mahdi-zarei/nekoray#18]
firstly i want to thank you for your efforts on improving nekoray since it's probably now abandoned by the original devs

can you write documentation or give me hints about the process of compiling the nekobox core of a specific version ? i can compile the nekobox core but i am able to only compile the version that's already in supported by you, but i am talking about compiling other versions (old versions or alpha versions). in v2rayn i can just copy paste replace the sing_box.exe core but in nekoray it's a different story, thanks.

**Comment by Mahdi-zarei** [comment]
The sing-box-extra is practically a wrapper around a sing-box project. if you look at its go.mod you can see the imported sing-box (which is currently being replaced given an issue with the official sing-box). so practically you just need to change the replacement of the sing-box to your own. Also consider the latest commit of the sing-box repo that is being used, you will either have to cherry-pick it or you have to revert the changes required in the sing-box-extra. That's all you need. Then you can look up the scripts in the nekoray project to see how the nekobox core is being built.

**Comment by johnayman0** [comment]
Thank you i forked sing-box-extra and tested it with 1.9.0 (non rc version) and worked very well.

**Comment by mehdifirefox** [comment]
ممنون از زحمات شما 
امکانش هست از این نسخه شما استفاده نکنیم وفقط singbox رو اپدیت کنیم؟

**Comment by misagh72** [comment]
> ممنون از زحمات شما امکانش هست از این نسخه شما استفاده نکنیم وفقط singbox رو اپدیت کنیم؟

یعنی چی؟

**Comment by mehdifirefox** [comment]
> > ممنون از زحمات شما امکانش هست از این نسخه شما استفاده نکنیم وفقط singbox رو اپدیت کنیم؟
> 
> یعنی چی؟

نکوری که پروژش متوقف شده .با v2rayn هم مشکل دارم.
چون ایشون برنامه نویسه سوال کردم میشه همین نکوباس رو فقط core رو آپدیت کرد

**Comment by Mahdi-zarei** [comment]
> ممنون از زحمات شما امکانش هست از این نسخه شما استفاده نکنیم وفقط singbox رو اپدیت کنیم؟

بله میشه

**Comment by mehdifirefox** [comment]
> > ممنون از زحمات شما امکانش هست از این نسخه شما استفاده نکنیم وفقط singbox رو اپدیت کنیم؟
> 
> بله میشه

یه اموزش دقیق میدید چیکار کنیم
مثلا من اومدم فایل nekobox_core جایگزین کزدم با نسخه جدید سینگ باکس ولی ارور داد

این v2rayn گزارشای زیادی اومده مشکل داره ،نکورای با همین عقب موندگیش عالیه

**Comment by Mahdi-zarei** [comment]
> > > ممنون از زحمات شما امکانش هست از این نسخه شما استفاده نکنیم وفقط singbox رو اپدیت کنیم؟
> > 
> > 
> > بله میشه
> 
> یه اموزش دقیق میدید چیکار کنیم مثلا من اومدم فایل nekobox_core جایگزین کزدم با نسخه جدید سینگ باکس ولی ارور داد
> 
> این v2rayn گزارشای زیادی اومده مشکل داره ،نکورای با همین عقب موندگیش عالیه

کافیه همین فایل nekobox core رو جایگزین کنید. من خودم تست کردم الان و هیچ اروری نداد.

**Comment by mehdifirefox** [comment]
> > > > ممنون از زحمات شما امکانش هست از این نسخه شما استفاده نکنیم وفقط singbox رو اپدیت کنیم؟
> > > 
> > > 
> > > بله میشه
> > 
> > 
> > یه اموزش دقیق میدید چیکار کنیم مثلا من اومدم فایل nekobox_core جایگزین کزدم با نسخه جدید سینگ باکس ولی ارور داد
> > این v2rayn گزارشای زیادی اومده مشکل داره ،نکورای با همین عقب موندگیش عالیه
> 
> کافیه همین فایل nekobox core رو جایگزین کنید. من خودم تست کردم الان و هیچ اروری نداد.

عجیبه، من همین چند دقیقه پیش تست کردم ارور میده تو لاگ، حالا فردا یع بار دیگه تست میکنم
تو بخش core اون بخش ادرس دادن مستقیم core  وقتی تغییری نمیکنه چ فایده ای دارع اون بخشو گذاشته؟ ادرس میدم مستقیم تغییراتی تو لاگ دیده نمیشه
این اگه خوب کار کنه دیگه دردسر نداشتیم

**Comment by misagh72** [comment]
> > > > > ممنون از زحمات شما امکانش هست از این نسخه شما استفاده نکنیم وفقط singbox رو اپدیت کنیم؟
> > > > 
> > > > 
> > > > بله میشه
> > > 
> > > 
> > > یه اموزش دقیق میدید چیکار کنیم مثلا من اومدم فایل nekobox_core جایگزین کزدم با نسخه جدید سینگ باکس ولی ارور داد
> > > این v2rayn گزارشای زیادی اومده مشکل داره ،نکورای با همین عقب موندگیش عالیه
> > 
> > 
> > کافیه همین فایل nekobox core رو جایگزین کنید. من خودم تست کردم الان و هیچ اروری نداد.
> 
> عجیبه، من همین چند دقیقه پیش تست کردم ارور میده تو لاگ، حالا فردا یع بار دیگه تست میکنم تو بخش core اون بخش ادرس دادن مستقیم core وقتی تغییری نمیکنه چ فایده ای دارع اون بخشو گذاشته؟ ادرس میدم مستقیم تغییراتی تو لاگ دیده نمیشه این اگه خوب کار کنه دیگه دردسر نداشتیم

چرا میخوای جایگزین کنی؟ از همین نسخه نکوباکس استفاده کنید دیگه سینگ باکس جدید هست

**Comment by mehdifirefox** [comment]
> > > > ممنون از زحمات شما امکانش هست از این نسخه شما استفاده نکنیم وفقط singbox رو اپدیت کنیم؟
> > > 
> > > 
> > > بله میشه
> > 
> > 
> > یه اموزش دقیق میدید چیکار کنیم مثلا من اومدم فایل nekobox_core جایگزین کزدم با نسخه جدید سینگ باکس ولی ارور داد
> > این v2rayn گزارشای زیادی اومده مشکل داره ،نکورای با همین عقب موندگیش عالیه
> 
> کافیه همین فایل nekobox core رو جایگزین کنید. من خودم تست کردم الان و هیچ اروری نداد.

شاید این نسخه شما مشکل نداره وگرنه دوباره تست کردم نشد ارور میده
بیزحمت ببین میتونی راه حلی پیدا کنی
چون دنبال یه راه دائمی میگردم مثلا ممکنه شما دراینده دیگه آپدیتش نکنی

**Comment by misagh72** [comment]
> > > > > ممنون از زحمات شما امکانش هست از این نسخه شما استفاده نکنیم وفقط singbox رو اپدیت کنیم؟
> > > > 
> > > > 
> > > > بله میشه
> > > 
> > > 
> > > یه اموزش دقیق میدید چیکار کنیم مثلا من اومدم فایل nekobox_core جایگزین کزدم با نسخه جدید سینگ باکس ولی ارور داد
> > > این v2rayn گزارشای زیادی اومده مشکل داره ،نکورای با همین عقب موندگیش عالیه
> > 
> > 
> > کافیه همین فایل nekobox core رو جایگزین کنید. من خودم تست کردم الان و هیچ اروری نداد.
> 
> شاید این نسخه شما مشکل نداره وگرنه دوباره تست کردم نشد ارور میده بیزحمت ببین میتونی راه حلی پیدا کنی چون دنبال یه راه دائمی میگردم مثلا ممکنه شما دراینده دیگه آپدیتش نکنی

راحل دائمی اینجاست 
https://github.com/Mahdi-zarei/nekoray/issues/18#issuecomment-2141102869
اگر هم بلد نیستی یا از نرم افزار های دیگه استفاده کنید

**Comment by johnayman0** [comment]
> > > > Thank you for your efforts, is it possible to not use this version of yours and just update singbox?
> > > 
> > > 
> > > yes it can
> > 
> > 
> > A detailed tutorial on what to do. For example, I replaced the nekobox_core file with the new version of Singbox, but it gave an error. 
> > There have been many reports of this v2rayn having problems, Nekoray is great with this lag
> 
> Just replace this nekobox core file. I tested it myself now and it didn't give any error.

he probably just downloaded singbox from sagernet and renamed it to nekobox_core without sing-box-extra wrapper

**Comment by mehdifirefox** [comment]
> > > > > Thank you for your efforts, is it possible to not use this version of yours and just update singbox?
> > > > 
> > > > 
> > > > yes it can
> > > 
> > > 
> > > A detailed tutorial on what to do. For example, I replaced the nekobox_core file with the new version of Singbox, but it gave an error.
> > > There have been many reports of this v2rayn having problems, Nekoray is great with this lag
> > 
> > 
> > Just replace this nekobox core file. I tested it myself now and it didn't give any error.
> 
> he probably just downloaded singbox from sagernet and renamed it to nekobox_core without sing-box-extra wrapper

yes . 
I have to do something else؟
