### ISSUE TITLE
Win11 nekoray 4.2.2 and latest 4.2.3 crash when start. (Solved)

### ISSUE THREAD

**Issue by ndsphonemy** [Mahdi-zarei/nekoray#180]

**Comment by ndsphonemy** [comment]
Problem solved, after update vc_redist.x64
download from https://learn.microsoft.com/ru-ru/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Mahdi-zarei** [comment]
Thank you for investigating this problem, I believe with windows updates frequently installed, this problem is unlikely to occur, as I tested on two windows 11 systems with fairly recent updates installed and it worked without any issues.

**Comment by M450ud** [comment]
Windows 10 Enterprise  22H2 Version 10.0.19045.5011

NR 4.2.3 crashing on startup.

**Comment by Mahdi-zarei** [comment]
> > Thank you for investigating this problem, I believe with windows updates frequently installed, this problem is unlikely to occur, as I tested on two windows 11 systems with fairly recent updates installed and it worked without any issues.
> 
> Apparently it's not. On my two pc's, win11 insider preview builds, from beta channel, usually windows is updated once a week. I can say my windows is new and updated.

My next guess is that some apps which need this component install it along their installation process, and since Nekoray is portable, one needs to install the c++ runtime dependencies himself.

**Comment by Mahdi-zarei** [comment]
> Windows 10 Enterprise 22H2 Version 10.0.19045.5011
> 
> NR 4.2.3 crashing on startup.

Did you install the latest vc redist and c++ redistributables ?

**Comment by M450ud** [comment]
> > Windows 10 Enterprise 22H2 Version 10.0.19045.5011
> > NR 4.2.3 crashing on startup.
> 
> Did you install the latest vc redist and c++ redistributables ?

After reinstalling VC redist now working.
thanks.
