### ISSUE TITLE
4.2.3换中文字体了吗？没以前好看了，希望换回去

### ISSUE THREAD

**Issue by zhegeshijiehuiyouai** [Mahdi-zarei/nekoray#181]
我从4.2.1升级到4.2.3后，发现中文字体看起来很奇怪，没有以前舒服，感觉dpi和屏幕不兼容了，感觉像素没有对其一样。
恰好在更新说明里有提到中文翻译，所以我想是不是替换了中文字体，能还原回去吗？

**Comment by Mahdi-zarei** [comment]
No changes have been made the fonts, the only possible culprit is the upgrade of Qt which may have changed the fonts. For the time being I can only suggest that you tweak this from outside the nekoray, as the feature to change fonts is not implemented.

**Comment by zhegeshijiehuiyouai** [comment]
ok, thanks

**Comment by Mahdi-zarei** [comment]
> > 字体没有发生任何变化，唯一可能的原因是 Qt 升级可能改变了字体。目前我只能建议你从 nekoray 外部进行调整，因为改变字体的功能尚未实现。
> 
> After updating Qt from 6.7.3 to 6.8.0, I also encountered this issue on Windows. The system default font, Microsoft YaHei UI, appears blurry. In my fork, I added a font-switching feature, and after changing to Microsoft YaHei, the display returns to normal as it was before. I'm not sure what changes in Qt caused this behavior.

I will try to implement a font switch feature like the theme one in the next release then.

**Comment by Mahdi-zarei** [comment]
> > After updating Qt from 6.7.3 to 6.8.0, I also encountered this issue on Windows. The system default font, Microsoft YaHei UI, appears blurry. In my fork, I added a font-switching feature, and after changing to Microsoft YaHei, the display returns to normal as it was before. I'm not sure what changes in Qt caused this behavior.
> 
> Based on my testing, it seems that Qt 6.8.1 has fixed the issue with the default Windows font display. You may want to update it.

it is not yet officially released, I'm not sure if the github actions will be able to download it, but I will update to it once it is available.
