### ISSUE TITLE
BUG: Wireguard configurations stopped working in version 4.2.3.

### ISSUE THREAD

**Issue by planzar** [Mahdi-zarei/nekoray#182]
In version 4.2.3, Wireguard configurations that work in version 4.2.1 stopped working.
This happens on Windows 10, 11 and Linux.

![2024-10-11_110503](https://github.com/user-attachments/assets/a52863df-8e2e-4752-a51d-89a93f680d9f)

![2024-10-11_110947](https://github.com/user-attachments/assets/59669636-09ae-400b-a116-63cb58341345)

How can I fix it?

**Comment by Mahdi-zarei** [comment]
This issue seems to be only affecting url tests and the config itself should work. I will fix the url test issue in the next release.

**Comment by planzar** [comment]
Thank you very much.
I panicked.
