### ISSUE TITLE
BUG: Bug with VLESS import that is persisted even before fork

### ISSUE THREAD

**Issue by somebodywashere** [Mahdi-zarei/nekoray#185]
### Expected behavior:

When importing VLESS key, Packet encoding should be defaulted to XUDP, if nothing passed (Actually there's no way to pass this through the link format).

This is stated by [sing-box docs](https://sing-box.sagernet.org/configuration/outbound/vless/#flow)

### Actual behavior:

Packet encoding is empty

### How to reproduce

Import any VLESS key. Packet encoding will be empty

**Comment by somebodywashere** [comment]
Sorry, the tag in link is wrong. It's https://sing-box.sagernet.org/configuration/outbound/vless/#packet_encoding

**Comment by Mahdi-zarei** [comment]
I noticed this, i will set xudp as default for the next release.
