### ISSUE TITLE
BUG: can not defind dns server in dhcp type

### ISSUE THREAD

**Issue by AkramiPro** [Mahdi-zarei/nekoray#19]
## Describe the problem

![image](https://github.com/Mahdi-zarei/nekoray/assets/54323929/5484f8f2-6cd1-4943-a0e2-68f2abd17352)

## How to reproduce

```
            {
                "address": "dhcp://auto",
                "detour": "direct",
                "tag": "dns-local"
            },
```

**Comment by Mahdi-zarei** [comment]
Will include the tag on the next release.
