### ISSUE TITLE
BUG: Route Profile Import JSON can't properly import ```"ip_is_private": true,```

### ISSUE THREAD

**Issue by SudoerReodus** [Mahdi-zarei/nekoray#190]
## Describe the problem

When using "Import JSON" dialog in the "Route Profile" window, to import this rule:

```
[{
    "ip_is_private": true,
    "outbound": "direct"
}]
```

Expected behavior:

It should import it as:

```
{
    "ip_is_private": true,
    "outbound": "direct"
}
```

Actual behavior:

But it instead will remove the ```"ip_is_private": true,``` and import the rule as:

```
{
    "outbound": "direct"
}
```

## How to reproduce

Described above.

## log

Version 4.2.3

**Comment by Mahdi-zarei** [comment]
try 4.2.4

**Comment by SudoerReodus** [comment]
Thanks, it works now.
