### ISSUE TITLE
BUG: "outbound with name dns_out does not exist"

### ISSUE THREAD

**Issue by SudoerReodus** [Mahdi-zarei/nekoray#193]
## Describe the problem

When attempting to import the following rule using the Import JSON dialog in the Route Profile window:

```
[{
    "outbound": "dns_out",
    "protocol": "dns"
}]
```

You get the following error:

![image](https://github.com/user-attachments/assets/3cbd64f9-e076-49cd-aec5-013542933f4e)

Even though this rule exists in default profiles and works just fine if you add it manually instead of using the Import JSON dialog. 

Version: 4.2.3

**Comment by Mahdi-zarei** [comment]
try 4.2.4

**Comment by SudoerReodus** [comment]
Thanks, it works now.
