### ISSUE TITLE
4.2.3订阅分组不支持clash了

### ISSUE THREAD

**Issue by zhegeshijiehuiyouai** [Mahdi-zarei/nekoray#194]
## Description suggestions
nekoray之前都是支持clash订阅的，但是升级到4.2.3后不支持了。

## Necessity of recommendations
互联网上别人分享的节点订阅链接，并不是都可以选择v2ray格式或者clash格式的，有些分享就只有clash格式，现在无法导入，就不能使用别人的分享了，只能选择停留在老版本

**Comment by misagh72** [comment]
yes you need to read changelog

. Deprecate clash meta subscription parsing format

**Comment by zhegeshijiehuiyouai** [comment]
我看了changelog，了解到了这一变动，但直接删除clash订阅解析是出于什么目的呢，很多人都会用到这个功能，这样删除似乎只是让nekoray没有以前强大了。
如果是因为有什么无法调和的漏洞而剔除的，那么可不可以考虑给个开关，让我们自行决定是否启动clash解析并自行承担开启后的危害。

**Comment by misagh72** [comment]
use original nekoray if you want clash subscription 
https://github.com/MatsuriDayo/nekoray

**Comment by Mahdi-zarei** [comment]
The reason clash meta has been removed is that it no longer has a source of truth, the original project has been taken down and everyone is extending it as they want, which removes the possibility of having a uniform protocol, and thus it is removed.

**Comment by zhegeshijiehuiyouai** [comment]
我看到你已经将clash配置解析重新添加回来了，感谢感谢。
如果之前删除clash配置是因为clash删除事件而担忧的话，可以考虑这个项目 https://github.com/MetaCubeX/mihomo ，这个是开源的clash高级版本，不少clash gui代理工具都将内核切换成了这个内核。
不过我们我们应该只会用到解析clash配置节点，并将其转换为singbox节点吧，用不到clash复杂的规则。

**Comment by Mahdi-zarei** [comment]
I don't have plans for improving the current clash format, but you can use it again in 4.2.4.
