### ISSUE TITLE
BUG: Hysteria2 protocol errors 

### ISSUE THREAD

**Issue by zuohl** [Mahdi-zarei/nekoray#196]
## Describe the problem
Hysteria2 kernel not found, go to settings
<img width="350" alt="image" src="https://github.com/user-attachments/assets/4cecb712-f82b-4fc8-931b-1c6efa5812d9">

**Comment by zuohl** [comment]
mac m1pro

**Comment by Mahdi-zarei** [comment]
Either disable force use external core or load the hysteria2 extra core.
