### ISSUE TITLE
Other suggestions 

### ISSUE THREAD

**Issue by Graveyard9988** [Mahdi-zarei/nekoray#2]
Some enhancement for your fork:

https://github.com/maskedeken/sing-box/commits/neko-1.8.x/

And

https://github.com/xchacha20-poly1305/husi/commits/dev/

**Comment by Mahdi-zarei** [comment]
The first link you sent is practically a mirror of sing-box and I don't understand what I should do about it, the version of sing-box in my fork of nekoray is already updated to 1.9.0-rc.14. Regarding the second link, I do plan to eventually add all the useful features (tcp brutal, rule sets etc) and Husi is an android client and it's history of commits are of no help here.
