### ISSUE TITLE
BUG: Whitelist mode for Tun doesn't work

### ISSUE THREAD

**Issue by midncircus** [Mahdi-zarei/nekoray#20]
While Blacklist mode works as expected, the Whitelist mode settings are completely ignored.

The original NeroBox had the same issue. It only worked for XRay or if you disable Internal Tun for sing-box. But both workarounds are gone now.

Windows 10 here.
![2024-06-06_004112](https://github.com/Mahdi-zarei/nekoray/assets/171871443/6f688899-938c-4856-b050-74a732aef0bd)

**Comment by Mahdi-zarei** [comment]
I will soon update the app to allow leveraging the sing-box's process name routing and allow for complete route definitions, this should practically remove the need for whitelist mode as it is practically a simple rule that routes all traffic directly unless specified otherwise.

**Comment by Mahdi-zarei** [comment]
Try the new routing system, you should be able to achieve whatever the old Tun settings could offer.
