### ISSUE TITLE
BUG: 4.2.4 Linux The "Cancel" and "OK" buttons are missing.

### ISSUE THREAD

**Issue by ndiruhniu** [Mahdi-zarei/nekoray#201]
## Describe the problem

Actual behavior: There are simply no buttons

## How to reproduce

Go to the config editor
![pic1](https://github.com/user-attachments/assets/88f08385-32ee-43d6-852b-fe09088b0c23)

**Comment by Mahdi-zarei** [comment]
sorry for the inconvenience, please redownload the 4.2.4 release.

**Comment by ndiruhniu** [comment]
Thank you. It works now.

**Comment by TheWeirdDev** [comment]
The issue still persists when I build the app from source.
