### ISSUE TITLE
BUG: 订阅和节点如果是中文域名，则无法正常工作

### ISSUE THREAD

**Issue by bupt2017** [Mahdi-zarei/nekoray#214]
## Describe the problem

大佬您好，首先很感谢您的付出。从上游断更之后我就一直在用您维护的这个版本。
但是现在在使用的时候发现了一个问题，就是如果订阅和节点是中文域名的话，订阅和节点就无法正常工作。

这个问题在上游维护的版本中是不存在的，不知道是不是您将对中文域名的支持移除了（虽然真的很少有人会用中文域名，比如 `你好.com` ）

Expected behavior:
预期行为1：中文域名的订阅链接可以获取到节点。
预期行为2：中文域名的节点可以正常使用

Actual behavior:
实际行为1：中文域名的订阅链接无法获取到节点
实际行为2：中文域名的节点无法使用 （但是可以使用快捷键`ctrl+shift+I` 将中文域名转为ip，则节点就能使用了）

## How to reproduce
使用中文域名订阅或者使用中文域名的节点即可复现

Provide steps on how the problem can be reproduced. Issues without this will be closed.
Statements like `App dont work` and `config not connect` provide no useful information.

## log
《如果是订阅链接是中文域名的日志》
MatsuriDayo维护的：成功获取
>>>>>>>> Requesting subscription: yl
<<<<<<<< Subscription request fininshed: yl
<<<<<<<< Change of yl:
Added 9 profiles:
[+] [Hysteria2] [Hy2]剩余流量：20 GB
[+] [Hysteria2] [Hy2]距离下次重置剩余：21 天
[+] [Hysteria2] [Hy2]套餐到期：2024-12-12
[+] [Hysteria2] [Hy2]🇰🇷韩国-首尔3-500M
[+] [Hysteria2] [Hy2]🇰🇷韩国-首尔4-500M
[+] [Hysteria2] [Hy2]🇯🇵日本-东京-500M-1
[+] [Hysteria2] [Hy2]🇯🇵日本-东京-500M-2
[+] [Hysteria2] [Hy2]🇩🇪德国-法兰克福-2500M
[+] [Hysteria2] [Hy2]🇩🇪德国-法兰克福-500M 1
Deleted 0 Profiles:

您目前维护：获取为空
>>>>>>>> Requesting subscription: yl
<<<<<<<< Subscription request fininshed: yl
<<<<<<<< Change of yl:
Nothing

《如果是节点是中文域名，进行url test测试的日志》
MatsuriDayo维护的：成功测试出延迟 （为了保护隐私，我将日志中的真实的中文域名换成了《你好.com》，将解析出来的真实ip进行了隐藏）
INFO[0000] sing-box started (0.00s)
INFO[0000] outbound/hysteria2[proxy]: outbound connection to cp.cloudflare.com:80
INFO[0000] outbound/direct[direct]: outbound packet connection to 180.184.1.1:53
INFO[0000] dns: exchanged de.node.xn--6qq79v.com A de.node.xn--6qq79v.com. 258 IN A 141.x.x.x
INFO[0000] dns: exchanged de.node.xn--6qq79v.com SOA xn--6qq79v.com. 1800 IN SOA carlane.ns.cloudflare.com. dns.cloudflare.com. 2355010059 10000 2400 604800 1800

您目前维护：
INFO[0000] router: updated default interface Ethernet, index 5
INFO[0000] sing-box started (0.00s)
INFO[0000] outbound/hysteria2[proxy]: outbound connection to cp.cloudflare.com:80
[[Hysteria2] [Hy2]🇩🇪德国-法兰克福-500M 1] test error: Get "http://cp.cloudflare.com/": invalid address
Speedtest finished!

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by Mahdi-zarei** [comment]
The first one should be about the cURL, it seems there are issues with unicode addresses, I will try to fix it but I am not sure if this is possible. The speedtest issue is really weird, the only guess I got is that sing-box does not support it, can you check this please?

**Comment by bupt2017** [comment]
十分抱歉大佬，您的判断是正确的，第二个关于url test的问题是我的不细心导致的。具体原因是将一个address是中文域名的节点导入到nekoray的时候并不会自动进行Punycode 编码。这个现象在上游和您维护的版本中是一致的。

第一个：是直接将节点复制到nekoray中，这个现象在上游和您维护的版本中是一致的。
（原来的节点已经经过了Punycode 编码，但是导入到软件中会恢复成中文域名）

第二个：是通过快捷键ctrl+shift+I将中文域名解析成了IP
第三个：是我手动将中文域名替换成了Punycode 编码的域名
![image](https://github.com/user-attachments/assets/c0046cea-fe64-4405-bdfb-b124faaa94a7)

再次感谢大佬的付出

**Comment by Mahdi-zarei** [comment]
Great to hear that you got it to work, it is best that you handle these edge cases manually, as finding a solution that supports these cases can be pretty cumbersome.

**Comment by bupt2017** [comment]
您做的已经很好了，很感谢
