### ISSUE TITLE
BUG: Created custom route profile disappears after restarting program

### ISSUE THREAD

**Issue by ItsBenyaamin** [Mahdi-zarei/nekoray#216]
## Describe the problem
After creating the route profile(clone Bypass Iran and add some other rules to it) and restarting the program, The created profile just disappears.

Distro: Fedora 40

![Screenshot from 2024-10-29 08-33-05](https://github.com/user-attachments/assets/34ec08a1-46dd-48e3-bfc8-fe82cd6f9a80)

**Comment by ItsBenyaamin** [comment]
Any update?

**Comment by milkyfuckinway** [comment]
For me it only happens when cloning any default route, when create new one from scratch it saves normally

**Comment by milkyfuckinway** [comment]
> try 4.2.6

works fine, thanks
