### ISSUE TITLE
BUG: Remove Duplicates and Sorting Features Not Working Correctly in Nekoray on Linux

### ISSUE THREAD

**Issue by Turbine8845** [Mahdi-zarei/nekoray#233]
## Describe the Problem

Dear Mahdi,

Thank you for consistently updating nekoray and adding new features. I have noticed several minor bugs in the Linux version of nekoray which is provided in `nekoray-4.2.7-2024-12-04-linux64.zip`. Here is a list of the bugs:

1. The `Remove Duplicates` feature incorrectly removes non-duplicate configurations on Linux. The Windows version of nekoray does not appear to be affected by this issue.

2. Configurations cannot be properly sorted by `Name` and `Test Result` in the Linux version. I have tried to sort my configurations by `Name` and `Test Result` multiple times, but each time, I get a completely different sorting result.

## Expected Behavior

- The `Remove Duplicates` feature should only remove duplicate configurations.
- Clicking on the `Type`, `Address`, `Name`, and `Test Result` columns should properly sort the configurations.

## Actual Behavior

- The `Remove Duplicates` feature removes non-duplicate configurations.
- The sorting feature gives different results each time it is used.

## How to Reproduce
1. Create a group in Linux and Windows versions of nekoray using the following provider: https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.txt

2. Use the `Remove Duplicates` feature in Linux and Windows versions of nekoray and compare the results.

3. Attempt to sort the configurations by different criteria in Linux and Windows versions of nekoray. Compare the results afterward.

**Comment by Mahdi-zarei** [comment]
I am currently refactoring the codes, so it should be fixed by the time I get to these parts.

**Comment by Mahdi-zarei** [comment]
I tried to reproduce the problems, none of them were observed. Also note that by clicking on the columns the order of sort changes from desc to asc and vice versa, and I believe this is what you have observed. Regarding the remove dup the behavior was consistent in windows and linux which is expected, as the code for that part is by no means platform dependant. If you have more information on these issues please provide them, otherwise there is nothing to be done here.

**Comment by Turbine8845** [comment]
> I tried to reproduce the problems, none of them were observed. Also note that by clicking on the columns the order of sort changes from desc to asc and vice versa, and I believe this is what you have observed. Regarding the remove dup the behavior was consistent in windows and linux which is expected, as the code for that part is by no means platform dependant. If you have more information on these issues please provide them, otherwise there is nothing to be done here.

Thanks for your explanation. I tried a freshly extracted version of nekoray on both Windows and Linux and it had no issues. What I did previously was that I copied the contents of the `config` folder from nekoray on Windows to my Linux instance of nekoray and I guess this caused the issues that I reported earlier.
