### ISSUE TITLE
[FR]: Bundling Fonts and Country Flag Emojis in Nekoray for Cross-Platform Compatibility

### ISSUE THREAD

**Issue by Turbine8845** [Mahdi-zarei/nekoray#234]
## Description suggestions
Dear Mahdi,

Unfortunately, Microsoft does not bundle country flag emojis by default in Windows. You can find more information about this limitation on the following page: [Microsoft Support - Country Flag Emojis](https://answers.microsoft.com/en-us/windows/forum/all/country-emoji-for-windows/78a3e92b-02a8-4e7c-814e-c1c0596eaf4e)

This limitation causes Nekoray to display country flag emojis incorrectly on Windows, as shown below: 

![nekoray_flag_emojis_on_windows](https://github.com/user-attachments/assets/6b144a08-4890-42bb-a36b-152b69e29988)

On Linux, however, this is not an issue due to its open-source nature and customizable font configurations. Country flag emojis appear correctly, as shown in the following screenshot:

![nekoray_flag_emojis_on_linux](https://github.com/user-attachments/assets/cefbdc07-94db-49a4-9858-ebf416701b75)

Is it possible to bundle the necessary fonts and emoji support with Nekoray to ensure that country flag emojis in configuration names are displayed correctly across all platforms, including Windows?

## Necessity of recommendations
Many free config providers on the internet use country flag emojis as part of their config names, which can lead to a broken or incomplete experience on Windows. By bundling the necessary fonts or configurations, Nekoray could offer consistent cross-platform support, allowing users on all operating systems to view these emojis correctly. This would enhance the user experience for Windows users and make the application more versatile overall.

**Comment by Mahdi-zarei** [comment]
I don't know how I can bundle fonts, but I will try to look into it.

**Comment by Restia-Ashbell** [comment]
It's best to resolve system issues at the system level. Otherwise, other applications, such as browsers, will still fail to display properly. Replacing the default emoji font on your own is the best solution, such as using [Twemoji](https://github.com/13rac1/twemoji-color-font).

**Comment by Turbine8845** [comment]
> It's best to resolve system issues at the system level. Otherwise, other applications, such as browsers, will still fail to display properly. Replacing the default emoji font on your own is the best solution, such as using [Twemoji](https://github.com/13rac1/twemoji-color-font).

I tried this on a Windows 10 VM and it didn't work. 

![nekoray](https://github.com/user-attachments/assets/e7964240-13b5-42da-a0f5-44d8d90e5492)


Unfortunately, Windows is a retarded platform and I doubt anything can be done to have proper country flag emojis on Windows.

**Comment by Restia-Ashbell** [comment]
> I tried this on a Windows 10 VM and it didn't work.

This is your operational issue. You don't explain what you did when it doesn't work. You shouldn't need others to teach you how to use Windows.

**Comment by Turbine8845** [comment]
> This is your operational issue. You don't explain what you did when it doesn't work. You shouldn't need others to teach you how to use Windows.

I did this and it didn't work. These steps were described in the github project you mentioned:

1. Download the most recent Python 3 for Windows: https://www.python.org/downloads/windows/
2. Start the installer, select "Add Python 3.6 to PATH", finish the install process, then reboot.
3. Download Twitter Color Emoji Windows package from releases: https://github.com/13rac1/twemoji-color-font/releases/download/v15.1.0/TwitterColorEmoji-SVGinOT-Win-15.1.0.zip
4. Uncompress the file.
5. Open the new TwitterColorEmoji directory.
6. Run install.cmd. Note: This will take some time.
7. Install both new fonts when requested.

This is another project for adding country flag emojis to Windows but it's deprecated now and it doesn't work on the newer builds of Windows 10 and Windows 11.
https://github.com/perguto/Country-Flag-Emojis-for-Windows

If you have a solution for Windows, I really appreciate it if you share it. I already use nekoray on Arch Linux and it's not affected by this issue.

**Comment by Restia-Ashbell** [comment]
> If you have a solution for Windows, I really appreciate it if you share it. I already use nekoray on Arch Linux and it's not affected by this issue.


Sorry, if your steps are correct, I’m not sure why it’s not working either. You can check in the font settings to ensure the font is properly installed.

You can also try this simpler method:
[Seguiemj Mod Ver 1.31](https://llccd.eu.org/files/seguiemj_1_31_mod.ttf) (for Windows 10)
[Seguiemj Mod Ver 1.33](https://llccd.eu.org/files/seguiemj_1_33_mod.ttf) (for Windows 11)
These are modified versions of the Segoe UI Emoji font with Twemoji's flag emojis extracted and added. Simply double-click to install, or right-click and select "Install for all users".

**Comment by ndsphonemy** [comment]
> [Seguiemj Mod Ver 1.33](https://llccd.eu.org/files/seguiemj_1_33_mod.ttf) (for Windows 11)

Work on Win11 24h2 latest insider build from Dev chanel.

**Comment by Turbine8845** [comment]
> You can also try this simpler method: [Seguiemj Mod Ver 1.31](https://llccd.eu.org/files/seguiemj_1_31_mod.ttf) (for Windows 10) [Seguiemj Mod Ver 1.33](https://llccd.eu.org/files/seguiemj_1_33_mod.ttf) (for Windows 11) These are modified versions of the Segoe UI Emoji font with Twemoji's flag emojis extracted and added. Simply double-click to install, or right-click and select "Install for all users".

Thank you. This fixed the country flag emojis issue on Windows.

![nekoray_with_flag_emojis_on_windows](https://github.com/user-attachments/assets/ae098ab1-7ea5-4a6b-8692-c942ec924c38)
