### ISSUE TITLE
BUG: 比较严重的安全问题。

### ISSUE THREAD

**Issue by XyHK-HUC** [Mahdi-zarei/nekoray#236]
在4.2.7的最新版本中，会造成严重的DNS泄露问题：

当仅仅代理而不启用Tun模式时，完全通过本地的运营商即真实的DNS解析网站。
当启用Tun模式时，会造成代理服务器DNS+真实DNS共同解析网站。

可尝试使用下面两个网站测试严重的泄露BUG
https://www.astrill.com/dns-leak-test

https://whoer.net/

**Comment by Mahdi-zarei** [comment]
Please configure your browser to use the proxy dns. Proxy mode by default does not affect dns unless the user app is properly configured.

**Comment by Mahdi-zarei** [comment]
> Additionally, I noticed extra `[]` brackets appearing in the logs. After checking the sing-box configuration exported with the default settings, I didn’t find any issues.

This is most likely due to sing-box changes, inside the brackets should be the user ( as in username of http or socks auth ) which is out of context here and thus empty.

This whole situation though could be due to the change in the format of proxy, previously it was `http://server:port`, now it is `socks=server:port`. I am reverting it back to http for the time being.

**Comment by XyHK-HUC** [comment]
是的，我记错了版本号，DNS泄露问题应该出现在4.2.6，但是现在的4.2.7是代理之后无法访问网页了 @Mahdi-zarei

**Comment by Mahdi-zarei** [comment]
> Yes, I misremembered the version number. The DNS leak problem should have appeared in 4.2.6, but now in 4.2.7, the web page cannot be accessed after proxying. @Mahdi-zarei

Could be caused by the dns resolution issue, wait for the next release.

**Comment by Mahdi-zarei** [comment]
try 4.2.8

**Comment by Restia-Ashbell** [comment]
> This is most likely due to sing-box changes, inside the brackets should be the user ( as in username of http or socks auth ) which is out of context here and thus empty.
> 
> This whole situation though could be due to the change in the format of proxy, previously it was `http://server:port`, now it is `socks=server:port`. I am reverting it back to http for the time being.

I recently discovered that this issue occurs because the Windows system proxy sets SOCKS4 through the "socks=" configuration. Since SOCKS4 does not support domain name transmission, applications using the system proxy will resolve domain names locally.
