### ISSUE TITLE
Question: UDP traffic

### ISSUE THREAD

**Issue by To-Azamat** [Mahdi-zarei/nekoray#237]
Good day!
When UDP traffic is being forwarded from client to proxy server, does it still travels unencrypted or IP-encapsulated and encrypted?

**Comment by Mahdi-zarei** [comment]
Depends on your proxy configuration, but if your proxy config tunnels UDP as well, it will also encrypt it in almost all cases.

**Comment by To-Azamat** [comment]
Thank you for reply!
I am talking Vless-reality config. Plan to route all dns traffic through it to avoid isp tracking.

**Comment by Mahdi-zarei** [comment]
Yes, if you use xudp it will tunnel and encrypt your udp traffic as well.

**Comment by To-Azamat** [comment]
You mean in flow settings? I need to choose xtls-vision-udp443, not just xtls-vision?

**Comment by Mahdi-zarei** [comment]
I am talking about the packet encoding settings, which should be xudp by default, and so all should be good for tunneling udp.

**Comment by To-Azamat** [comment]
Can you please point me the direction where I can confirm the settings?

**Comment by Mahdi-zarei** [comment]
open your the profile editor and the packet encoding should not be blank.
![image](https://github.com/user-attachments/assets/247f38ab-2653-4243-9cce-793390ce812b)

**Comment by To-Azamat** [comment]
Found it, thank you!
I suppose this setting is server-independent, I just set it in client?

**Comment by To-Azamat** [comment]
And also in my setup it was blank by default. Does it mean xudp on or off by default?

**Comment by Mahdi-zarei** [comment]
as far as I'm aware sing-box server supports everything, don't know about xray. So if you are using a sing-box server then yes, only client matters.

**Comment by Mahdi-zarei** [comment]
> And also in my setup it was blank by default. Does it mean xudp on or off by default?

it was off most likely because of the URL provided or because the version of nekoray was old.

**Comment by To-Azamat** [comment]
So I will force-enable it then. Thank you a lot for the help!
