### ISSUE TITLE
TLS fragment

### ISSUE THREAD

**Issue by advancecf** [Mahdi-zarei/nekoray#24]
Hi

Can you change sing-box base package from sagernet to https://github.com/kyochikuto/sing-box-plus to support TLShello fragment for compile nekobox core to use this feature as custom outbound?

**Comment by Mahdi-zarei** [comment]
Hi
I'm afraid not, for the time being my main focus will be to improve nekoray as a GUI for sing-box, features outside of sing-box need to wait until the project is in a better state. I can suggest hiddify's Desktop client as it uses a custom sing-box core with the TLS Fragment capability.
