### ISSUE TITLE
Please support the SSR protocol, or support the SSR protocol through plug-ins, thank you.

### ISSUE THREAD

**Issue by skyenq** [Mahdi-zarei/nekoray#25]
Please support the SSR protocol, or support the SSR protocol through plug-ins, thank you.

Although the SSR protocol is old, it is still necessary to support it.

**Comment by Mahdi-zarei** [comment]
Sing-box currently has removed SSR from its supported protocols, and I don't know any plugins supporting it as SSR is practically abandoned. If you know any plugins I suggest you run it manually and use nekoray to tunnel the whole device through it.
