### ISSUE TITLE
Singbox 1.9.3 torrent sniffing

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#26]
Hi,

Not to be pushy ... 
But singbox 1.9.3 has added torrent sniffing ability, is there anyway to push and use it to next release?
https://github.com/SagerNet/sing-box/compare/v1.9.3...dev-next

Thanks for your awesome fork.

**Comment by Mahdi-zarei** [comment]
Hello, it is already under development. It will soon be released.
