### ISSUE TITLE
Landing proxy for Groups

### ISSUE THREAD

**Issue by Surfboardv2ray** [Mahdi-zarei/nekoray#3]
## Description suggestions
Under Preferences -> Groups, there's already the "Front Proxy" options which allows chaining for an entire group from a single proxy.

## Necessity of recommendations
Just like [NekoBoxForAndroid](https://github.com/MatsuriDayo/NekoBoxForAndroid) which offers [Landing Proxy](https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/595ed091f933a5359756d08c0ab4ff85f874b8fa/app/src/main/java/io/nekohasekai/sagernet/ui/GroupSettingsActivity.kt#L114) to route the traffic of an entire group to a single proxy instead, would be nice to have the feature in the desktop client as well.

**Comment by Mahdi-zarei** [comment]
I will try to add this feature, but it might take some time as my priority is to catch up with sing-box's newly added features, other features should wait for now.
