### ISSUE TITLE
BUG: DNS rule error (4.0.7)

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#32]
## Describe the problem

Default rule set gives DNS rule error

Expected behavior is to start without adding/editing rule sets.

## How to reproduce

Unpack the zip file add a proxy config and start, it should connect but gives this error:

`create service: parse route options: parse dns rule[0]: missing conditions 
`

Rule set json shows:

```
{
    "outbound": "dns_out",
    "protocol": "dns"
}
```

**Comment by Mahdi-zarei** [comment]
Try 4.0.8-beta.1.

**Comment by papampi** [comment]
Fixed in [4.0.8-beta.1](https://github.com/Mahdi-zarei/nekoray/releases/tag/4.0.8-beta.1)
