### ISSUE TITLE
Please bring back old route

### ISSUE THREAD

**Issue by EbadiDev** [Mahdi-zarei/nekoray#33]
I have been copying and pasting a JSON code all the time in route options, but due to the latest update, I am unable to edit the JSON file for routing purposes. Please allow us to directly edit the JSON file again.

**Comment by papampi** [comment]
Old routing rules are deprecated and will be removed from singbox soon, better adopt to new rules faster.
It's much easier when you get used to them.

**Comment by EbadiDev** [comment]
I was referring to the custom Route, for which it was to edit the JSON file.

**Comment by Mahdi-zarei** [comment]
An option to import a Json Array containing rule objects could be useful I assume. Will try to include it in the next release. But also note that the geoIP and geoSite rules are no longer supported and you need to use rule-sets, and to fix some ambiguity in the names, the names needed for rule-sets are formatted as name_IP or name_SITE depending on whether it's an ip or site rule-set.

**Comment by clift190** [comment]
请直接在设置里定义好“全局”和“绕过大陆”两组路由选项就好，方便小白使用，谢谢！

**Comment by Mahdi-zarei** [comment]
> 请直接在设置里定义好“全局”和“绕过大陆”两组路由选项就好，方便小白使用，谢谢！

我们将添加更多默认配置，以方便进行轻松设置。

**Comment by ndsphonemy** [comment]
> I was referring to the custom Route, for which it was to edit the JSON file.
I accede to the request to bring back the json editor of custom routes.
I had all routes were custom and now after the update I can't edit them in any way.
