### ISSUE TITLE
Small issue when migrating from the legacy nekoray with xray core to this one

### ISSUE THREAD

**Issue by amirhakimnejad** [Mahdi-zarei/nekoray#34]
There's an issue when migrating from the main repo to this one.
If you have chosen Xray-core before, this client fails to start because of the unsupported core settings; it should be recovered to the main core, I suppose.

**Comment by papampi** [comment]
Have you tried to switch from xray to singbox in your old setup then switch to this repo?

**Comment by amirhakimnejad** [comment]
> Have you tried to switch from xray to singbox in your old setup then switch to this repo?

Yes it works. Also changing value of this file to `0` would work, too.
like this: 
`echo "0" > ~/Library/Preferences/nekoray/config/groups/coreType`

Though I meant an automatic way for end users.
