### ISSUE TITLE
[FR]:  Add default start profile if no profile running on last exit

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#36]
## Describe the Feature

If for whatever reason nekoray crash or stops the proxy and you restart it via command or app menus it won't automatically connect to last profile since it was stopped when exited.

Adding a default startup profile if it was not running at last run will make it auto connect to that profile even if it crash and start/restart by a auto start script or system restart.

**Comment by Mahdi-zarei** [comment]
I'm not sure about this, a default profile might be deleted and then the feature won't work again. Also crashes should be rare and should not generally affect user experience and thus should not need a workaround.

**Comment by papampi** [comment]
I had some crashes on matsuri nekoray which had to manually start the profile again, 

I've had the crash once on 4.0.6, warning for another profile is starting after singbox core crashed and nekoray was trying to restart the profile which it maybe same issue as TUN busy.
