### ISSUE TITLE
create service: outbound not found for rule[0]: dns-out

### ISSUE THREAD

**Issue by iamfarhad** [Mahdi-zarei/nekoray#37]
not connect

[[VLESS] v2rayroad] test error: create service: outbound not found for rule[0]: dns-out
[[VLESS] v2rayroad] test error: create service: outbound not found for rule[0]: dns-out
[[VLESS] v2rayroad] test error: create service: outbound not found for rule[0]: dns-out

**Comment by papampi** [comment]
Have you Tried to set `Override Underlying DNS`  in core> core options?

**Comment by iamfarhad** [comment]
> Have you Tried to set `Override Underlying DNS` in core> core options?

no i did not something, just run program and copy paste xray vless

**Comment by Mahdi-zarei** [comment]
> I can connect but URL test failed. error: `test error: create service: outbound not found for rule[0]: dns-out`
> 
> > Have you Tried to set Override Underlying DNS in core> core options?
> 
> I've set it to https://8.8.8.8/dns-query and local or localhost but no difference.

There is a slight bug with testing configurations. Will be fixed in the next release.

**Comment by Mahdi-zarei** [comment]
try 4.0.8-beta.2
