### ISSUE TITLE
BUG: Error when add any process names

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#38]
## Describe the problem
Adding any `process name` or `process path` brings up lots of errors like this:

`INFO[0022] [3350596593 2ms] router: failed to search process: netlink message: NLMSG_ERROR
`

**Comment by Mahdi-zarei** [comment]
You need to refer to sing-box's documentation on these fields for this matter.

**Comment by papampi** [comment]
Posted in sing-box issues, let's see how it goes.
