### ISSUE TITLE
BUG: Routing - Outbound: proxy throws Invalid state

### ISSUE THREAD

**Issue by midncircus** [Mahdi-zarei/nekoray#39]
Not possible to direct globally and proxy a certain app.

Whenever I choose Outbound: proxy it gives an error and doesn't update the resulting rule.

![2024-06-16_150734](https://github.com/Mahdi-zarei/nekoray/assets/171871443/35858baf-deae-4ab4-a5b8-db29ad76a33a)

**Comment by Mahdi-zarei** [comment]
try 4.0.8-beta.2
