### ISSUE TITLE
BUG: how to fix unknown core error after update to to this version

### ISSUE THREAD

**Issue by javad490** [Mahdi-zarei/nekoray#4]
## Describe the problem
after update version 3.26 portable to version 4 portable, and run nekoray.exe system popup unknown core and close
##how to fix it:
To fix the unknown core error when updating the previous version 3.26 portable to version 4 portable
First, run version 4 once
Then close the program completely
Then copy all files and folders of version 4 to the previous version
Now run the updated program to see the previous configurations without errors

**Comment by mahdiyari** [comment]
"Unkown coreType" error on linux using both appImage and .deb package. Fixed by using the .zip file.

**Comment by Mahdi-zarei** [comment]
> "Unkown coreType" error on linux using both appImage and .deb package. Fixed by using the .zip file.

Were you using Xray core before?

**Comment by mahdiyari** [comment]
It was on sing-box with the original nekoray as that was the only one that tun mode worked. On another note, tt seems the proxy check box doesn't work with this version. I also had troubles with tun mode. I don't think I could make it work at all. Using Kubuntu 22.

**Comment by Mahdi-zarei** [comment]
> It was on sing-box with the original nekoray as that was the only one that tun mode worked. On another note, it seems the proxy check box doesn't work with this version. I also had troubles with tun mode. I don't think I could make it work at all. Using Kubuntu 22.

Please check your proxy env when system proxy is active and see if it points to nekoray's socks port. Also please open another issue if there are problems with the Tun mode or System Proxy.

**Comment by amirhakimnejad** [comment]
I mistakenly opened a duplicated issue. There's an easy fix here:
https://github.com/Mahdi-zarei/nekoray/issues/34#issuecomment-2171362774

**Comment by amirhakimnejad** [comment]
I think I mistakenly opened a duplicated issue here:
https://github.com/Mahdi-zarei/nekoray/issues/34
The fix for mac is this:
https://github.com/Mahdi-zarei/nekoray/issues/34#issuecomment-2171362774

Though you can find and delete coreType file using this option:
<img width="229" alt="image" src="https://github.com/Mahdi-zarei/nekoray/assets/30291162/c59da30f-db4c-4b63-b775-ac511d14e3b2">
The file is under config/groups folder
