### ISSUE TITLE
BUG: Later Pre-release version suggest updating to older Stable one.

### ISSUE THREAD

**Issue by midncircus** [Mahdi-zarei/nekoray#40]
Definetly not a big deal, but it confused me for the first time I encountered it.

Expected behavior: Pre-release version suggests updating to newer Pre-release or to Stable only if it's newer.

Actual behavior: 4.0.7 Pre-release found an update to 4.0.6 Stable.

![2024-06-16_171349](https://github.com/Mahdi-zarei/nekoray/assets/171871443/4e1a9c2a-b8cf-41ec-b510-e30a7dac42af)

**Comment by Mahdi-zarei** [comment]
Fixed in 4.0.8-beta.2.
