### ISSUE TITLE
BUG: when you open the route window, it's impossible to work because the button sizes are massive

### ISSUE THREAD

**Issue by rdbox** [Mahdi-zarei/nekoray#43]
![image](https://github.com/Mahdi-zarei/nekoray/assets/18515862/15d2a2b0-cfce-4360-ba2d-cb6fee5628f8)
![T3XnyV](https://github.com/Mahdi-zarei/nekoray/assets/18515862/ea6d02bd-a135-48d3-ac9a-0147f81bbedc)

I do not understand how this happens when you open a window it fills the entire working area some broken GUI Can not do anything buttons the size of a soccer stadium and not infinite they can not be reduced in any way when trying to reduce the window disappears some serious bug in the GUI operating system Windows 10

**Comment by rdbox** [comment]
> Are you using any specific settings when running the app? You are currently the only one facing this problem.

Figured it out, downloaded the archive again as everything is trivial.

And how to add an exclusion rule in the old version was just **domain:site.com**

I want to exclude all domains, what do I need to do?

![image](https://github.com/Mahdi-zarei/nekoray/assets/18515862/a32609cf-1665-4a34-a528-ec3c46e1bb63)

**Comment by Mahdi-zarei** [comment]
> And how to add an exclusion rule in the old version was just **domain:site.com**
> 
> I want to exclude all domains, what do I need to do?

For specific needs you need to refer to sing-box's docs, but to exclude a domain with all its subdomains I guess you need to use domain_suffix with the desired outbound (I suppose you want to use direct here).
