### ISSUE TITLE
BUG: 最新版的pr删除了绕过应用程式的gui了

### ISSUE THREAD

**Issue by Malus-risus** [Mahdi-zarei/nekoray#44]
## 描述问题

预期行为：能添加进程名字绕过软件

实际行为：找不到界面

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by Mahdi-zarei** [comment]
您需要使用新的路由选项，该选项可以让您充分利用 sing-box 的路由规则。

**Comment by clift190** [comment]
> 您需要使用新的路由选项，该选项可以让您充分利用 sing-box 的路由规则。

哪里有教程/例子啊？捣鼓半天总不对，自己增加的rule保存后总不见~~~
最好直接设置一个绕过大陆的rule

**Comment by Mahdi-zarei** [comment]
> > You need to use the new routing option, which allows you to take full advantage of sing-box's routing rules.
> 
> Where can I find a tutorial/example? I've been tinkering with it for a long time but it's always wrong. The rules I added always disappear after saving. It's better to directly set a rule that bypasses the mainland.

Try 4.0.8
