### ISSUE TITLE
Routing tutorials

### ISSUE THREAD

**Issue by M-Sadegh-M** [Mahdi-zarei/nekoray#45]
Hello
Thank you for updating the program.
Please add a wiki or tutorials for routing.
I used this [repo](https://github.com/bootmortis/iran-hosted-domains?tab=readme-ov-file#sing-box-core) to bypass Iranian sites.
Now, due to the change in the routing section, I don't know how to use routhing section.

Thank you

**Comment by papampi** [comment]
Use [Chocolate4U](https://github.com/Chocolate4U/Iran-sing-box-rules) Download geosite and geoip .db files and copy into nekoray folder. Restart nekoray so the db files get loaded.

In nekoray: "Routing Settings" > "Route" >  double click Default > "New" > "Set Name", "Attribute: "rule_set" >>>
Start typing rule names and it will be filtered in right pane, click on the rule you want and it will be added.

I think all the rest like domains, ip, .... are easy enough to figure out.

**Comment by Mahdi-zarei** [comment]
> Use [Chocolate4U](https://github.com/Chocolate4U/Iran-sing-box-rules) Download geosite and geoip .db files and copy into nekoray folder. Restart nekoray so the db files get loaded.

this practically should be unnecessary as they are shipped with the package.

> Please add a wiki or tutorials for routing.

I'm planning to do this, but either way for usages more complex than bypassing local IPs you will have to refer to sing-box's documentation as nekoray simply generates the rules and required assets and has no role in how they work.

**Comment by papampi** [comment]
> > Use [Chocolate4U](https://github.com/Chocolate4U/Iran-sing-box-rules) Download geosite and geoip .db files and copy into nekoray folder. Restart nekoray so the db files get loaded.
> 
> this practically should be unnecessary as they are shipped with the package.

If default added .db are from loyalsoldier or sing-box, they don't have complete Iran rules and miss a lot
That's why I suggested using Chocolate4U
Also noticed .dat files still exist in zip which has no use anymore.

**Comment by M-Sadegh-M** [comment]
> >
> I'm planning to do this
Thank you. Routing part needs to be simplified for normal users
It's very difficult to find rules in this section without search box.
![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/6f901336-37aa-41f1-bf9d-b9b897c2fc32)

**Comment by Mahdi-zarei** [comment]
> > > 
> > 
> > 
> > I'm planning to do this
> 
> Thank you. Routing part needs to be simplified for normal users It's very difficult to find rules in this section without search box. ![image](https://private-user-images.githubusercontent.com/124435580/341951568-6f901336-37aa-41f1-bf9d-b9b897c2fc32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDMzNTAsIm5iZiI6MTcxOTA0MzA1MCwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQxOTUxNTY4LTZmOTAxMzM2LTM3YWEtNDFmMS1iZjlkLWI5Yjg5N2MyZmMzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwNzU3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjU2MmQyOTdlYTE3NmJjOWQ2ZWIzZmUyYmE1ZTJiNzcwNWE4ZjUwMDAwZTk5MzllODlhNzhlZGYzNGIyZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mWz80XtyatqV6GfOG9uP0RUto2rAWT8Xp8qJxWUbN8U)

The right side text box is an auto complete section, you can type in the input box and it will show you suggestions which you can use, practically the input box could be considered a search box here.

**Comment by papampi** [comment]
> It's very difficult to find rules in this section without search box. 

Just start typing in middle pane and it filter out in right pane:
Then click on filtered ones, and they will be added.

 
![image](https://github.com/Mahdi-zarei/nekoray/assets/1108483/1e2bea16-f413-422e-a332-08dc3157a69c)

**Comment by M-Sadegh-M** [comment]
What's the different between "ir_site" and "category-ir_site"

**Comment by papampi** [comment]
> What's the different between "ir_site" and "category-ir_site"

I think ir_site are all Iranian sites while categor-ir are the iran access only

**Comment by M-Sadegh-M** [comment]
Based on the discussions and developer plans, I consider this issue closed.

Thank you

**Comment by M-Sadegh-M** [comment]
Sorry to reopen this issue

I have another question : Which one of these is used for single IP or domain?

![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/5aa24bcb-8980-47ee-912f-1b8c74c2a754)

**Comment by Mahdi-zarei** [comment]
> Sorry to reopen this issue
> 
> I have another question : Which one of these is used for single IP or domain?
> 
> ![image](https://private-user-images.githubusercontent.com/124435580/342041394-5aa24bcb-8980-47ee-912f-1b8c74c2a754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjY3MjUsIm5iZiI6MTcxOTEyNjQyNSwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQyMDQxMzk0LTVhYTI0YmNiLTg5ODAtNDdlZS05MTJmLTFiOGM3NGMyYTc1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzA3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTExMTExOWEyZTU4MWJlMTI1MTYyYTU3YWQwMzk5MTU0NTZlY2U3Y2ZhMjkyZTI5ZDdkMWYzZmMyZmVmYmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uq0weMS6vf1BTSSymdvaYUNo-_nSab8m3MseZ2FiBKU)

For a single ip, ip_cidr can be used like 192.168.1.1/32.
for a single domain, domain should be used with the desired domain as input.

**Comment by papampi** [comment]
Just make sure for domains+subdomains you should use domain_suffix if use domain sing-box only filter that domain and no subdomains.

**Comment by M-Sadegh-M** [comment]
for example 
![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/ac0fbafa-8991-4aa3-bafd-a8668d88b59b)

but it's not working

![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/23b5f8dd-86c3-4907-b6b6-7ecc8146d9a1)
![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/b4b850b1-7443-4243-bbf5-8e0debcceec2)

**Comment by Mahdi-zarei** [comment]
> for example ![image](https://private-user-images.githubusercontent.com/124435580/342043399-ac0fbafa-8991-4aa3-bafd-a8668d88b59b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjgxNjEsIm5iZiI6MTcxOTEyNzg2MSwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQyMDQzMzk5LWFjMGZiYWZhLTg5OTEtNGFhMy1iYWZkLWE4NjY4ZDg4YjU5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmUwMjg5ZGM1NzFhYWMwNGE3NjZjM2VlYzU3MWVjNTE5ZWNjZTcwMGMwYjQ2NzUwZDRmZGE4MjQ4ZTk3NjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-u_0EfNem2WQnLahu2PXqIqQDWr2SHcdhPuEj59_fMs)
> 
> but it's not working
> 
> ![image](https://private-user-images.githubusercontent.com/124435580/342043467-23b5f8dd-86c3-4907-b6b6-7ecc8146d9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjgxNjEsIm5iZiI6MTcxOTEyNzg2MSwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQyMDQzNDY3LTIzYjVmOGRkLTg2YzMtNDkwNy1iNmI2LTdlY2M4MTQ2ZDlhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2Q4YmIyZWU3MWY0ZGRkNWYxOWE2MzljNTVmMWM4ZDdjZTMxNWY5ZGY4MmU2N2M3ZmJmNzI0M2IxYTZlZGFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gf4sUqgjdx54VGJ4JMGeJApJyWjIaUlntkdwTnQbiUg) ![image](https://private-user-images.githubusercontent.com/124435580/342043719-b4b850b1-7443-4243-bbf5-8e0debcceec2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjgxNjEsIm5iZiI6MTcxOTEyNzg2MSwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQyMDQzNzE5LWI0Yjg1MGIxLTc0NDMtNDI0My1iYmY1LThlMGRlYmNjZWVjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTBlOTA3MGMwNWE4NDFjM2YwZjY4Y2Q2ZDdjMmFhMjRkZDU0ZGRkYjIxYTU3ZGQ1ZTQ4YjU1ZTIwMDZlNDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92HYhtU62-WdFguC5Xg35g-tlbbZQV69atbWU_RivTQ)

Because you are not visiting google.com or youtube.com, but www.google.com and www.youtube.com. Those 2 are different domains.

**Comment by M-Sadegh-M** [comment]
> > for example ![image](https://private-user-images.githubusercontent.com/124435580/342043399-ac0fbafa-8991-4aa3-bafd-a8668d88b59b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjgxNjEsIm5iZiI6MTcxOTEyNzg2MSwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQyMDQzMzk5LWFjMGZiYWZhLTg5OTEtNGFhMy1iYWZkLWE4NjY4ZDg4YjU5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmUwMjg5ZGM1NzFhYWMwNGE3NjZjM2VlYzU3MWVjNTE5ZWNjZTcwMGMwYjQ2NzUwZDRmZGE4MjQ4ZTk3NjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-u_0EfNem2WQnLahu2PXqIqQDWr2SHcdhPuEj59_fMs)
> > but it's not working
> > ![image](https://private-user-images.githubusercontent.com/124435580/342043467-23b5f8dd-86c3-4907-b6b6-7ecc8146d9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjgxNjEsIm5iZiI6MTcxOTEyNzg2MSwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQyMDQzNDY3LTIzYjVmOGRkLTg2YzMtNDkwNy1iNmI2LTdlY2M4MTQ2ZDlhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2Q4YmIyZWU3MWY0ZGRkNWYxOWE2MzljNTVmMWM4ZDdjZTMxNWY5ZGY4MmU2N2M3ZmJmNzI0M2IxYTZlZGFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gf4sUqgjdx54VGJ4JMGeJApJyWjIaUlntkdwTnQbiUg) ![image](https://private-user-images.githubusercontent.com/124435580/342043719-b4b850b1-7443-4243-bbf5-8e0debcceec2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjgxNjEsIm5iZiI6MTcxOTEyNzg2MSwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQyMDQzNzE5LWI0Yjg1MGIxLTc0NDMtNDI0My1iYmY1LThlMGRlYmNjZWVjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTBlOTA3MGMwNWE4NDFjM2YwZjY4Y2Q2ZDdjMmFhMjRkZDU0ZGRkYjIxYTU3ZGQ1ZTQ4YjU1ZTIwMDZlNDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92HYhtU62-WdFguC5Xg35g-tlbbZQV69atbWU_RivTQ)
> 
> Because you are not visiting google.com or youtube.com, but [www.google.com](http://www.google.com) and [www.youtube.com](http://www.youtube.com). Those 2 are different domains.

yes it's worked.
![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/e78cb453-3130-4093-9613-f5af3903c6ff)

Now, if you don't mind, one more question

How to direct private ranges 10.10 and 172

Thanks a lot

**Comment by papampi** [comment]
> but it's not working
> 
> ![image](https://private-user-images.githubusercontent.com/124435580/342043467-23b5f8dd-86c3-4907-b6b6-7ecc8146d9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjgzNzIsIm5iZiI6MTcxOTEyODA3MiwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQyMDQzNDY3LTIzYjVmOGRkLTg2YzMtNDkwNy1iNmI2LTdlY2M4MTQ2ZDlhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzM0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2EwNWFjZjhjM2M2YWRmNjJhZTNiMGFkZjZiYzdjMjJmNWQyYzZjNzYwNTUyYmI1MmVhY2JkMjg0YTI1NTI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lJ9G271z3RnVABzPoi3O47qmMMyQVK7WDGxFHbEjOts) ![image](https://private-user-images.githubusercontent.com/124435580/342043719-b4b850b1-7443-4243-bbf5-8e0debcceec2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjgzNzIsIm5iZiI6MTcxOTEyODA3MiwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQyMDQzNzE5LWI0Yjg1MGIxLTc0NDMtNDI0My1iYmY1LThlMGRlYmNjZWVjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzM0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzcxMDNlOGI2MThjZGJhZGYxNDAyOGIyY2NkYjg0NzBhM2I4NzMxNGMyZmE3NDFjYTViODRhM2FmY2U5ZjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WwUMEPMzJNfEsmUugje1zXhCXzCfkzUjdRptepVhxYo)

As @Mahdi-zarei said and I said earlier, www.google.com, abc.example.com, xyz.google.com,  ... are subdomains of google.com. You should use domain_suffix to include all.

**Comment by papampi** [comment]
> > Because you are not visiting google.com or youtube.com, but [www.google.com](http://www.google.com) and [www.youtube.com](http://www.youtube.com). Those 2 are different domains.
> 
> yes it's worked. ![image](https://private-user-images.githubusercontent.com/124435580/342045164-e78cb453-3130-4093-9613-f5af3903c6ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMjg1NjUsIm5iZiI6MTcxOTEyODI2NSwicGF0aCI6Ii8xMjQ0MzU1ODAvMzQyMDQ1MTY0LWU3OGNiNDUzLTMxMzAtNDA5My05NjEzLWY1YWYzOTAzYzZmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwNzM3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzQ2NWYzMThlNmM3OWMyYThjZTU2OWQzNTc2YzdlMzI4Y2QyOWNmMTE4MTI2NDQzZDdkYjQzODg3MTZmZTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kKXsNfi8sg-bGcJ2_CXJwe5I1bexTbRX45vNXvV6siE)
> 
> Now, if you don't mind, one more question
> 
> How to direct private ranges 10.10 and 172
> 
> Thanks a lot

Use a cidr calculator like https://www.ipaddressguide.com/cidr then add the desired range to ip_cidr

**Comment by M-Sadegh-M** [comment]
thanks a lot

**Comment by papampi** [comment]
Or just add Private_ip and Private_site in a rule_set

![image](https://github.com/Mahdi-zarei/nekoray/assets/1108483/b5225d17-3514-4627-b29b-7cd84d89c894)

**Comment by papampi** [comment]
@Mahdi-zarei 
I think this issue can be pinned until a tutorial gets ready.

**Comment by M-Sadegh-M** [comment]
> @Mahdi-zarei I think this issue can be pinned until a tutorial gets ready.

me too
It's a good Q&A for others  same questions

**Comment by papampi** [comment]
@Mahdi-zarei 
I just noticed there is a "ip_is_private" with "true" or "false" setting.
Do you know if it work the same as ip_cidr or private-ip rule sets?

**Comment by Mahdi-zarei** [comment]
> @Mahdi-zarei I just noticed there is a "ip_is_private" with "true" or "false" setting. Do you know if it work the same as ip_cidr or private-ip rule sets?

As far as I'm concerned it matches whether a destination IP is private, so I guess if the rule-set you are using is accurate it should have the same functionality, but since private IPs are predefined and do not change, the boolean flag should be a much better choice than rule sets. Also note that false does not match anything ( it does not mean ip is not private, it simply means the flag is non-existant if I'm not mistaken )

**Comment by papampi** [comment]
How to set process to bypass:

Preferences >> Routing setting >> Route >>  Double click the rule you are using (Default, Bypass Iran, ... )  >> New
Set name
Attribute: process_name or process_path 
Set outbound to direct 

Better move to as high as you want before getting blocked or ... 

![image](https://github.com/Mahdi-zarei/nekoray/assets/1108483/89d8e552-80c4-4458-9c53-9d6080e45d19)

**Comment by papampi** [comment]
@Mahdi-zarei 
Can you please explain how the new inbound rule works?

**Comment by Mahdi-zarei** [comment]
There is an option in the settings that allows for defining custom inbounds. If used, then you can use the inbound rules to route them as needed. I had not noticed that option exists until some time ago, and I think it will rarely be needed, but anyways for the sake of completeness I also added the inbound rule condition.
