### ISSUE TITLE
The latest version 4.0.1 for Windows shows the sing-box kernel as 1.9.0-rc.14, but not the updated 1.9.0-rc.15

### ISSUE THREAD

**Issue by ndsphonemy** [Mahdi-zarei/nekoray#5]
## Describe the problem

The latest version 4.0.1 for Windows shows the sing-box kernel as 1.9.0-rc.14, but not the updated 1.9.0-rc.15

## How to reproduce

![image](https://github.com/Mahdi-zarei/nekoray/assets/145504694/97a96004-9d4e-4ddc-83ef-5dd591f89a74)

**Comment by Mahdi-zarei** [comment]
The sing-box core is updated to the said version, I forgot to update the version number and this is practically a visual bug. Will be fixed in the next release.

**Comment by ndsphonemy** [comment]
> The sing-box core is updated to the said version, I forgot to update the version number and this is practically a visual bug. Will be fixed in the next release.
Ok, thanks for the quick reply.
