### ISSUE TITLE
Question: whitelist 

### ISSUE THREAD

**Issue by RezaRezapour** [Mahdi-zarei/nekoray#54]
how can i set a whitelist in routing setting
in main rep i can do it by Routing Settieng >> simple Route

**Comment by Mahdi-zarei** [comment]
If by whitelist you mean to not use the proxy for certain IPs or domains, then you can create a new rule and set the outbound to direct. If you mean you want to only use the proxy for certain scenarios, then you can set the Default outbound to direct and add the desirable rules.
