### ISSUE TITLE
outbound not found for rule[0]: dns-out

### ISSUE THREAD

**Issue by emadtoranji** [Mahdi-zarei/nekoray#55]
سلام دوست عزیز وقتتون بخیر

من از پنل علیرضا استفاده میکنم و لینک های اتصال رو وقتی داخل برنامه (MatsuriDayo) Nekoray که از هسته xray استفاده میکنه اضافه میکنم متصل میشه. اما وقتی داخل برنامه شما لینک هارو اضافه میکنم به اررور زیر میخورم:
`test error: create service: outbound not found for rule[0]: dns-out `

میخواستم بدونم مبدا مشکل از کجاست؟

باتشکر از شما

**Comment by Mahdi-zarei** [comment]
سلام وقت بخیر
چه ورژنی رو استفاده میکنید؟

**Comment by emadtoranji** [comment]
پنل علیرضا: ١.٨.۴

برنامه شما: ۴.٠.٧ و  ۴.٠.٨Dev2 رو تست کردم هردو همین اررور رو میده.

**Comment by Mahdi-zarei** [comment]
این باگی که میفرمایید توی نسخه 
4.0.8-beta.2
حل شده.

**Comment by emadtoranji** [comment]
داخل خود برنامه Update رو زدم، وقتی روی ok کلیک میکردم که برنامه رو ببنده و نسخه جدید رو نصب بکنه اتفاقی نمی‌افتاد و فقط برنامه بسته میشد.

به صورت دستی مجدد دانلود و جایگزین کردم اما همچنان مشکل پابرجا بود.

**Comment by Mahdi-zarei** [comment]
با چه روشی جایگزین کردید؟ من خودم تست کردم و این مشکل به وجود نیومد.

**Comment by emadtoranji** [comment]
الان نسخه 4.0.8 (2024-06-29) رو تست کردم ارروری نداد و تونستم انتخاب بکنم و Tun Mode رو روشن کنم اما اتصال برقرار نمیشه :(

اینکه پنل علیرضا از هسته xray استفاده میکنه ممکنه مربوط باشه؟ یا ربطی نداره؟

**Comment by Mahdi-zarei** [comment]
ارتباط مستقیمی ندارن این دو مورد. باید mux خاموش باشه سمت کلاینت فقط.

**Comment by emadtoranji** [comment]
خاموشه اما بازم وصل نمیشه. عجیبه.
