### ISSUE TITLE
BUG: Auto Update not works anymore

### ISSUE THREAD

**Issue by AkramiPro** [Mahdi-zarei/nekoray#57]
After click on `yes` in restart program popup, program closed but nothing happened after long time.
I check it just download the `nekoray.zip` and break in unzip process.

**Comment by Mahdi-zarei** [comment]
It seems that the update functionality has been broken, for now please update the app manually, all of the nekoray's app data is inside the config folder, so simply extract the new version of nekoray and copy the config folder from the old installation dir to the new directory.

**Comment by papampi** [comment]
> After click on `yes` in restart program popup, program closed but nothing happened after long time. I check it just download the `nekoray.zip` and break in unzip process.

Delete zip file, click update again, unzip it, copy/replace content of extracted zip.

**Comment by Mahdi-zarei** [comment]
should be Fixed in 4.0.9
