### ISSUE TITLE
路由导入修改

### ISSUE THREAD

**Issue by ccddos** [Mahdi-zarei/nekoray#58]
## Description suggestions
目前自定义路由只支持如图属性，对于其他sing-box docs中存在的属性 既无法通过import导入，也无法直接edit

比如我想根据inbound tag进行分流控制，就无法实现

![image](https://github.com/Mahdi-zarei/nekoray/assets/135016091/496d44ea-c2c6-4a46-990d-0ce6cc14ac83)

## Necessity of recommendations
import json的时候取消自动修改属性条目，允许自定义条目, 或者补充完整editor

![image](https://github.com/Mahdi-zarei/nekoray/assets/135016091/8ff89fe1-12b9-4a6f-a9af-e40f21612e54)

**Comment by Mahdi-zarei** [comment]
我不明白，nekoray 会创建 mixed-in 并且在开启 Tun 模式的情况下会创建一个 tun-in，但不允许自定义 inbound。如果您无法创建自己的 inbound，那么根据 inbound 标签进行路由如何能够起到作用呢？ (Wǒ bù míngbái, nekoray huì chuàngjiàn mixed-in bìngqiě zài kāiqí Tun móshì de qíngkuàng xià huì chuàngjiàn yīgè tun-in, dàn bù yǔnxú zìdìngyì inbound. Rúguǒ nín wúfǎ chuàngjiàn zìjǐ de inbound, nàme cănjù inbound biāoqīán jìnxíng lúyóu rúhé nénggòu qídào zuòyòng ne?)

**Comment by ccddos** [comment]
> 我不明白，nekoray 会创建 mixed-in 并且在开启 Tun 模式的情况下会创建一个 tun-in，但不允许自定义 inbound。如果您无法创建自己的 inbound，那么根据 inbound 标签进行路由如何能够起到作用呢？ (Wǒ bù míngbái, nekoray huì chuàngjiàn mixed-in bìngqiě zài kāiqí Tun móshì de qíngkuàng xià huì chuàngjiàn yīgè tun-in, dàn bù yǔnxú zìdìngyì inbound. Rúguǒ nín wúfǎ chuàngjiàn zìjǐ de inbound, nàme cănjù inbound biāoqīán jìnxíng lúyóu rúhé nénggòu qídào zuòyòng ne?)

It can be done by customize inbound , like the image show

So I think my request is reasonable

![image](https://github.com/Mahdi-zarei/nekoray/assets/135016091/278bbd8d-9142-4a38-ad55-9068f3cbc442)

**Comment by Mahdi-zarei** [comment]
那很有意思，我并不知道我们有那个选项 . 的确，既然您可以添加自己的 inbound，那么基于 inbound 进行路由是合理的。我将添加路由选项。

**Comment by Mahdi-zarei** [comment]
Try 4.0.9.
