### ISSUE TITLE
BUG: مشکل در رابط کاربری و تم برنامه

### ISSUE THREAD

**Issue by M-Sadegh-M** [Mahdi-zarei/nekoray#60]
سلام وقت بخیر
تشکر بابت رفع مشکلات در اپدیت قبلی
در نسخه اخر 4.0.8 وقتی تم را به ویستا تغییر میدم منوها درست نشون داده نمیشه
![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/8578c4ba-81ab-4f02-855f-247650392cc5)

![Untitled](https://github.com/Mahdi-zarei/nekoray/assets/124435580/e84a6c29-053c-47e0-9b4c-44b02a039954)

![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/4034cfae-5bd1-463a-9a68-5c2b86240c99)

**Comment by Mahdi-zarei** [comment]
سلام وقت بخیر
تم ویندوز ویستا از تم های خود Qt هست و مشکلاتش قابل رفع نیست، توی ریلیز بعدی تم حذف میشه با توجه به مشکلاتی که داره.

**Comment by M-Sadegh-M** [comment]
تشکر از شما
اگه حذف میشه به خاطر مشکلات پایه ای مساله ای نیست ولی تم جدید مشکلات زیادی داره که امیدوارم به مرور حلش کنید
مثالش در عکس زیر اصلا خوانا و مشخص نیست کدوم بخش ها غیرفعال هست و نمیشه ادیت کرد ولی در همون تم ویستا کامل مشخصه

![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/d929f43d-e079-4ea6-be88-c2ca183c9612)

![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/5e4b8c41-e56f-42d8-803e-be010f98dcf5)

یا مثلا خط و خطوط اضافه کادر ها در منوها را ببنید و مقایسه کنید با همون تم ویستا

![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/b3c3c872-0718-4ee8-a931-8474b6618836)

![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/3072c342-1b44-4abf-b810-879498a9d0e8)

**Comment by Mahdi-zarei** [comment]
خیلی عجیب هست این موارد، کل تم های استفاده شده تم های دیفالت خود Qt هست و عملا من امکان تغییرشون رو ندارم به سادگی. سیستم عاملتون چی هست؟ بجز تم ویستا تم دیگه ای نیست که مشکلی نداشته باشه؟

**Comment by M-Sadegh-M** [comment]
> خیلی عجیب هست این موارد، کل تم های استفاده شده تم های دیفالت خود Qt هست و عملا من امکان تغییرشون رو ندارم به سادگی. سیستم عاملتون چی هست؟ بجز تم ویستا تم دیگه ای نیست که مشکلی نداشته باشه؟

ویندوز 11 هست اخرین اپدیت و نسخه
مشکلی که به خاطرش تاپیک را باز کردم اگه یکبار نرم افزار را از کنار ساعت باز کنم ببندم حل میشه
تم دیفالت مشکلی در نمایش گزینه ها نداره و همه چیز مشخصه ولی مشکلاتی مثل موارد بالا از جهت مشخص نبودن گزینه های فعال و یا خط و خطوط اضافی خیلی داره

یا مثل موارد زیر که کانفیگی که فعال هست اصلا رنگش تغییر نمیکنه یا پینگ سرور با رنگ دیگه نیست و مواردی که ساده میاد و در تم قدیمی بود و به خوانایی و UX خیلی کمک میکرد

![image](https://github.com/Mahdi-zarei/nekoray/assets/124435580/67ca8c8b-be7a-4ade-a56c-fb5b62d1208f)

**Comment by Mahdi-zarei** [comment]
بنظر یک سری مشکلات دارن تم های فعلی، توی ریلیز بعدی سعی بر برطرف کردنشون میشه.

**Comment by Mahdi-zarei** [comment]
> یا مثل موارد زیر که کانفیگی که فعال هست اصلا رنگش تغییر نمیکنه یا پینگ سرور با رنگ دیگه نیست و مواردی که ساده میاد و در تم قدیمی بود و به خوانایی و UX خیلی کمک میکرد

تغییر رنگ ها توی یکسری تم ها غیر فعال میشن، ولی توی تم fusion این مشکل وجود نداره و فعال هستن.
در مورد خرابی تم های اعمال شده هم عملا تنها راه فعلا ریستارت برنامه هست، مشکلات تم از سمت Qt هست و تنها راه دور زدنش هم استفاده از تم کاستوم هست که فعلا امکانش نیست عملا.

**Comment by M-Sadegh-M** [comment]
از همون تم ویستا استفاده می‌کنم ومشکلی نداره
مشکلش همون حالت بالا بود که دفعه اول که انتخاب میکردم اتفاق می افتاد الان مشکلی نداره.

خواستید ایشو را ببندید خواستید باز بگذارید.

تشکر از پیگیری

**Comment by Mahdi-zarei** [comment]
با توجه به اینکه مشکلات تم یه ایشو دیگه باز هست براش این رو میبندم.
