### ISSUE TITLE
BUG: The GUI does not respect the system wide dark theme on Linux

### ISSUE THREAD

**Issue by Turbine8845** [Mahdi-zarei/nekoray#61]
## Describe the problem
The GUI of nekoray does not respect the system wide dark theme applied to the Cinnamon desktop environment in Debian.
## Expected behavior:
The GUI must be shown using a dark theme instead of a light theme when a system wide dark theme is applied on Linux. The dark theme problem is not present on Windows.
## Actual behavior:
Nekoray is shown using a light theme instead of a dark theme when a system wide dark theme is applied on Linux.

![Nekoray Dark theme issue](https://github.com/Mahdi-zarei/nekoray/assets/166437392/0c292011-6dd1-462e-83f7-7e4cde17948f)

## How to reproduce
The problem can be created by applying a dark them on Linux and then opening the Nekoray's launcher.

**Comment by Mahdi-zarei** [comment]
I'm afraid this problem cannot be efficiently solved on my end, as the problem is caused by Qt's system theme handling on linux desktops and the only solution out there might be to use qt6ct.

**Comment by Mahdi-zarei** [comment]
Try QDarkStyle in 4.0.9. For the time being, this issue cannot be properly solved since the problem is rooted in Qt.
