### ISSUE TITLE
Difficulty in selecting the Landing and Fronting proxies and the discontinuation of providing the DEB files

### ISSUE THREAD

**Issue by Turbine8845** [Mahdi-zarei/nekoray#65]
Dear Mahdi,
Thank you for all bug fixes and the addition of new features to Nekoray. I have finally decided to completely migrate to your fork of Nekoray and ditch the original version. However, I have a problem with the new GUI elements for selecting Fronting and Landing proxies for Sub Groups in the forked version. I have a large number of Sub Links and proxies in Nekoray and it is really difficult with the new GUI to find and select a specific proxy as the Front/Landing proxy. Please consider implementing a search feature (or an alternative solution) for selecting Fronting/Landing proxies.
 
![Nekoray Front](https://github.com/Mahdi-zarei/nekoray/assets/166437392/db07379f-3000-4c30-9696-1291bf06a6ee)

Also, why the new release does not include the .deb files? The .deb files were really handy for people like me who use Linux. If you are planning to no longer provide the DEB files please kindly consider providing a comprehensive build guide for compiling nekoray for various operating systems as the build guide for the original version of Nekoray was all in Chinese and used an older version of Qt.

**Comment by Mahdi-zarei** [comment]
You can use the Zip file provided for linux, I will also try to find a way to add a search option for landing and front proxy.

**Comment by Mahdi-zarei** [comment]
Try 4.0.9 for searching through the Proxy list.
