### ISSUE TITLE
How can bypass some specific app in nekoray 

### ISSUE THREAD

**Issue by misagh72** [Mahdi-zarei/nekoray#69]
in original nekoray in the tun mode you can add process name to bypass vpn 
but in this version got removed 
how can i add specific app.exe to this nekoray

**Comment by papampi** [comment]
Preferences >> Routing setting >> Route >>  Double click the rule you are using (Default, Bypass Iran, ... )  >> New
Set name, Attribute process_name or process_path set outbound to direct 

Better move to as high as you want before getting blocked or ... 

![image](https://github.com/Mahdi-zarei/nekoray/assets/1108483/89d8e552-80c4-4458-9c53-9d6080e45d19)

**Comment by papampi** [comment]
Also added to https://github.com/Mahdi-zarei/nekoray/issues/45 
You can check it for otherrouting rules.
