### ISSUE TITLE
[FR] Update geosite, geoip and srs files

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#70]
## Description suggestions
It would be nice to have an option to set geosite and geoip url's so users can click the icon to update the files.
It also needs to clean the srs files and restart the proxy so singbox regenerate .srs rule files so we can't have an auto update schedule option.

I have written a simple bash script for myself to download them, clean srs files and restart nekoray.

**Comment by M-Sadegh-M** [comment]
https://github.com/hiddify/hiddify-geo/tree/rule-set

I have no idea, but I thought this repo might be useful.

**Comment by papampi** [comment]
Added in [4.1.0](https://github.com/Mahdi-zarei/nekoray/releases/tag/4.1.0)
Thanks
