### ISSUE TITLE
[FR] Don't stop please ... 

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#71]
Hi,
Since the main Nekoray has woken up from long sleep you mentioned that you might stop working on this.

I just checked the new main beta and I should say its long behind yours in so many ways and yours is so much better.
Please don't stop this, maybe give it a new name and continue your awesome work.

**Comment by M-Sadegh-M** [comment]
Hello,

I believe your changes could be beneficial to the main project, so I suggest submitting PRs. It will likely be accepted and merged.

If it is merged, please continue to update and support the main project.

If @arm64v8a does not accept your PRs or you cannot reach an agreement, proceed as you see fit. You can either continue or cancel based on your judgment.

Regardless, we appreciate your efforts.

**Comment by Mahdi-zarei** [comment]
Hello, Thanks for the support!
I was also thinking about submitting PRs, but since many of the changes I made are kind of opinionated I doubt they will easily be merged, so for the time being I will most likely continue to work on this fork, but if the original repo adds enough functionalities to cover the necessary areas, I will most likely stop working on this fork as it was not my goal to compete for users, but to provide the necessary tools to have a properly configured proxy on Desktop platforms.

**Comment by M-Sadegh-M** [comment]
> Hello, Thanks for the support! I was also thinking about submitting PRs, but since many of the changes I made are kind of opinionated I doubt they will easily be merged, so for the time being I will most likely continue to work on this fork, but if the original repo adds enough functionalities to cover the necessary areas, I will most likely stop working on this fork as it was not my goal to compete for users, but to provide the necessary tools to have a properly configured proxy on Desktop platforms.

I think it’s worth a try. You can test it and see if it gets accepted or not. Collaborating on a project is more effective than working separately and parallel

**Comment by midncircus** [comment]
Totally agree. I filed 3 issues and all fixed very fast. Mahdi is a champ.

**Comment by SPIRIT-00** [comment]
Mahdi did great job, thanks a lot!

**Comment by Mahdi-zarei** [comment]
welp, seems that the original author does not like the idea of joining hands, so for the time being I will maintain my own fork, might also consider changing the name and removing the forked property and continue this project on its own, the same as Husi.

**Comment by papampi** [comment]
Denied without a single word ... just "Not planned" ... abrupt and  discourteous!!!
