### ISSUE TITLE
Appimage and deb packages

### ISSUE THREAD

**Issue by Sue1133** [Mahdi-zarei/nekoray#72]
Hello. Where did the appimage and deb packages go? Appimage was convenient and there was no need to have qt on the system, and deb packages simplified their installation.

Now I had to stop at 4.0.8-beta.2. I tried to install the latest 4.0.8 and did not understand why it was looking for qt packages from the system, although they are located in the same folder in the usr/lib/ directory.

**Comment by Mahdi-zarei** [comment]
Hello, If you use the launcher to run nekoray there will be no need for any additional changes to run the app.
In the future I will return appImage and deb package for more convenience, but for now there is no necessity.

**Comment by Sue1133** [comment]
Thank you, everything worked. I'll wait for appimage and deb.

Thank you for your work.

**Comment by vmkspv** [comment]
@Mahdi-zarei, are there any plans for Throne AppImage? Since version 1.0.0 has been released, this would simplify the transition from Nekoray AppImage.

**Comment by Mahdi-zarei** [comment]
Doesn't app image isolate an app and thus break nekoray's Tun mode?

**Comment by vmkspv** [comment]
> Doesn't app image isolate an app and thus break nekoray's Tun mode?

Yeah, it breaks Tun mode. But for those who use the app in proxy mode only, it's a nice way to distribute the binary.

**Comment by Mahdi-zarei** [comment]
What does it offer that the current zip distribution does not?

**Comment by vmkspv** [comment]
> What does it offer that the current zip distribution does not?

This makes installation much easier, without having to keep track of the many directories and files that are in the file system during zip-distribution. Additionally, AppImages make it easy to manage versions and perform clean uninstallation, which is important from a privacy perspective.

**Comment by Mahdi-zarei** [comment]
The zip release has all that it uses with it, and creates only a config folder inside its own dir, so practically there is nothing to keep track of and also removing the dir removes all things related to nekoray and is a clean uninstallation. There is really no benefit to providing an app image version that breaks one of the most useful features of nekoray, and brings in absolutely nothing, if app image is self contained, so is the zip release! It does not install anything or use any resources outside its own directory, much like the app image version.
