### ISSUE TITLE
BUG:مشکل در تست کانفیگ ها 

### ISSUE THREAD

**Issue by xQuantoM** [Mahdi-zarei/nekoray#73]
سلام و خسته نباشید
بنده وقتی میخوام تعداد زیادی کانفیگ تست کنم در وسط کار کل نرم افزار کرش میکنه مصرف رم به شدت بالا میره بنده فکر کردم شاید مشکل از دی ان اس برنامه باشه ولی تاثیر نداشت 
![Screenshot (3)](https://github.com/Mahdi-zarei/nekoray/assets/78085908/b50518c1-d8c1-4db9-872d-cb1ea255ada6)

**Comment by Mahdi-zarei** [comment]
سلام
من الان با یه گروه با +9000 تا کانفیگ رو url test گرفتم و مشکلی ایجاد نشد برام. لطفا مراحل دقیقتری که این مشکل رو بشه باهاش ایجاد کرد رو بفرست و اینکه test concurrency روی چه عددی بود؟ من با 500 و 200 تست کردم و مشکلی نبود. البته این عدد ها زیاد هستن و پیشنهادم اینه از 100 بیشتر نباشه این پارامتر.

**Comment by xQuantoM** [comment]
برای بنده دقیقا روی 100 بود بنده از این گروه استفاده میکنم
https://raw.githubusercontent.com/yebekhe/TVC/main/subscriptions/xray/normal/mix
و اگر مشکلی نیست امکانش هست لینک این گروه بفرستید یا چیز دیگه بتونم با اونا هم تست کنم؟

**Comment by Mahdi-zarei** [comment]
بعد از چند سری تست کرش داد و به نظر میرسه مشکل بخاطر استفاده نادرست از ترد های Qt هست و توی بعضی مواقع باعث میشه برنامه کرش کنه. در حال حاضر پیشنهادم اینه تعداد تست های موازی رو کم کنی تا احتمال اتفاق افتادنش کمتر بشه. سعی میکنم توی ریلیز بعدی مشکل رو رفع کنم.

**Comment by xQuantoM** [comment]
ممنونم از شما

**Comment by Mahdi-zarei** [comment]
ریلیز جدید رو تست کنید.

**Comment by xQuantoM** [comment]
بنده تست کردم و مشکل حل شده کرش نمیکنه ولی test concurrency میزارم 100 150 کانفیگ Unavailable میزنن یک جوری کانفیگ ها درست اسکن نمیشن اسکیپ میشن ولی وقتی test concurrency میزارم روی 10 5 خیلی از کانفیگ ها کار میکنن پینگ میدن

**Comment by Mahdi-zarei** [comment]
احتمال خوبی دلیل این اتفاق تعداد بالای کانفیگ هایی هست که استارت میشن، با توجه به اینکه نکوری برای هر کانفیگ یه ترد میسازه تعداد بالای ترد میتونه باعث کندی بشه و باعث بشه کانفیگ ها تایم اوت بشن، بهتره تعداد موازی بودن رو روی یه عدد پایین ست کرد. در حال حاضر نحوه انجام تست همون روشی هست که نسخه اصلی استفاده میکنه. در آپدیت های بعدی بخش تست رو در صورت امکان بهبود میدم.

**Comment by xQuantoM** [comment]
ممنونم ازتون بنده از کانفیگ های رایگان استفاده میکنم و تعداد اینا خیلی زیاده خیلی عالی میشه تست بهتر شه

**Comment by javad490** [comment]
منم در جدیدترین ورژن و ورژن های قبلی روی ویندوز 11 چنین مشکلی دارم که مثل در پینگ url test گرفتن از کانفیگ 100 تاِیی چند تا را که پینگ گرفت برنامه هنگ میکنه و میره بیرون و فایل nekobox_core.exe فشار پردازش سنگینی روی cpu میاره که باید از داخل task manager این فایل بسته بشه تا پردازش الکی قطع بشه

https://github.com/Mahdi-zarei/nekoray/issues/96#issue-2446239269

**Comment by javad490** [comment]
منم در جدیدترین ورژن و ورژن های قبلی روی ویندوز 11 چنین مشکلی دارم که مثل در پینگ url test گرفتن از کانفیگ 100 تاِیی چند تا را که پینگ گرفت برنامه هنگ میکنه و میره بیرون و فایل nekobox_core.exe فشار پردازش سنگینی روی cpu میاره که باید از داخل task manager این فایل بسته بشه تا پردازش الکی قطع بشه

https://github.com/Mahdi-zarei/nekoray/issues/96#issue-2446239269

**Comment by Mahdi-zarei** [comment]
یک بخشی از مشکل بخاطر شروع کردن تعداد زیادی کانفیگ هست که با کم کردن تعداد موازی زدن حل میشه
در کل ولی مشکل بهینه نبودن توی ریلیز جدید رفع خواهد شد.
البته برای موازی تست کردن باید پهنای باند رو هم در نظر داشت، تعداد موازی زدن ها زیاد باشه پهنای باند پر میشه و تایم اوت و پینگ بالا میگیرید.

**Comment by Mahdi-zarei** [comment]
ریلیز جدید رو تست کنید.

**Comment by xQuantoM** [comment]
![image](https://github.com/user-attachments/assets/b6bdaacb-4ed3-41b3-a126-245e9aae47b5)
به نظر میرسه که مشکل تست حل شده الان اگه کانفینگی با nekoray مشکلی نداشته باشه ساپورت بشه به طور کامل اسکن میشه ولی کانفیگ مثل splithttp که هنوز توی کور سینگ باکس نیست nekoray نمیتونه تشخیص بده کلا گروه دیگه تست نمیکنه لطفا جوری بشه که حتی اگه کانفینگی ساپورت نمیشه فقط اسکیپ بشه بزاره بقیه گروه اسکن بشه

**Comment by Mahdi-zarei** [comment]
ریلیز جدید رو تست کنید

**Comment by javad490** [comment]
> ریلیز جدید رو تست کنید

با تشکر، مشکل پردازش سنگین cpu هنگام url test کانفیگها در ویندوز 11 با آخرین ورژن برنامه برطرف شده.

مشکل جدید اینه که ظاهرا فعالبت برنامه توسط فیلترینگ شناسائی میشه و حدود 15 دقیقه پس از استفاده از کانفیگ ping میره بالا و دچار مکث و قطع و وصلی میشه..

همچنین داخل لاگ این خطاها مرتب به نمایش در میاد و تکرار میشه
![nekoray-fork-error2](https://github.com/user-attachments/assets/8d421587-4680-47ee-b8c8-78a8b12ac2e2)

**Comment by Mahdi-zarei** [comment]
> > ریلیز جدید رو تست کنید
> 
> با تشکر، مشکل پردازش سنگین cpu هنگام url test کانفیگها در ویندوز 11 با آخرین ورژن برنامه برطرف شده.
> 
> مشکل جدید اینه که ظاهرا فعالبت برنامه توسط فیلترینگ شناسائی میشه و حدود 15 دقیقه پس از استفاده از کانفیگ ping میره بالا و دچار مکث و قطع و وصلی میشه..
> 
> همچنین داخل لاگ این خطاها مرتب به نمایش در میاد و تکرار میشه ![nekoray-fork-error2](https://private-user-images.githubusercontent.com/123890771/358854689-8d421587-4680-47ee-b8c8-78a8b12ac2e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDk1MDcsIm5iZiI6MTcyMzkwOTIwNywicGF0aCI6Ii8xMjM4OTA3NzEvMzU4ODU0Njg5LThkNDIxNTg3LTQ2ODAtNDdlZS1iOGM4LTc4YThiMTJhYzJlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxNTQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmM4M2MxZDZjZTUwMTZkODNjYzZhNjhiZGQzZDk0ZTcyZTk3YWI0N2E0NWYwNDlmYWRlNzFlYTYxODBkNThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f-ynURpXrznBvKcDBChfSaWCHbKJdYD4NGNkVHYivz0)

این مرتبط به نکوری نمیشه. مشکل یا بخاطر آپدیت شدن sing-box هست یا کانفیگ مشکل دار.

**Comment by javad490** [comment]
> > > ریلیز جدید رو تست کنید
> > 
> > 
> > با تشکر، مشکل پردازش سنگین cpu هنگام url test کانفیگها در ویندوز 11 با آخرین ورژن برنامه برطرف شده.
> > مشکل جدید اینه که ظاهرا فعالبت برنامه توسط فیلترینگ شناسائی میشه و حدود 15 دقیقه پس از استفاده از کانفیگ ping میره بالا و دچار مکث و قطع و وصلی میشه..
> > همچنین داخل لاگ این خطاها مرتب به نمایش در میاد و تکرار میشه ![nekoray-fork-error2](https://private-user-images.githubusercontent.com/123890771/358854689-8d421587-4680-47ee-b8c8-78a8b12ac2e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDk1MDcsIm5iZiI6MTcyMzkwOTIwNywicGF0aCI6Ii8xMjM4OTA3NzEvMzU4ODU0Njg5LThkNDIxNTg3LTQ2ODAtNDdlZS1iOGM4LTc4YThiMTJhYzJlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxNTQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmM4M2MxZDZjZTUwMTZkODNjYzZhNjhiZGQzZDk0ZTcyZTk3YWI0N2E0NWYwNDlmYWRlNzFlYTYxODBkNThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f-ynURpXrznBvKcDBChfSaWCHbKJdYD4NGNkVHYivz0)
> 
> این مرتبط به نکوری نمیشه. مشکل یا بخاطر آپدیت شدن sing-box هست یا کانفیگ مشکل دار.

کانفیگ سالمه و با v2rayN و هیدیفای بدون خطا کار میکنه

**Comment by xQuantoM** [comment]
مکشل به طور کامل حل شده تشکر فقط دیگه keybind برا بنده کار نمیکنه مشکل از بنده هست یا نه تو ابدیت جدید اینطوری شده
