### ISSUE TITLE
Kill-switch like feature

### ISSUE THREAD

**Issue by amirhakimnejad** [Mahdi-zarei/nekoray#74]
With Nekoray, I have experienced a lot of scenarios where, after an unsuccessful connection, my real IP is exposed. 
Is there a way to kill the internet(Like the killswitch feature in other softwares) to minimize IP exposure?

**Comment by Mahdi-zarei** [comment]
By kill the internet, do you mean to shut down nekoray, or to disconnect the whole device's connectivity?

**Comment by amirhakimnejad** [comment]
The latter, just like this in expressvpn 
<img width="557" alt="Screenshot 2024-07-03 at 11 59 57 AM" src="https://github.com/Mahdi-zarei/nekoray/assets/30291162/43c97ef3-b3ba-4e7b-a56b-760cbe2f2082">

**Comment by Mahdi-zarei** [comment]
Given how nekoray works, this might be rather difficult to implement. For the time being I'm focusing on improving current features and fixing bugs and don't want to add new functionalities, so it will have to wait until some time. by the way, as long as the core is running, you can achieve the effect using tun mode, but to fully disconnect a device when nekoray stops or crashes requires some effort.
