### ISSUE TITLE
BUG: حالت پروکسی و باز هم مشکل در اپدیت

### ISSUE THREAD

**Issue by M-Sadegh-M** [Mahdi-zarei/nekoray#77]
وقت بخیر
- مشکل اپدیت مستقیم در نرم افزار همچنان حل نشده
- حالت پروکسی فعال نمیشه و پیام زیر میاد

```
sing-box: 1.9.3
2024/07/10 06:23:00 nekobox_core grpc server listening at 127.0.0.1:14400
>>>>>>>> Starting profile [VLESS] Worker
INFO[0000] router: updated default interface Ethernet, index 16
INFO[0000] inbound/mixed[mixed-in]: tcp server started at [::]:2080
INFO[0000] sing-box started (0.11s)
grpc-status error code: 2 , error msg: InternetSetOption(PerConnectionOption): winapi error #12005
[Error] gRPC: QNetworkReply::NetworkError code: 301
Failed to set system proxy with error An invalid oplock acknowledgment was received by the system.
```
-  مورد گرافیکی زیر هم هست، کلمه کامل قرمز نیست

![Untitled](https://github.com/Mahdi-zarei/nekoray/assets/124435580/fb65e950-c9d4-4e0d-bfd2-d83ce31d60e9)

**Comment by Mahdi-zarei** [comment]
وقت بخیر
طبیعتا از ورژن قبلی نمیتونید به ورژن جدید آپدیت کنید چون مشکل آپدیت در این ورژن حل شده و برای ورژن های بعدتر قابل استفاده هست.
مورد دوم بخاطر ست کردن گزینه allow other devices to connect هست، نسخه رو مجددا ریلیز میکنم تا حل شه مشکل، دوباره تست کنید بعد از ریلیز مجدد.

**Comment by Mahdi-zarei** [comment]
مشکل دوم و سوم حل شد، تست کنید.
مشکل اول هم که عملا مربوط به نسخه قبلی هست.

**Comment by M-Sadegh-M** [comment]
بله همگی برطرف شدند
