### ISSUE TITLE
BUG: Unusual large Tun settings window

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#78]
When open Tun settings it opens with old large size, while it can be smaller now that it doesnt have the rules sections anymore

![image](https://github.com/Mahdi-zarei/nekoray/assets/1108483/9e7f5758-e9a6-4cad-af17-4bcf124e5d88)

Its prettier if launch with minimum height needed:

![image](https://github.com/Mahdi-zarei/nekoray/assets/1108483/4c8b89db-5a64-4d6b-bb8c-d34c0d2774a9)

**Comment by M-Sadegh-M** [comment]
The window size is correct for me

![Untitled](https://github.com/Mahdi-zarei/nekoray/assets/124435580/a2781dd7-b123-47ba-b488-48128c53c239)

**Comment by M-Sadegh-M** [comment]
> Then maybe a Linux decoration problem, you running it on linux? Tried on ubuntu 22.04 and 24.04 , both shows the same for me.
no, run on win 11

**Comment by Mahdi-zarei** [comment]
The problem might be caused by the GSO button, will try to look into it for the next release.

**Comment by ndsphonemy** [comment]
This is because one of your proxy servers has a very long name.

**Comment by Mahdi-zarei** [comment]
try 4.0.10

**Comment by Sue1133** [comment]
I just checked, the window is normal size, thanks.

**Comment by papampi** [comment]
All good, Tun is fixed, update is fixed , ...
