### ISSUE TITLE
BUG: create service: parse route options: parse dns rule[0]: missing conditions

### ISSUE THREAD

**Issue by Sue1133** [Mahdi-zarei/nekoray#79]
![bug](https://github.com/Mahdi-zarei/nekoray/assets/174503310/0a802407-9d2a-4feb-abb4-1b48b4c9e88e)
When connecting to shadowsocks this error appears, but with VLESS everything is fine. I didn't touch the DNS rules.

**Comment by Mahdi-zarei** [comment]
There seems to be a slight bug with the DNS rules when no domain is set to use direct outbound, for now, please try setting the Routing settings->Routing Profile to bypass china, or manually create a profile and add a domain to use direct outbound.

**Comment by Mahdi-zarei** [comment]
try 4.0.10

**Comment by Sue1133** [comment]
It works, thanks.
