### ISSUE TITLE
[FR] Add sing-box yacd webui files and some improvemnts for it.

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#81]
I had this added, but just noticed on a fresh install if a user wants to use sing-box webui from its clash api url it needs yacd-meta files to be copied in ../nekoray/config/dashboard

I thought maybe bring the clash api menu to front instead of being hidden in core options and after profile startup add a single line that shows webui address, so users who has no idea it exists can check singbox webui.
Later when the auto select option is added it will be more useful.

Yacd-meta webui files: [Yacd-meta](https://github.com/MetaCubeX/yacd/archive/gh-pages.zip)

Again .... thanks for your awesome work.

**Comment by papampi** [comment]
So just noticed that it shows the api:
`INFO[0000] clash-api: restful api listening at 127.0.0.1:9090
`

But maybe users don't know how to use it, 
if secret is used: `http://127.0.0.1:9090/ui/?secret=SECRET`
or with no secret: `http://127.0.0.1:9090/ui/`

**Comment by Sue1133** [comment]
I think it's better to leave everything as it is and just add instructions to the documentation.
