### ISSUE TITLE
[FR] Automatic Rule Set Update

### ISSUE THREAD

**Issue by ccddos** [Mahdi-zarei/nekoray#85]
## Description Suggestions

I have found that the rule set appears to be compiled from `geoip.db` and `geosite.db`. However, these files do not update automatically and the rule set does not recompile.

## Necessity of Recommendations

Since websites and domains frequently change their IP addresses, it is **crucial** to ensure that the rule set is updated regularly. **Automating** the update process for `geoip.db` and `geosite.db` will ensure the rule set remains **accurate and effective**.

## Additional Resources

For example:
- Official set: [SagerNet sing-geosite](https://github.com/SagerNet/sing-geosite) and [SagerNet sing-geoip](https://github.com/SagerNet/sing-geoip)
- Mihomo set: [MetaCubeX meta-rules-dat](https://github.com/MetaCubeX/meta-rules-dat)

**Comment by papampi** [comment]
Almost same request as https://github.com/Mahdi-zarei/nekoray/issues/70

**Comment by ccddos** [comment]
got it
