### ISSUE TITLE
Random user-agent for non-tls configs

### ISSUE THREAD

**Issue by APT-ZERO** [Mahdi-zarei/nekoray#87]
Hello
Please add random User-Agent to non-tls configs
You can make users able to set their custom user-agent list, and a manual option to get a fresh list from
https://cdn.jsdelivr.net/gh/microlinkhq/top-user-agents@master/src/index.json
Thank you

**Comment by Mahdi-zarei** [comment]
Hello
I don't understand its usage, could you elaborate on why this feature might be needed?

**Comment by Mahdi-zarei** [comment]
So I believe what we need is the ability to set custom headers when using http Transport, this can be added.

**Comment by Mahdi-zarei** [comment]
Try 4.1.0
