### ISSUE TITLE
BUG: 希望恢复延迟测试颜色显示

### ISSUE THREAD

**Issue by HenryCarey** [Mahdi-zarei/nekoray#89]
在之前版本中是可以显示 Url Test 的颜色区分的，后来某个版本开始变成了黑色显示，无法快速分辨，

现在的 Url Test 如下图：
![截图2](https://github.com/user-attachments/assets/de02e17e-615a-4865-9bdd-2643027b47ef)

希望改回以前的 Url Test 如下图：
![截图](https://github.com/user-attachments/assets/dffd5422-bf94-45d4-a4f5-2801d091910e)

**Comment by M-Sadegh-M** [comment]
use vista theme

![image](https://github.com/user-attachments/assets/c8c3358e-c4e8-484b-b265-a15d1c3c0ebc)

**Comment by Mahdi-zarei** [comment]
This is enforced by the theme, besides Windows11 theme, all other themes have colors on windows, try them.

**Comment by HenryCarey** [comment]
> This is enforced by the theme, besides Windows11 theme, all other themes have colors on windows, try them.

但是vista主题有问题：
![截图3](https://github.com/user-attachments/assets/d429cf74-2fb0-42e7-be52-0e849b7f4c2d)

**Comment by Mahdi-zarei** [comment]
Restart the app once, Vista theme has a bit of bug.

**Comment by HenryCarey** [comment]
> Restart the app once, Vista theme has a bit of bug.

ok，好了，谢谢

**Comment by HenryCarey** [comment]
> use vista theme
> 
> ![image](https://private-user-images.githubusercontent.com/124435580/348622609-c8c3358e-c4e8-484b-b265-a15d1c3c0ebc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzUzMjcsIm5iZiI6MTcyMTAzNTAyNywicGF0aCI6Ii8xMjQ0MzU1ODAvMzQ4NjIyNjA5LWM4YzMzNThlLWM0ZTgtNDg0Yi1iMjY1LWExNWQxYzNjMGViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwOTE3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDFlNGQ4MTVlMTg2YTZmY2UzNDAyMWJlZjM3YTEwMTFkZDhlYTA1MTgyMzFjMDE5ZmY2NzliMzlkNzllYmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T-BCTRRBs0bB5cRBaAAfQZbXHKGScgWfFGCP36c-UUM)

Thanks！

**Comment by Mahdi-zarei** [comment]
> > Restart the app once, Vista theme has a bit of bug.
> 
> ok, it will be fine after restarting the app, thank you If possible, I still hope that the default theme can display the url test color

I will try, but i don't think it will be possible, In the code the test results are printed with color and the theme overrides them, also the theme itself is not editable.

**Comment by HenryCarey** [comment]
> > > Restart the app once, Vista theme has a bit of bug.
> > 
> > 
> > ok, it will be fine after restarting the app, thank you If possible, I still hope that the default theme can display the url test color
> 
> I will try, but i don't think it will be possible, In the code the test results are printed with color and the theme overrides them, also the theme itself is not editable.

ok, thanks!
