### ISSUE TITLE
BUG: MALICIOUS detect in virustotal.com

### ISSUE THREAD

**Issue by amirhoseinsadeghi** [Mahdi-zarei/nekoray#9]
![2024-05-17_210951](https://github.com/Mahdi-zarei/nekoray/assets/106965411/d4e9a8c4-f3f3-418b-90cf-2729efa22feb)
## Describe the problem
MALICIOUS and Trojan are detected in the zip program file on virustotal.com, why?
Expected behavior:

Actual behavior:

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by Mahdi-zarei** [comment]
Read the source code and the github actions and decide why. I should not be responsible for debugging a false-alarming virus scanner.
