### ISSUE TITLE
BUG: nekoray forgets last profile

### ISSUE THREAD

**Issue by midncircus** [Mahdi-zarei/nekoray#90]
nekoray may forget last selected profile even though "Remeber last profile" is enabled.

Sometimes it happens on a regular OS restart (which may be hard to reproduce). I suppose it happens mostly if nekoray window is visible (not closed to tray) when you restart the OS. Not sure about that.

A better way to reproduce is to end the nekoray task in the Task Manager. nekoray window should be visible again I think. I believe it happens every time in that case. (While ending tasks is not supposed usage scenario It still shouldn't reset settings and may be a convenient way to investigate why it happens on a regular OS restart)

**Comment by Mahdi-zarei** [comment]
Try 4.1.0
