### ISSUE TITLE
BUG: Requesting subscription error

### ISSUE THREAD

**Issue by ig-man** [Mahdi-zarei/nekoray#91]
## Update subscription failed 

All was fine with the update subscription to including the release 4.0.8-beta.2.
It does not work since 4.0.8 to 4.0.10. The same error : "Requesting subscription error: Failed to query the TLS context: An unsupported function was requested".
![4 0 8b2](https://github.com/user-attachments/assets/d65cec1a-4963-43a4-b80c-0f3f5057d6f2)

![4 0 10](https://github.com/user-attachments/assets/3b1da6e8-0ac3-4f2f-96a0-70b0c76001a8)

**Comment by Mahdi-zarei** [comment]
I assume you are using Win7, which release did you download? The problem is most likely because newer Qt versions do not support windows7 and so the TLS plugin is not functioning correctly.

**Comment by ig-man** [comment]
Thank you for your feedback! Yes, I am using Win7. There was no difference which release to use for win7 or win10, the same error both there and there. Only using VxKex I can launch the Nekoray on Win7.

**Comment by Mahdi-zarei** [comment]
You will need to wait until I implement a workaround for TLS requests in the windows7 build, I'm a bit busy so it will take some time.

**Comment by Mahdi-zarei** [comment]
Try 4.1.0
You should be able to use the group update ( and other http(s) features ).

**Comment by ig-man** [comment]
It works, thank you!
