### ISSUE TITLE
BUG: 4.0.10 无法使用Discord Windows版

### ISSUE THREAD

**Issue by HenryCarey** [Mahdi-zarei/nekoray#92]
已测试4.0.6版本打开系统代理即可打开Discord Windows版，
4.0.10 “Routing Profile”使用“Default”和“Bypass China”都无法使用Discord Windows版，提示“Update failed”（网页版正常）
尝试过添加“Discord”DOMAIN-SUFFIX规则，无效。

**Comment by Mahdi-zarei** [comment]
What proxy format do you use in the old version? Also could you check if the windows proxy settings differ in the 4.0.6 and 4.0.10 versions? 
proxy settings are in: Internet Options -> Connections -> Lan settings

**Comment by HenryCarey** [comment]
> What proxy format do you use in the old version? Also could you check if the windows proxy settings differ in the 4.0.6 and 4.0.10 versions? proxy settings are in: Internet Options -> Connections -> Lan settings

4.0.6使用的自带的“绕过局域网和大陆”，4.0.10使用的“Bypass China”，其它设置均未更改，
尝试设置DNS为remote或者direct都无法访问，
另外您提到的系统设置都未更改过（开启“系统代理”后，软件默认设置的）

**Comment by Mahdi-zarei** [comment]
That is a bit weird, can you try to set the port that nekoray uses to 1080 and see if it helps?

**Comment by HenryCarey** [comment]
> That is a bit weird, can you try to set the port that nekoray uses to 1080 and see if it helps?

端口改为1080依旧不行，我也感觉很奇怪....

**Comment by Mahdi-zarei** [comment]
I also use discord and cannot manage to reproduce this error, both 4.0.6 and 4.0.10 work well and discord uses the Nekoray to connect. The only thing I can think of for now is that another app is interfering with Nekoray, can you share a picture of Internet Options -> Connections -> Lan settings -> Advanced settings so we can check if it properly set?

**Comment by HenryCarey** [comment]
> I also use discord and cannot manage to reproduce this error, both 4.0.6 and 4.0.10 work well and discord uses the Nekoray to connect. The only thing I can think of for now is that another app is interfering with Nekoray, can you share a picture of Internet Options -> Connections -> Lan settings -> Advanced settings so we can check if it properly set?

截图如下：
![截图 2024-07-20](https://github.com/user-attachments/assets/866c4490-75d1-4685-a4b9-76ee107ff07c)

下面完整IP为：localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*

补充：我又找了一台没有开启或者安装其它代理软件的电脑，发现问题依旧。

**Comment by Mahdi-zarei** [comment]
At the point i don't see any problems in the windows settings, this problem is really odd...

**Comment by Mahdi-zarei** [comment]
If the problem is still there, try this:
First close discord
Set system proxy
in CMD, type: ipconfig /flushdns
open discord
see if this helps with the problem.
Also please share the nekoray logs if this did not solve the problem.

**Comment by HenryCarey** [comment]
> If the problem is still there, try this: First close discord Set system proxy in CMD, type: ipconfig /flushdns open discord see if this helps with the problem. Also please share the nekoray logs if this did not solve the problem.

我清除了其他日志，只打开Discord 出现以下日志，然后就会出现报错：Update failed
日志：
```
INFO[0032] [2261927345 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:13038
INFO[0032] [2261927345 1ms] inbound/mixed[mixed-in]: inbound connection to 4.1.82.179:443
INFO[0032] [2261927345 312ms] outbound/socks[proxy]: outbound connection to 4.1.82.179:443
```

**Comment by Mahdi-zarei** [comment]
This is because discord does not respect the system proxy, I assume the only way to open it is to use Tun mode.

**Comment by HenryCarey** [comment]
> This is because discord does not respect the system proxy, I assume the only way to open it is to use Tun mode.

看来只能启用 TUN 了，再次感谢！
