### ISSUE TITLE
Block UDP:443

### ISSUE THREAD

**Issue by mbm13781221** [Mahdi-zarei/nekoray#93]
Hi.
Can you add UDP/QUIC:443 block with Iran bypass ruleset?
It is very useful with Hysteria2 protocol.
"https://v2.hysteria.network/docs/misc/About-HTTP3/"

**Comment by Mahdi-zarei** [comment]
Hello
You can easily block it yourself using the routing section, and since blocking udp on port 443 is not a widely needed rule, it cannot be added to the predefined rules.
