### ISSUE TITLE
BUG: Renaming or deleting the front/landing proxy crashes Nekoray

### ISSUE THREAD

**Issue by Turbine8845** [Mahdi-zarei/nekoray#95]
## Describe the problem
Nekoray crashes if you change the name of the front/landing proxy or delete it.

## Expected behavior:
Nekoray should not crash when the front/landing proxy is changed or deleted. Instead, it should update the front/landing proxy of the subgroup to either a known proxy or set it to none.

## Actual behavior:
When the front/landing proxy is deleted or changed (for example, due to updating the subgroup that includes the front/landing proxy) and you click on "Edit selected group" for the subgroup that used the front/landing proxy, Nekoray crashes.

## How to reproduce
1. Create a subgroup and select a front/landing proxy for it.
2. Rename or delete the front/landing proxy.
3. Click on "Edit selected group" for the created subgroup.

Nekoray will crash and display a message like the one shown in the following screenshot:

![Nekoray_bug](https://github.com/user-attachments/assets/37546fcf-042d-4f54-a0cd-ff67d8351909)

## log
```log
2024/08/01 20:02:03 parent exited: exit status 0xc0000005 <nil>
```

## Temporary solution
Go to the `nekoray/config/groups` directory and open the JSON file for the problematic subgroup using a text editor. Change the number written in front of `"front_proxy_id":` or `"landing_proxy_id":` to `-1` and relaunch Nekoray.

**Comment by Mahdi-zarei** [comment]
Try 4.1.0

**Comment by Turbine8845** [comment]
Dear Mahdi,
Thank you for updating Nekoray. Unfortunately, version 4.1.1 has caused some issues with my installation. I've detailed the problems in https://github.com/Mahdi-zarei/nekoray/issues/104. I've reverted to the previous version for now, but I plan to further test a separate installation of version 4.1.1 and will report any additional issues I encounter.
