### ISSUE TITLE
BUG: The time of pinging the url from the configs increases the CPU processing, and you have to close the neckbox_core file with the task manager.

### ISSUE THREAD

**Issue by javad490** [Mahdi-zarei/nekoray#96]
## Describe the problem
The time of pinging the url from the configs increases the CPU processing, and you have to close the neckbox_core file with the task manager.
Expected behavior:
CPU intensive processing with Nekobox_core.exe file in Windows 11 on url test and hang app, must close this file via windows task manage
Actual behavior:
بالا رفتن شدید پردازش در زمان پینگ گرفتن url test در ویندوز 11 که حتی با بستن برنامه هم رفع نمیشود و باعث هنگ برنامه میشود که باید از داخل تسک منیجر ویندوز فایل nekobox_core.exe را بست 
## log

آخرین ورژن پرتابل روی ویندوز 11 این مشکل را دارد و چند ورژن قبلی هم چنین مشکلی داشت که نمیتوان پینگ از کانفیگها گرفت

**Comment by Mahdi-zarei** [comment]
Try 4.1.0
