### ISSUE TITLE
Inbound proxy settings

### ISSUE THREAD

**Issue by Sue1133** [Mahdi-zarei/nekoray#98]
Why did you remove the option to set a password on the proxy and remove information about the proxy type?

![pic1](https://github.com/user-attachments/assets/17b9ea2b-6f67-41c5-b8e3-67547bff3c72)
4.0.10

![pic2](https://github.com/user-attachments/assets/fd72a750-af2f-45a5-a7c9-0b60c752effe)
Latest nightly build

**Comment by Mahdi-zarei** [comment]
> Why did you remove the option to set a password on the proxy

Practically for a use which uses the proxy for his own device authentication is meaningless. And if you want to share your proxy across lan, I suggest you add a Custom inbound for it.



> remove information about the proxy type

Part of deleting old useless features, can be added back of course.

**Comment by Mahdi-zarei** [comment]
> > Part of deleting old useless features, can be added back of course.
> 
> Then could you please add them again?

Do you mean the part that clarifies about SOCKS+HTTP? I'm a bit confused why that is of such concern, even though I will be adding a tooltip to add the deleted information back.

**Comment by Sue1133** [comment]
It would also be possible to set a password

**Comment by Mahdi-zarei** [comment]
Why is password needed for an inbound on a personal system? As i said earlier, if you need to share your proxy and you want to set auth, you need to use custom inbound.

**Comment by Sue1133** [comment]
Sorry, but I use it to share my connection with friends. Previously, this could be simply configured in the interface, but you removed it.

**Comment by Mahdi-zarei** [comment]
I see, please first try to use the custom inbound feature, if there are more requests, I will bring back this feature.
The reason that i removed it the first place, was that it was adding an unnecessary complexity to many parts of the app that were using the proxy ( like update subs with proxy ) and since this feature was not used much, I removed it to simplify the codebase.

**Comment by Sue1133** [comment]
Thanks for the explanation, I'll try to figure it out.

**Comment by Mahdi-zarei** [comment]
you can export the sing-box config of a profile then copy the mixed-in inbound and change the port, tag, and add auth to it and add it to custom inbound.
