### ISSUE TITLE
刚试了新版。发现删了右键删除重复配置功能。

### ISSUE THREAD

**Issue by sjjiqtkgg** [Mahdi-zarei/nekoray#99]
有时导入节点多，很多重复节点可以一键删除。本人感觉这功能还是满实用的。希望在下次更新能恢复

**Comment by sjjiqtkgg** [comment]
导入节点在原有的分组无效，要建新分组才行，本来想移动节点，发现没有这功能，后来用分享复制功能。发现不能从B分组复制到A分组中。新建C分组后可以分享复制。
![image](https://github.com/user-attachments/assets/b25a4119-077e-48b2-8b53-70220c0b2b7e)
原分组导入
![image](https://github.com/user-attachments/assets/56e4d306-f7d7-4202-91b0-ca7549a89133)

**Comment by Mahdi-zarei** [comment]
> 有时导入节点多，很多重复节点可以一键删除。本人感觉这功能还是满实用的。希望在下次更新能恢复

I will try to restore the useful options and add some more to help those who use many profiles
by the way you can use ctrl + c and ctrl + v to export and import profiles
also you can use ctrl while clicking profiles to select multiple profiles and export them at once

**Comment by Mahdi-zarei** [comment]
> Importing nodes is invalid in the original group, and you need to create a new group. I originally wanted to move the node, but found that there is no such function, so I later used the share and copy function. It is found that it cannot be copied from group B to group A. After creating a new C group, you can share and copy it. ![image](https://private-user-images.githubusercontent.com/95971362/357745306-b25a4119-077e-48b2-8b53-70220c0b2b7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2Mjk4MjQsIm5iZiI6MTcyMzYyOTUyNCwicGF0aCI6Ii85NTk3MTM2Mi8zNTc3NDUzMDYtYjI1YTQxMTktMDc3ZS00OGIyLThiNTMtNzAyMjBjMGIyYjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA5NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YmZjM2JkM2JkZWFhZmNlMTcwNDgyNmIxNzNmMGZlYmMyOGJkZGY2NTZlNDdmMzRjMDJkOThlMzAyYzA3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N4QPaKntFDNcJ3O60Bw243nGLYp7xhkVvGEpbQ3ddWI) Original group import ![image](https://private-user-images.githubusercontent.com/95971362/357745826-56e4d306-f7d7-4202-91b0-ca7549a89133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2Mjk4MjQsIm5iZiI6MTcyMzYyOTUyNCwicGF0aCI6Ii85NTk3MTM2Mi8zNTc3NDU4MjYtNTZlNGQzMDYtZjdkNy00MjAyLTkxYjAtY2E3NTQ5YTg5MTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA5NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OWI3ZGEyZTM2YmI2ZGI3MjQ5MzBiOGZjMDQxZjIzZmZlNzUzYjI2YTNmMjljMmM2MTUzYzEyYjRiYTc3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QFuWHWBlrPu3qOlq4w2IC_MgjyubwPRDZGmpnd0hpIQ)

These seems to be a bug in rendering profiles in groups, even though a profile gets imported it will not be shown.

**Comment by sjjiqtkgg** [comment]
> > 导入节点在原有组内无效，需要新建组，本来想移动节点，但是发现没有这个功能，后来用了共享复制功能，发现不能从B组复制到A组，新建C组后就可以共享复制了。![图像](https://private-user-images.githubusercontent.com/95971362/357745306-b25a4119-077e-48b2-8b53-70220c0b2b7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2Mjk4MjQsIm5iZiI6MTcyMzYyOTUyNCwicGF0aCI6Ii85NTk3MTM2Mi8zNTc3NDUzMDYtYjI1YTQxMTktMDc3ZS00OGIyLThiNTMtNzAyMjBjMGIyYjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA5NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YmZjM2JkM2JkZWFhZmNlMTcwNDgyNmIxNzNmMGZlYmMyOGJkZGY2NTZlNDdmMzRjMDJkOThlMzAyYzA3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N4QPaKntFDNcJ3O60Bw243nGLYp7xhkVvGEpbQ3ddWI)原组导入![图像](https://private-user-images.githubusercontent.com/95971362/357745826-56e4d306-f7d7-4202-91b0-ca7549a89133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2Mjk4MjQsIm5iZiI6MTcyMzYyOTUyNCwicGF0aCI6Ii85NTk3MTM2Mi8zNTc3NDU4MjYtNTZlNGQzMDYtZjdkNy00MjAyLTkxYjAtY2E3NTQ5YTg5MTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA5NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OWI3ZGEyZTM2YmI2ZGI3MjQ5MzBiOGZjMDQxZjIzZmZlNzUzYjI2YTNmMjljMmM2MTUzYzEyYjRiYTc3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QFuWHWBlrPu3qOlq4w2IC_MgjyubwPRDZGmpnd0hpIQ)
> 
> 这似乎是在分组渲染配置文件时的一个错误，即使导入了配置文件也不会显示。

是的，我重新4..0.1复盖后节点显示了

**Comment by Mahdi-zarei** [comment]
Try 4.1.1

**Comment by sjjiqtkgg** [comment]
> 尝试 4.1.1
感谢，问题解决.
